/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "GEOResourceManifestTileGroupObserver-Protocol.h"

@class NSObject<OS_dispatch_queue>, VKResourceManager;

// Not exported
@interface VKGGLTextureManager : NSObject <GEOResourceManifestTileGroupObserver>
{
    unsigned int _tileGroupIdentifier;
    NSObject<OS_dispatch_queue> *_textureQueue;
    struct map<std::__1::basic_string<char>, geo::fast_shared_ptr<ggl::Texture2D>, std::__1::less<std::__1::basic_string<char>>, std::__1::allocator<std::__1::pair<const std::__1::basic_string<char>, geo::fast_shared_ptr<ggl::Texture2D>>>> _textureDictionary;
    VKResourceManager *_resourceManager;
    struct Device *_device;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)purge;
- (void)resourceManifestManagerDidChangeActiveTileGroup:(id)arg1;
- (void)resourceManifestManagerWillChangeActiveTileGroup:(id)arg1;
- (fast_shared_ptr_2ab6109a)textureWithName:(id)arg1 forScale:(float)arg2 mipmap:(_Bool)arg3;
- (fast_shared_ptr_2ab6109a)textureWithName:(id)arg1 forScale:(float)arg2;
- (fast_shared_ptr_2ab6109a)textureWithName:(id)arg1 mipmap:(_Bool)arg2;
- (fast_shared_ptr_2ab6109a)textureWithName:(id)arg1;
- (id)dataWithName:(id)arg1 fromResourceManager:(id)arg2;
- (void)dealloc;
- (id)initWithTileGroupIdentifier:(unsigned int)arg1 resourceManager:(id)arg2 device:(struct Device *)arg3;

@end

