/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <VectorKit/VKPolygonGroup.h>

@class GEOFeatureStyleAttributes, VKSharedResources;

// Not exported
@interface VKTexturedPolygonGroup : VKPolygonGroup
{
    VKSharedResources *_sharedResources;
    fast_shared_ptr_2ab6109a _texture;
    fast_shared_ptr_2ab6109a _textureVariant;
    _Bool _needsTextureUpdate;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)updateTextures;
- (void)updateTexturesIfNecessary;
- (void)setNeedsTextureUpdate;
@property(readonly, nonatomic) GEOFeatureStyleAttributes *styleAttributes;
- (fast_shared_ptr_2ab6109a)_textureForName:(id)arg1;
- (void)dealloc;
- (id)initWithStyleQuery:(shared_ptr_6e6219d6 *)arg1 tile:(id)arg2 contentScale:(float)arg3 sharedResources:(id)arg4;
@property(readonly, nonatomic) struct Texture2D *textureVariant;
@property(readonly, nonatomic) struct Texture2D *texture;

@end

