/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSObject<OS_dispatch_queue>, NSTimer, WBSCloudHistorySyncThrottler;

@interface WBSCloudHistory : NSObject
{
    NSObject<OS_dispatch_queue> *_cloudHistoryQueue;
    _Bool _cloudHistoryEnabled;
    _Bool _saveChangesWhenHistoryLoads;
    _Bool _fetchChangesWhenHistoryLoads;
    id <NSObject> _historyWasLoadedObserver;
    struct unique_ptr<SafariShared::SuddenTerminationDisabler, std::__1::default_delete<SafariShared::SuddenTerminationDisabler>> _saveOperationSuddenTerminationDisabler;
    struct unique_ptr<SafariShared::SuddenTerminationDisabler, std::__1::default_delete<SafariShared::SuddenTerminationDisabler>> _fetchOperationSuddenTerminationDisabler;
    WBSCloudHistorySyncThrottler *_saveChangesThrottler;
    NSTimer *_saveChangesLaterTimer;
}

+ (id)sharedCloudHistory;
@property(nonatomic, getter=isCloudHistoryEnabled) _Bool cloudHistoryEnabled; // @synthesize cloudHistoryEnabled=_cloudHistoryEnabled;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)_saveChangesLaterTimerFired:(id)arg1;
- (void)_scheduleSaveChangesLaterTimerWithInterval:(double)arg1;
- (double)_backoffTimeIntervalFromError:(id)arg1;
- (long long)_resultFromError:(id)arg1;
- (long long)_priorityForSaveWithVisits:(id)arg1 tombstones:(id)arg2 bypassingThrottler:(_Bool)arg3;
- (void)_historyWasLoaded:(id)arg1;
- (void)_registerForHistoryWasLoadedNotificationIfNecessary;
- (void)_fetchChangesWhenHistoryLoads;
- (void)_saveChangesWhenHistoryLoads;
- (void)_fetchAndMergeChangesWithServerChangeTokenData:(id)arg1 intoHistory:(id)arg2;
- (void)fetchAndMergeChanges;
- (void)_saveVisits:(id)arg1 tombstones:(id)arg2 toCloudHistoryBypassingThrottler:(_Bool)arg3 withCallback:(id)arg4;
- (void)_saveChangesToCloudHistoryStoreBypassingThrottler:(_Bool)arg1;
- (void)saveChangesToCloudHistoryStoreBypassingThrottler;
- (void)saveChangesToCloudHistoryStore;
- (_Bool)cloudHistoryEnabled;
- (void)dealloc;
- (id)init;

@end

