/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "SGMailClient-Protocol.h"

@class NSArray, NSMutableArray;

@interface SGFakeMailClient : NSObject <SGMailClient>
{
    NSMutableArray *_messages;
    NSMutableArray *_fullDownloadRequests;
}

@property(readonly) NSArray *fullDownloadRequests; // @synthesize fullDownloadRequests=_fullDownloadRequests;
- (void).cxx_destruct;
- (void)requestRichDownloadOfMessagesWithReferences:(id)arg1;
- (id)messagesWithIds:(id)arg1 onMessage:(id)arg2;
- (id)allMessagesSince:(id)arg1 onMessage:(id)arg2;
- (void)addMessage:(id)arg1 source:(id)arg2;
- (id)init;

@end

