/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "SGPipelineDissector-Protocol.h"

@class NSArray;

@interface SGParallelDissector : NSObject <SGPipelineDissector>
{
    NSArray *_dissectors;
}

+ (id)parallelDissectorWithDissectors:(id)arg1;
- (void).cxx_destruct;
- (void)dissect:(id)arg1;
- (id)initWithDissectors:(id)arg1;

@end

