/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSDateFormatter, NSSet;

@interface SGReverseTemplatesJSDataDetectors : NSObject
{
    struct __DDScanner *_scanner;
    NSSet *_availLocales;
    NSDateFormatter *_dateFormatter;
    NSDateFormatter *_naiveDateFormatter;
    NSDateFormatter *_noTimeFormatter;
}

- (void).cxx_destruct;
- (id)runDataDetectors:(id)arg1 locale:(id)arg2 epoch:(double)arg3;
- (id)init;

@end

