/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableDictionary, NSString;

@interface RKResponseCollection : NSObject
{
    NSString *_context;
    NSMutableDictionary *_responseCatalog;
}

+ (id)responseCollectionWithContext:(id)arg1;
@property(retain) NSMutableDictionary *responseCatalog; // @synthesize responseCatalog=_responseCatalog;
@property(retain) NSString *context; // @synthesize context=_context;
- (void).cxx_destruct;
- (id)responsesForCategory:(unsigned long long)arg1 gender:(unsigned long long)arg2 maximumResponses:(unsigned long long)arg3 withLanguage:(id)arg4 options:(unsigned long long)arg5;
- (void)resetResponseCatalog;
- (id)_initWithContext:(id)arg1;
- (id)init;

@end

