/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "BSXPCCoding-Protocol.h"

@interface FBSSceneOcclusion : NSObject <BSXPCCoding>
{
    struct CGRect _rect;
}

+ (id)occlusionWithRect:(struct CGRect)arg1;
+ (id)fullOcclusion;
- (void)encodeWithXPCDictionary:(id)arg1;
- (id)initWithXPCDictionary:(id)arg1;
- (id)description;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqualToOcclusion:(id)arg1;
- (struct CGRect)CGRect;
- (id)init;
- (id)_initWithCGRect:(struct CGRect)arg1;

@end

