/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class BSMutableSettings;

@interface FBSSceneClientSettingsDiffInspector : NSObject
{
    BSMutableSettings *_observerInfo;
    _Bool _iteratingObservers;
}

- (id)description;
- (void)_addObserver:(id)arg1 forSetting:(unsigned long long)arg2 inInfo:(id)arg3;
- (void)observeOtherSetting:(unsigned long long)arg1 withBlock:(id)arg2;
- (void)observeOcclusionsWithBlock:(id)arg1;
- (void)observePreferredInterfaceOrientationWithBlock:(id)arg1;
- (void)observeClassWithBlock:(id)arg1;
- (void)removeAllObservers;
- (void)inspectDiff:(id)arg1 withContext:(void *)arg2;
- (void)dealloc;
- (id)init;

@end

