/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <CloudKitDaemon/CKDURLRequest.h>

@class CKShareID, NSArray, NSMutableDictionary;

@interface CKDLikeItemsURLRequest : CKDURLRequest
{
    id _itemLikedProgressBlock;
    NSArray *_itemIDsToLike;
    NSArray *_itemIDsToUnlike;
    CKShareID *_shareID;
    NSMutableDictionary *_itemIDsByRequestID;
}

@property(retain, nonatomic) NSMutableDictionary *itemIDsByRequestID; // @synthesize itemIDsByRequestID=_itemIDsByRequestID;
@property(retain, nonatomic) CKShareID *shareID; // @synthesize shareID=_shareID;
@property(retain, nonatomic) NSArray *itemIDsToUnlike; // @synthesize itemIDsToUnlike=_itemIDsToUnlike;
@property(retain, nonatomic) NSArray *itemIDsToLike; // @synthesize itemIDsToLike=_itemIDsToLike;
@property(copy, nonatomic) id itemLikedProgressBlock; // @synthesize itemLikedProgressBlock=_itemLikedProgressBlock;
- (void).cxx_destruct;
- (void)requestDidParseNodeFailure:(id)arg1;
- (void)requestDidParseProtobufObject:(id)arg1;
- (id)requestOperations;
- (id)requestOperationClasses;
- (long long)partitionType;
- (long long)serverType;
- (int)operationType;
- (id)initWithItemIDsToLike:(id)arg1 itemIDsToUnlike:(id)arg2 inShare:(id)arg3;

@end

