/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "PBRequest.h"

#import "NSCopying-Protocol.h"

@class CKDPIdentifier, NSData;

@interface CKDPInvitationAcceptRequest : PBRequest <NSCopying>
{
    CKDPIdentifier *_invitationId;
    NSData *_parameters;
}

+ (id)options;
@property(retain, nonatomic) NSData *parameters; // @synthesize parameters=_parameters;
@property(retain, nonatomic) CKDPIdentifier *invitationId; // @synthesize invitationId=_invitationId;
- (void).cxx_destruct;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (Class)responseClass;
- (unsigned int)requestTypeCode;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(readonly, nonatomic) _Bool hasParameters;
@property(readonly, nonatomic) _Bool hasInvitationId;

@end

