/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "CKDResponseBodyParser-Protocol.h"

@class NSData, NSError, NSMutableData, NSObject<OS_dispatch_queue>;

@interface CKDProtobufResponseBodyParser : NSObject <CKDResponseBodyParser>
{
    _Bool _isParsing;
    Class _messageClass;
    id _objectParsedBlock;
    NSError *_parserError;
    NSObject<OS_dispatch_queue> *_parseQueue;
    NSData *_parserData;
    NSMutableData *_tailParserData;
    unsigned long long _curObjectLength;
}

@property(nonatomic) _Bool isParsing; // @synthesize isParsing=_isParsing;
@property(nonatomic) unsigned long long curObjectLength; // @synthesize curObjectLength=_curObjectLength;
@property(retain, nonatomic) NSMutableData *tailParserData; // @synthesize tailParserData=_tailParserData;
@property(retain, nonatomic) NSData *parserData; // @synthesize parserData=_parserData;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *parseQueue; // @synthesize parseQueue=_parseQueue;
@property(retain, nonatomic) NSError *parserError; // @synthesize parserError=_parserError;
@property(copy, nonatomic) id objectParsedBlock; // @synthesize objectParsedBlock=_objectParsedBlock;
@property(nonatomic) Class messageClass; // @synthesize messageClass=_messageClass;
- (void).cxx_destruct;
- (void)finishWithCompletion:(id)arg1;
- (void)processData:(id)arg1;
- (_Bool)_parseObjects:(_Bool)arg1;
- (_Bool)_parseObjectFromData:(id)arg1;
- (id)init;

@end

