/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class CKDClientContext, CKDPCSCache, CKDPCSData, NSMutableDictionary, NSOperationQueue, NSString;

@interface CKDPCSManager : NSObject
{
    struct _PCSIdentityData *_publicZoneIdentity;
    CKDClientContext *_context;
    NSOperationQueue *_operationQueue;
    CKDPCSCache *_zoneCache;
    CKDPCSCache *_shareCache;
    CKDPCSCache *_publicRecordCache;
    NSMutableDictionary *_recordCacheByPrivateZoneID;
    struct _PCSIdentityData *_myPCSIdentity;
    NSString *_serviceName;
    CKDPCSData *_defaultPublicZonePCSData;
}

@property(readonly, nonatomic) CKDPCSData *defaultPublicZonePCSData; // @synthesize defaultPublicZonePCSData=_defaultPublicZonePCSData;
@property(retain, nonatomic) NSString *serviceName; // @synthesize serviceName=_serviceName;
@property(nonatomic) struct _PCSIdentityData *myPCSIdentity; // @synthesize myPCSIdentity=_myPCSIdentity;
@property(retain, nonatomic) NSMutableDictionary *recordCacheByPrivateZoneID; // @synthesize recordCacheByPrivateZoneID=_recordCacheByPrivateZoneID;
@property(retain, nonatomic) CKDPCSCache *publicRecordCache; // @synthesize publicRecordCache=_publicRecordCache;
@property(retain, nonatomic) CKDPCSCache *shareCache; // @synthesize shareCache=_shareCache;
@property(retain, nonatomic) CKDPCSCache *zoneCache; // @synthesize zoneCache=_zoneCache;
@property(retain, nonatomic) NSOperationQueue *operationQueue; // @synthesize operationQueue=_operationQueue;
@property(readonly, nonatomic) __weak CKDClientContext *context; // @synthesize context=_context;
- (void).cxx_destruct;
- (id)referenceSignatureFromAssetKey:(id)arg1;
- (id)referenceIdentifierStringFromAssetKey:(id)arg1;
- (id)newAssetKey;
- (id)wrapAssetKey:(id)arg1 withRecordPCS:(struct _OpaquePCSShareProtection *)arg2 withError:(id *)arg3;
- (id)unwrapAssetKey:(id)arg1 withRecordPCS:(struct _OpaquePCSShareProtection *)arg2 withError:(id *)arg3;
- (void)setPCSData:(id)arg1 forFetchedShareID:(id)arg2;
- (void)setPCSData:(id)arg1 forFetchedRecordID:(id)arg2 withScope:(long long)arg3;
- (void)setPCSData:(id)arg1 forFetchedZoneID:(id)arg2 withScope:(long long)arg3;
- (void)fetchPCSForShareWithID:(id)arg1 operation:(id)arg2 fetchFromServer:(_Bool)arg3 withCompletionHandler:(id)arg4;
- (void)_fetchPCSForShareWithIDFromServer:(id)arg1 operation:(id)arg2 forCache:(id)arg3;
- (void)fetchPCSForRecordWithID:(id)arg1 operation:(id)arg2 fetchFromServer:(_Bool)arg3 withCompletionHandler:(id)arg4;
- (id)_newPCSRecordCache;
- (void)_fetchPCSForRecordWithIDFromServer:(id)arg1 operation:(id)arg2 forCache:(id)arg3;
- (void)fetchPCSForZoneWithID:(id)arg1 operation:(id)arg2 fetchFromServer:(_Bool)arg3 withCompletionHandler:(id)arg4;
- (void)_fetchPCSForZoneWithIDFromServer:(id)arg1 operation:(id)arg2 forCache:(id)arg3;
- (void)_saveNewPCSOnDefaultZone:(id)arg1 operation:(id)arg2 cache:(id)arg3;
- (id)etagFromRecordPCS:(struct _OpaquePCSShareProtection *)arg1 error:(id *)arg2;
- (struct _OpaquePCSShareProtection *)createRecordPCSFromData:(id)arg1 zonePCS:(struct _OpaquePCSShareProtection *)arg2 error:(id *)arg3;
- (id)dataFromRecordPCS:(struct _OpaquePCSShareProtection *)arg1 error:(id *)arg2;
- (struct _OpaquePCSShareProtection *)createRecordPCSWithZonePCS:(struct _OpaquePCSShareProtection *)arg1 error:(id *)arg2;
- (id)repairZonePCSData:(id)arg1 error:(id *)arg2;
- (id)etagFromZonePCS:(struct _OpaquePCSShareProtection *)arg1 error:(id *)arg2;
- (struct _OpaquePCSShareProtection *)createZonePCSFromData:(id)arg1 error:(id *)arg2;
- (id)dataFromZonePCS:(struct _OpaquePCSShareProtection *)arg1 error:(id *)arg2;
- (struct _OpaquePCSShareProtection *)createZonePCSWithError:(id *)arg1;
- (id)defaultPublicZonePCSDataWithError:(id *)arg1;
- (id)etagFromPCSData:(id)arg1;
- (id)_operationInfoOfClass:(Class)arg1 fromOperation:(id)arg2;
- (struct _PCSIdentityData *)copyServiceIdentityWithError:(id *)arg1;
- (struct _PCSIdentityData *)copyPublicZoneIdentity;
- (void)dealloc;
- (id)initWithClientContext:(id)arg1;
- (id)_serviceNameForContainerID:(id)arg1;
- (void)clearPCSCaches;

@end

