/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "PBCodable.h"

#import "NSCopying-Protocol.h"

@class NSMutableArray, NSString;

@interface CKDPPulseResponse : PBCodable <NSCopying>
{
    NSString *_currentEtag;
    NSMutableArray *_userDatas;
}

@property(retain, nonatomic) NSMutableArray *userDatas; // @synthesize userDatas=_userDatas;
@property(retain, nonatomic) NSString *currentEtag; // @synthesize currentEtag=_currentEtag;
- (void).cxx_destruct;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
- (id)userDataAtIndex:(unsigned long long)arg1;
- (unsigned long long)userDatasCount;
- (void)addUserData:(id)arg1;
- (void)clearUserDatas;
@property(readonly, nonatomic) _Bool hasCurrentEtag;

@end

