/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "CKPackage.h"

@interface CKPackage (SectionPlanning)
- (id)planWithMMCS:(id)arg1 completionHandler:(id)arg2;
- (id)_MMCSItemsFromPackageItems:(id)arg1;
@end

