/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "QLPreviewItem-Protocol.h"

@class NSString, NSURL;

@interface CKAttachmentItem : NSObject <QLPreviewItem>
{
    struct CGSize _squarePreviewSize;
    struct CGSize _posterPreviewSize;
    NSURL *_fileURL;
    NSString *_guid;
    NSURL *_squarePreviewURL;
    NSURL *_posterPreviewURL;
    struct CGSize _backingSize;
}

+ (id)UTITypes;
+ (struct CGSize)defaultSizeForType:(long long)arg1;
+ (void)cancelPreviewGeneration;
+ (id)saveQueue;
+ (id)previewQueue;
+ (id)previewCache;
@property(copy, nonatomic) NSURL *posterPreviewURL; // @synthesize posterPreviewURL=_posterPreviewURL;
@property(copy, nonatomic) NSURL *squarePreviewURL; // @synthesize squarePreviewURL=_squarePreviewURL;
@property(nonatomic) struct CGSize backingSize; // @synthesize backingSize=_backingSize;
@property(copy, nonatomic) NSString *guid; // @synthesize guid=_guid;
@property(copy, nonatomic) NSURL *fileURL; // @synthesize fileURL=_fileURL;
@property(readonly) NSURL *previewItemURL;
- (struct CGSize)size;
- (id)pasteboardItem;
- (id)UTIType;
- (id)cachedPreviewForType:(long long)arg1 withSize:(struct CGSize)arg2;
- (id)_generatePreviewURLForType:(long long)arg1 withSize:(struct CGSize)arg2;
- (void)_savePreview:(id)arg1 forType:(long long)arg2 forSize:(struct CGSize)arg3;
- (void)generatePreviewForSize:(struct CGSize)arg1 withType:(long long)arg2 queue:(id)arg3 completion:(id)arg4;
- (id)_savedPreviewFromURL:(id)arg1;
- (id)description;
- (void)dealloc;
- (id)imageData;
- (id)initWithFileURL:(id)arg1 size:(struct CGSize)arg2 guid:(id)arg3;

// Remaining properties
@property(readonly) NSString *previewItemTitle;

@end

