/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface CKAudioSessionController : NSObject
{
    _Bool _active;
    _Bool _shouldUseSpeaker;
    _Bool _needsResetAudioSessionCategory;
}

+ (id)audioSessionQueue;
+ (id)shareInstance;
@property(nonatomic) _Bool needsResetAudioSessionCategory; // @synthesize needsResetAudioSessionCategory=_needsResetAudioSessionCategory;
@property _Bool shouldUseSpeaker; // @synthesize shouldUseSpeaker=_shouldUseSpeaker;
@property(getter=isActive) _Bool active; // @synthesize active=_active;
- (void)audioSessionRouteChange:(id)arg1;
- (void)setActive:(_Bool)arg1 shouldUseSpeaker:(_Bool)arg2 force:(_Bool)arg3 completion:(id)arg4;
- (void)configureAudioSession:(_Bool)arg1;
- (void)setActive:(_Bool)arg1 shouldUseSpeaker:(_Bool)arg2 completion:(id)arg3;
- (void)resetAudioSessionCategoryIfNeeded;
- (id)init;
- (void)dealloc;

@end

