/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "IMSystemMonitorListener-Protocol.h"

@class CKDispatchCache, CKMultiDict;

@interface CKPreviewDispatchCache : NSObject <IMSystemMonitorListener>
{
    CKDispatchCache *_dispatchCache;
    CKMultiDict *_pendingBlocks;
}

+ (id)transcriptPreviewCache;
+ (id)mapThumbnailQueue;
@property(retain, nonatomic) CKMultiDict *pendingBlocks; // @synthesize pendingBlocks=_pendingBlocks;
@property(retain, nonatomic) CKDispatchCache *dispatchCache; // @synthesize dispatchCache=_dispatchCache;
- (_Bool)shouldReplaceCachedPreview:(id)arg1 withPreview:(id)arg2;
- (void)transferRemoved:(id)arg1;
- (void)transferFinished:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)flush;
- (void)systemApplicationDidSuspendForEventsOnly;
- (void)systemApplicationDidSuspend;
- (id)notificationCenter;
- (id)mediaObjectManager;
- (void)resume;
- (void)endGeneratingForKey:(id)arg1;
- (void)beginGeneratingForKey:(id)arg1;
- (_Bool)isGeneratingPreviewForKey:(id)arg1;
- (void)setCachedPreview:(id)arg1 key:(id)arg2;
- (id)cachedPreviewForKey:(id)arg1;
- (void)enqueueGenerationBlock:(id)arg1 completion:(void)arg2 withPriority:(id)arg3 forKey:(void)arg4;
- (void)enqueueSaveBlock:(id)arg1 withPriority:(void)arg2;
- (id)init;
- (void)dealloc;
- (void)enqueueSaveBlock:(id)arg1 forMediaObject:(void)arg2 withPriority:(id)arg3;

@end

