/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <Search/SPSection.h>

#import "PRSMovieListSection-Protocol.h"

@class NSArray, NSString, NSURL;

@interface SPMovieListSection : SPSection <PRSMovieListSection>
{
}


// Remaining properties
@property(retain, nonatomic) NSArray *movies; // @dynamic movies;
@property(retain, nonatomic) NSString *subtitle; // @dynamic subtitle;
@property(retain, nonatomic) NSString *title; // @dynamic title;
@property(retain, nonatomic) NSString *type;
@property(retain, nonatomic) NSURL *url;
@end

