/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "SFContinuityScanManagerObserver-Protocol.h"

@interface SFBluetoothBrowser : NSObject <SFContinuityScanManagerObserver>
{
    id <SFBluetoothBrowserDelegate> _delegate;
}

@property id <SFBluetoothBrowserDelegate> delegate; // @synthesize delegate=_delegate;
- (void)scanManager:(id)arg1 updatedFoundDeviceList:(id)arg2;
- (id)init;

@end

