/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "SFCompanionXPCManagerObserver-Protocol.h"
#import "SFContinuityScannerClient-Protocol.h"

@class NSHashTable, NSMutableArray;

// Not exported
@interface SFContinuityScanManager : NSObject <SFCompanionXPCManagerObserver, SFContinuityScannerClient>
{
    id <SFContinuityScannerProtocol> _connectionProxy;
    NSMutableArray *_queuedIdentifers;
    NSHashTable *_observers;
}

+ (id)sharedManager;
@property(retain) NSHashTable *observers; // @synthesize observers=_observers;
@property(retain) NSMutableArray *queuedIdentifers; // @synthesize queuedIdentifers=_queuedIdentifers;
@property(retain) id <SFContinuityScannerProtocol> connectionProxy; // @synthesize connectionProxy=_connectionProxy;
- (void)xpcManagerConnectionInterrupted;
- (void)updatedFoundDeviceList:(id)arg1;
- (void)receivedAdvertisement:(id)arg1;
- (void)payloadForIdentifier:(id)arg1 withCompletionHandler:(id)arg2;
- (void)removeObserver:(id)arg1;
- (void)addObserver:(id)arg1;
- (void)setupXPCConnection;
- (void)dealloc;
- (id)init;

@end

