/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSData, NSDate, NSDictionary, NSString;

// Not exported
@interface SFInternalAdvertisement : NSObject
{
    _Bool _domain;
    NSString *_advertisementString;
    NSDate *_timestamp;
    NSDictionary *_options;
    NSData *_payload;
}

@property(retain) NSData *payload; // @synthesize payload=_payload;
@property(copy) NSDictionary *options; // @synthesize options=_options;
@property(retain) NSDate *timestamp; // @synthesize timestamp=_timestamp;
@property(getter=isDomain) _Bool domain; // @synthesize domain=_domain;
@property(copy) NSString *advertisementString; // @synthesize advertisementString=_advertisementString;
- (void)dealloc;
- (id)initWithAdvertisementString:(id)arg1 isDomain:(_Bool)arg2 timestamp:(id)arg3 options:(id)arg4 payload:(id)arg5;

@end

