/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <Foundation/NSFileReactorProxy.h>

// Not exported
@interface NSFileProviderProxy : NSFileReactorProxy
{
}

- (void)observePresentationChangeOfKind:(id)arg1 withPresenter:(id)arg2 url:(id)arg3 newURL:(id)arg4;
- (void)provideLogicalURLForURL:(id)arg1 completionHandler:(id)arg2;
- (void)providePhysicalURLForURL:(id)arg1 completionHandler:(id)arg2;
- (id)provideItemAtURL:(SEL)arg1 forAccessClaim:(id)arg2 completionHandler:(id)arg3;
- (void)forwardUsingMessageSender:(id)arg1;
- (void)setItemLocation:(id)arg1;

@end

