/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface DCIMSlalomUtilities : NSObject
{
}

+ (_Bool)writeRegions:(id)arg1 toPath:(id)arg2;
+ (id)regionsFromPlist:(id)arg1;
+ (id)plistFromRegions:(id)arg1;

@end

