/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iWorkImport/TSWPPageRep.h>

#import "TSDMasterDrawableDelegate-Protocol.h"

@class CALayer, TPMarginAdjustRep;

// Not exported
@interface TPPageRep : TSWPPageRep <TSDMasterDrawableDelegate>
{
    CALayer *_separatorLayer;
}

- (id)bodyReps;
- (_Bool)masksToBounds;
- (void)drawInLayerContext:(struct CGContext *)arg1;
- (void)drawInContext:(struct CGContext *)arg1;
- (void)setNeedsDisplayInRect:(struct CGRect)arg1;
- (void)setNeedsDisplay;
- (_Bool)directlyManagesLayerContent;
- (id)layerClass;
- (void)p_updateBorderLayers;
- (id)p_topmostEditingInfo;
- (void)p_updateSeparatorLayer;
- (_Bool)p_pageRequiresSeparator;
- (_Bool)childRepIsMasterDrawable:(id)arg1;
- (_Bool)childRepIsOnDocSetupCanvas:(id)arg1;
- (id)childRepsForHitTesting;
- (id)visibleChildLayouts;
- (void)p_didUpdateLayer:(id)arg1;
- (void)didUpdateLayer:(id)arg1;
- (void)p_updateLayoutBordersVisibility;
- (void)addAdditionalChildLayersToArray:(id)arg1;
- (void)viewScaleDidChange;
- (void)willBeRemoved;
- (void)showHUDForWPRep:(id)arg1 withFlags:(unsigned long long)arg2;
- (id)hitMasterRep:(struct CGPoint)arg1;
@property(readonly, nonatomic) TPMarginAdjustRep *marginAdjustRep;
- (id)p_hitRep:(struct CGPoint)arg1 passingTest:(id)arg2;
- (int)p_hitHeaderFooterFragment:(int)arg1 atPoint:(struct CGPoint)arg2;
- (id)hitRep:(struct CGPoint)arg1 passingTest:(id)arg2;
- (_Bool)p_headerFooterIsVisibleAndInteractive:(int)arg1;
- (void)dealloc;

@end

