/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iWorkImport/TSPSaveOperationState.h>

@class NSData, NSString, NSURL, NSUUID, SFUCryptoKey, TSPDocumentProperties, TSPDocumentRevision, TSPObject;

// Not exported
@interface TSPDocumentSaveOperationState : TSPSaveOperationState
{
    _Bool _shouldLeavePendingEndSave;
    NSURL *_URL;
    NSURL *_relativeURLForExternalData;
    TSPDocumentProperties *_documentProperties;
    TSPDocumentRevision *_documentRevision;
    unsigned long long _saveToken;
    TSPObject *_documentObject;
    TSPObject *_supportObject;
    NSURL *_originalSupportURL;
    SFUCryptoKey *_encryptionKey;
    NSData *_passwordVerifier;
    NSString *_documentPasswordHint;
    id <TSPPackageWriter> _documentPackageWriter;
    id <TSPPackageWriter> _supportPackageWriter;
    NSUUID *_documentUUID;
}

@property(nonatomic) _Bool shouldLeavePendingEndSave; // @synthesize shouldLeavePendingEndSave=_shouldLeavePendingEndSave;
@property(copy, nonatomic) NSUUID *documentUUID; // @synthesize documentUUID=_documentUUID;
@property(retain, nonatomic) id <TSPPackageWriter> supportPackageWriter; // @synthesize supportPackageWriter=_supportPackageWriter;
@property(retain, nonatomic) id <TSPPackageWriter> documentPackageWriter; // @synthesize documentPackageWriter=_documentPackageWriter;
@property(copy, nonatomic) NSString *documentPasswordHint; // @synthesize documentPasswordHint=_documentPasswordHint;
@property(retain, nonatomic) NSData *passwordVerifier; // @synthesize passwordVerifier=_passwordVerifier;
@property(retain, nonatomic) SFUCryptoKey *encryptionKey; // @synthesize encryptionKey=_encryptionKey;
@property(copy, nonatomic) NSURL *originalSupportURL; // @synthesize originalSupportURL=_originalSupportURL;
@property(retain, nonatomic) TSPObject *supportObject; // @synthesize supportObject=_supportObject;
@property(retain, nonatomic) TSPObject *documentObject; // @synthesize documentObject=_documentObject;
@property(nonatomic) unsigned long long saveToken; // @synthesize saveToken=_saveToken;
@property(retain, nonatomic) TSPDocumentRevision *documentRevision; // @synthesize documentRevision=_documentRevision;
@property(retain, nonatomic) TSPDocumentProperties *documentProperties; // @synthesize documentProperties=_documentProperties;
@property(copy, nonatomic) NSURL *relativeURLForExternalData; // @synthesize relativeURLForExternalData=_relativeURLForExternalData;
@property(readonly, nonatomic) NSURL *URL; // @synthesize URL=_URL;
- (void).cxx_destruct;
- (id)initWithURL:(id)arg1 updateType:(unsigned long long)arg2;
- (id)init;

@end

