/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iWorkImport/TSPFileDataStorage.h>

@class NSData, NSURL, TSPObjectContext;

// Not exported
@interface TSPExternalReferenceDataStorage : TSPFileDataStorage
{
    NSURL *_URL;
    NSData *_bookmarkData;
    TSPObjectContext *_context;
}

- (void).cxx_destruct;
@property(readonly, nonatomic, getter=isReadable) _Bool readable;
- (void)performReadWithAccessor:(id)arg1;
- (id)bookmarkDataForArchiver:(id)arg1;
- (void)archiveInfoMessage:(struct DataInfo *)arg1 archiver:(id)arg2;
- (id)storageForDataCopyFromOtherContext;
- (id)initWithBookmarkData:(id)arg1 context:(id)arg2;
- (id)initWithURL:(id)arg1;

@end

