/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iWorkImport/TSTEphemeralCellMap.h>

#import "TSTSearchableCellMap-Protocol.h"

@class NSMutableDictionary;

// Not exported
@interface TSTEphemeralSearchableCellMap : TSTEphemeralCellMap <TSTSearchableCellMap>
{
    NSMutableDictionary *mCellIDToIndexMap;
}

- (id)findCellFromCellMap:(CDStruct_0441cfb5)arg1;
- (void)popLastCell;
- (void)addCell:(id)arg1 andCellID:(CDStruct_0441cfb5)arg2;
- (void)dealloc;
- (id)initWithCapacity:(unsigned long long)arg1;

// Remaining properties
@property(nonatomic) _Bool appliesToHidden;

@end

