/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

// Not exported
@interface TSTLocalAccumulator : NSObject
{
    CDStruct_0441cfb5 _idOfFirstOccurence;
    unsigned long long _count;
}

@property unsigned long long count; // @synthesize count=_count;
@property CDStruct_0441cfb5 idOfFirstOccurence; // @synthesize idOfFirstOccurence=_idOfFirstOccurence;
- (id).cxx_construct;
- (id)description;

@end

