/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iWorkImport/TSWPTextCommand.h>

@class NSString, TSKAddedToDocumentContext;

// Not exported
@interface TSWPReplaceTextCommand : TSWPTextCommand
{
    id _text;
    TSKAddedToDocumentContext *_dolcContext;
    _Bool _coalesceable;
    _Bool _coalescingText;
    _Bool _withPasteRules;
    _Bool _deletingBackward;
    _Bool _doNotTrackDeletion;
    _Bool _crossDocumentPaste;
    NSString *_language;
    NSString *_dictationAndAutocorrection;
}

@property(retain, nonatomic) NSString *dictationAndAutocorrection; // @synthesize dictationAndAutocorrection=_dictationAndAutocorrection;
@property(retain, nonatomic) NSString *language; // @synthesize language=_language;
@property(retain, nonatomic) TSKAddedToDocumentContext *dolcContext; // @synthesize dolcContext=_dolcContext;
- (struct _NSRange)p_selectionRangeAfterReplacingRange:(struct _NSRange)arg1 changedRange:(struct _NSRange)arg2;
- (void)coalesceWithCommand:(id)arg1;
- (_Bool)canCoalesceWithCommand:(id)arg1;
- (_Bool)coalescingText;
- (_Bool)isCoalesceable;
- (int)persistenceKind;
- (void)redo;
- (void)undo;
- (void)doCommit;
- (id)actionString;
- (void)setUpdateSelection:(_Bool)arg1;
- (void)dealloc;
- (id)initWithStorage:(id)arg1 selection:(id)arg2 insertText:(id)arg3 coalesceable:(_Bool)arg4 coalescingText:(_Bool)arg5 updateSelection:(_Bool)arg6 deletingBackward:(_Bool)arg7;
- (id)initWithStorage:(id)arg1 selection:(id)arg2 insertText:(id)arg3 coalesceable:(_Bool)arg4 coalescingText:(_Bool)arg5 updateSelection:(_Bool)arg6 deletingBackward:(_Bool)arg7 undoSelection:(id)arg8;
- (id)initWithStorage:(id)arg1 range:(struct _NSRange)arg2 insertText:(id)arg3 coalesceable:(_Bool)arg4 coalescingText:(_Bool)arg5;
- (id)initWithStorage:(id)arg1 selection:(id)arg2 insertText:(id)arg3 updateSelection:(_Bool)arg4;
- (id)initWithStorage:(id)arg1 selection:(id)arg2 insertText:(id)arg3 crossDocumentPaste:(_Bool)arg4;
- (id)initWithStorage:(id)arg1 selection:(id)arg2 insertText:(id)arg3;
- (id)initWithStorage:(id)arg1 range:(struct _NSRange)arg2 insertText:(id)arg3;
- (id)initWithStorage:(id)arg1 range:(struct _NSRange)arg2 insertStorage:(id)arg3 withPasteRules:(_Bool)arg4 dolcContext:(id)arg5;

@end

