/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <PhotoEditSupport/BLBrushStroke.h>

@interface BLRepairBrushStroke : BLBrushStroke
{
    struct CGPoint _repairTextureOffset;
}

@property(nonatomic) struct CGPoint repairTextureOffset; // @synthesize repairTextureOffset=_repairTextureOffset;
- (id)keysToEncode;

@end

