/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSDictionary.h"

@interface NSDictionary (Additions)
- (id)dictionaryByRemovingValuesForKey:(id)arg1;
- (id)dictionaryBySwappingValuesWithDictionary:(id)arg1;
- (id)objectForIndex:(int)arg1;
- (id)nonRetainedObjectForKey:(id)arg1;
- (id)objectOrNullForKey:(id)arg1;
- (id)objectForKey:(id)arg1 defaultValue:(id)arg2;
- (struct CGAffineTransform)affineTransformForKey:(id)arg1;
- (struct CGPoint)pointFromStringForKey:(id)arg1 defaultValue:(struct CGPoint)arg2;
- (struct CGPoint)pointFromStringForKey:(id)arg1;
- (struct CGRect)rectFromStringForKey:(id)arg1 defaultValue:(struct CGRect)arg2;
- (struct CGRect)rectFromStringForKey:(id)arg1;
- (struct CGRect)rectForKey:(id)arg1 defaultValue:(struct CGRect)arg2;
- (struct CGRect)rectForKey:(id)arg1;
- (double)doubleForKey:(id)arg1 defaultValue:(double)arg2;
- (double)doubleForKey:(id)arg1;
- (float)floatForKey:(id)arg1 defaultValue:(float)arg2;
- (float)floatForKey:(id)arg1;
- (long long)integerForKey:(id)arg1 defaultValue:(long long)arg2;
- (int)intForKey:(id)arg1 defaultValue:(int)arg2;
- (long long)integerForKey:(id)arg1;
- (int)intForKey:(id)arg1;
- (_Bool)boolForKey:(id)arg1 defaultValue:(_Bool)arg2;
- (_Bool)boolForKey:(id)arg1;
@end

