/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UITableViewCell.h"

@class NSArray, NSMutableArray;

@interface MCDetailsCell : UITableViewCell
{
    NSArray *_details;
    NSMutableArray *_labels;
}

@property(retain, nonatomic) NSMutableArray *labels; // @synthesize labels=_labels;
@property(retain, nonatomic) NSArray *details; // @synthesize details=_details;
- (void).cxx_destruct;
- (void)_setupConstraints:(id)arg1;
- (void)_setupGroupViewInnerConstraints:(id)arg1;
- (void)_createViewWithDetails:(id)arg1;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

