/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "SBCDomainSyncServiceProtocol_Internal-Protocol.h"
#import "SBCPlaybackPositionServiceProtocol-Protocol.h"

@protocol SBCPlaybackPositionServiceProtocol_Internal <SBCPlaybackPositionServiceProtocol, SBCDomainSyncServiceProtocol_Internal>
- (oneway void)setClientConfiguration:(id)arg1;
@end

