/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "IDSDaemonListenerProtocol-Protocol.h"

@class CUTWeakReference, NSArray, NSData, NSDictionary, NSInputStream, NSObject<OS_dispatch_queue>, NSOutputStream, NSString, NSUUID;

@interface _IDSDevice : NSObject <IDSDaemonListenerProtocol>
{
    NSDictionary *_info;
    NSString *_serviceToken;
    CUTWeakReference *_account;
    int _socket;
    int _nearbyToken;
    _Bool _nearby;
    id _openSocketCompletionHandler;
    NSObject<OS_dispatch_queue> *_openSocketCompletionHandlerQueue;
    NSString *_openSocketCompletionHandlerID;
    NSInputStream *_inputStreamForSocket;
    NSOutputStream *_outputStreamForSocket;
}

- (void)closeSocketForDomain:(id)arg1;
- (void)xpcObject:(id)arg1 objectContext:(id)arg2;
- (void)closeStreamPairWithInputStream:(id)arg1 outputStream:(id)arg2;
- (void)setStreamPairWithInputStream:(id)arg1 outputStream:(id)arg2;
- (void)closeSocket:(int)arg1;
- (void)openSocketWithOptions:(id)arg1 completionHandler:(id)arg2 onQueue:(void)arg3;
- (int)socketForDomain:(id)arg1;
- (void)_setAccount:(id)arg1;
- (void)_nearbyStateChanged;
- (void)_addIdentity:(id)arg1;
@property(readonly, retain, nonatomic) NSArray *_identities;
@property(readonly, retain, nonatomic) NSData *pushToken;
@property(readonly, retain, nonatomic) NSString *enclosureColor;
@property(readonly, retain, nonatomic) NSString *deviceColor;
@property(readonly, nonatomic) _Bool supportsMMSRelay;
@property(readonly, nonatomic) _Bool supportsSMSRelay;
- (void)_updateNSUUID:(id)arg1;
@property(retain, nonatomic, setter=setNSUUID:) NSUUID *nsuuid;
@property(readonly, nonatomic) _Bool isDefaultLocalDevice;
@property(readonly, nonatomic) _Bool isDefaultPairedDevice;
@property(readonly, nonatomic) _Bool locallyPresent;
@property(readonly, nonatomic, getter=isNearby) _Bool nearby;
- (id)description;
@property(readonly, retain, nonatomic) NSString *service;
@property(readonly, retain, nonatomic) NSString *name;
@property(readonly, retain, nonatomic) NSString *modelIdentifier;
@property(readonly, retain, nonatomic) NSString *uniqueID;
- (void)_connect;
- (void)dealloc;
- (id)initWithDictionary:(id)arg1;

@end

