/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <Radio/RadioRequest.h>

@class SSURLConnectionRequest;

@interface RadioGetWishListRequest : RadioRequest
{
    SSURLConnectionRequest *_request;
    unsigned long long _maxNumberOfTracks;
}

@property(nonatomic) unsigned long long maxNumberOfTracks; // @synthesize maxNumberOfTracks=_maxNumberOfTracks;
- (void).cxx_destruct;
- (void)startWithCompletionHandler:(id)arg1;
- (void)cancel;
- (id)init;

@end

