/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <Radio/RadioPlaybackContext.h>

@class NSArray;

@interface RadioMutablePlaybackContext : RadioPlaybackContext
{
}

@property(copy, nonatomic) NSArray *trackPlaybackDescriptorQueue;
@property(nonatomic) long long numberOfSkipsUsed;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

