/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <Radio/RadioHistoryItem.h>

@class NSDate, NSString, RadioTrack;

@interface RadioMutableHistoryItem : RadioHistoryItem
{
}

@property(nonatomic) long long type;
@property(retain, nonatomic) RadioTrack *track;
@property(copy, nonatomic) NSString *externalIdentifier;
@property(retain, nonatomic) NSDate *datePlayed;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

