/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCopying-Protocol.h"
#import "NSMutableCopying-Protocol.h"

@class RadioArtworkCollection, RadioSeedMetadata;

@interface RadioLikeBanItem : NSObject <NSCopying, NSMutableCopying>
{
    long long _albumID;
    RadioArtworkCollection *_artworkCollection;
    _Bool _isSeed;
    RadioSeedMetadata *_seedMetadata;
    long long _storeID;
    long long _type;
}

@property(readonly, nonatomic) long long type; // @synthesize type=_type;
@property(readonly, nonatomic) long long storeID; // @synthesize storeID=_storeID;
@property(readonly, copy, nonatomic) RadioSeedMetadata *seedMetadata; // @synthesize seedMetadata=_seedMetadata;
@property(readonly, nonatomic) _Bool isSeed; // @synthesize isSeed=_isSeed;
@property(readonly, nonatomic) RadioArtworkCollection *artworkCollection; // @synthesize artworkCollection=_artworkCollection;
@property(readonly, nonatomic) long long albumID; // @synthesize albumID=_albumID;
- (void).cxx_destruct;
- (id)mutableCopyWithZone:(struct _NSZone *)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (id)initWithItemDictionary:(id)arg1;
- (id)init;

@end

