/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "SSURLConnectionResponse.h"

@class NSData;

@interface SSURLConnectionResponse (RadioAdditions)
- (void)radio_mescalVerifyDataWithCompletionHandler:(id)arg1;
@property(readonly, nonatomic) NSData *radio_decompressedBodyData;
@end

