/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "BBBehaviorOverrideEffectivePeriod-Protocol.h"

@class NSDate, NSUUID;

@interface BBBehaviorOverrideFixedEffectivePeriod : NSObject <BBBehaviorOverrideEffectivePeriod>
{
    NSDate *_startDate;
    double _effectiveInterval;
    NSUUID *_identifier;
}

+ (_Bool)supportsSecureCoding;
@property(copy, nonatomic) NSUUID *identifier; // @synthesize identifier=_identifier;
@property(nonatomic) double effectiveInterval; // @synthesize effectiveInterval=_effectiveInterval;
@property(copy, nonatomic) NSDate *startDate; // @synthesize startDate=_startDate;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)nextTransitionDateAfterDate:(id)arg1;
- (_Bool)containsDate:(id)arg1;
- (void)dealloc;
- (id)initWithStartDate:(id)arg1 effectiveInterval:(double)arg2 identifier:(id)arg3;

@end

