/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSCopying-Protocol.h"
#import "NSObject-Protocol.h"
#import "NSSecureCoding-Protocol.h"

@protocol BBBehaviorOverrideEffectivePeriod <NSCopying, NSSecureCoding, NSObject>
- (id)identifier;
- (id)nextTransitionDateAfterDate:(id)arg1;
- (_Bool)containsDate:(id)arg1;
@end

