/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSHashTable, NSManagedObjectContext, NSMutableDictionary, NSMutableSet, NSObject<OS_dispatch_queue>, PLPhotoLibrary;

@interface PHPhotoLibrary : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;
    PLPhotoLibrary *_photoLibrary;
    NSManagedObjectContext *_managedObjectContext;
    NSObject<OS_dispatch_queue> *_transactionQueue;
    NSMutableSet *_inserts;
    NSMutableSet *_updates;
    NSMutableSet *_deletes;
    NSMutableDictionary *_changeRequests;
    NSHashTable *_fetchResults;
    NSHashTable *_observers;
    NSMutableDictionary *_changeNotificationInfo;
}

+ (id)uniquedOIDs:(id)arg1;
+ (id)uniquedOID:(id)arg1;
+ (id)_effectiveRootEntity:(id)arg1;
+ (Class)PHObjectClassForOID:(id)arg1;
+ (Class)PHObjectClassForEntityName:(id)arg1;
+ (Class)classForFetchType:(id)arg1;
+ (id)sharedPhotoLibrary;
@property(retain, nonatomic) NSMutableDictionary *changeNotificationInfo; // @synthesize changeNotificationInfo=_changeNotificationInfo;
@property(retain, nonatomic) NSHashTable *observers; // @synthesize observers=_observers;
@property(retain, nonatomic) NSHashTable *fetchResults; // @synthesize fetchResults=_fetchResults;
@property(retain, nonatomic) NSMutableDictionary *changeRequests; // @synthesize changeRequests=_changeRequests;
@property(retain, nonatomic) NSMutableSet *deletes; // @synthesize deletes=_deletes;
@property(retain, nonatomic) NSMutableSet *updates; // @synthesize updates=_updates;
@property(retain, nonatomic) NSMutableSet *inserts; // @synthesize inserts=_inserts;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *transactionQueue; // @synthesize transactionQueue=_transactionQueue;
@property(retain, nonatomic) NSManagedObjectContext *managedObjectContext; // @synthesize managedObjectContext=_managedObjectContext;
@property(retain, nonatomic) PLPhotoLibrary *photoLibrary; // @synthesize photoLibrary=_photoLibrary;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
- (void).cxx_destruct;
- (void)handleMergeNotification:(id)arg1;
- (id)transactionPLPhotoLibrary;
- (id)transactionContext;
- (id)fetchUpdatedObject:(id)arg1;
- (id)fetchPHObjectsForUUIDs:(id)arg1 entityName:(id)arg2;
- (id)fetchPHObjectsForOIDs:(id)arg1 propertyHint:(unsigned long long)arg2 includeTrash:(_Bool)arg3;
- (id)fetchPHObjectsForOIDs:(id)arg1;
- (id)queryForType:(id)arg1 withIdentifiers:(id)arg2 local:(_Bool)arg3;
- (void)setChangeRequest:(id)arg1 forUUID:(id)arg2;
- (id)changeRequestForUUID:(id)arg1;
- (void)recordDeleteRequest:(id)arg1;
- (void)recordUpdateRequest:(id)arg1;
- (void)recordInsertRequest:(id)arg1;
- (void)assertTransaction;
- (_Bool)isApplyingRequestedChanges;
- (_Bool)performChangesAndWait:(id)arg1 error:(void)arg2;
- (void)performChanges:(id)arg1 completionHandler:(void)arg2;
- (void)_commitTransaction:(id)arg1;
- (void)_beginTransaction;
- (void)unregisterChangeObserver:(id)arg1;
- (void)registerChangeObserver:(id)arg1;
- (void)unregisterFetchResult:(id)arg1;
- (void)registerFetchResult:(id)arg1;
- (id)initSharedLibrary;
- (id)init;
- (id)pl_syncProgressAlbums;

@end

