/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class TUCall;

@interface TUAVConferenceConnection : NSObject
{
    int _socketDescriptor;
    TUCall *_call;
    id _didStartHandler;
    id _didStopHandler;
}

+ (id)conferenceConnectionWithCall:(id)arg1;
@property(copy, nonatomic) id didStopHandler; // @synthesize didStopHandler=_didStopHandler;
@property(copy, nonatomic) id didStartHandler; // @synthesize didStartHandler=_didStartHandler;
@property(retain, nonatomic) TUCall *call; // @synthesize call=_call;
@property(readonly, nonatomic) int socketDescriptor; // @synthesize socketDescriptor=_socketDescriptor;
@property(nonatomic, getter=isMuted) _Bool muted;
- (id)description;
- (void)dealloc;

@end

