/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCopying-Protocol.h"
#import "NSSecureCoding-Protocol.h"

@class NSArray;

@interface TILexicon : NSObject <NSCopying, NSSecureCoding>
{
    NSArray *_entries;
}

+ (void)requestLexiconFromBundlePath:(id)arg1 completionHandler:(id)arg2;
+ (id)lexiconWithEntries:(id)arg1;
+ (_Bool)supportsSecureCoding;
@property(readonly, nonatomic) NSArray *entries; // @synthesize entries=_entries;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;

@end

