/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface AXSimpleRuntimeManager : NSObject
{
    _Bool _systemWideServer;
    id _parameterizedAttributeCallback;
    id _attributeCallback;
    id _setAttributeCallback;
    id _performActionCallback;
    id _clientObserverCallback;
    id _hitTestCallback;
    id _applicationElementCallback;
}

+ (id)sharedManager;
@property(copy, nonatomic) id applicationElementCallback; // @synthesize applicationElementCallback=_applicationElementCallback;
@property(copy, nonatomic) id hitTestCallback; // @synthesize hitTestCallback=_hitTestCallback;
@property(copy, nonatomic) id clientObserverCallback; // @synthesize clientObserverCallback=_clientObserverCallback;
@property(copy, nonatomic) id performActionCallback; // @synthesize performActionCallback=_performActionCallback;
@property(copy, nonatomic) id setAttributeCallback; // @synthesize setAttributeCallback=_setAttributeCallback;
@property(copy, nonatomic) id attributeCallback; // @synthesize attributeCallback=_attributeCallback;
@property(copy, nonatomic) id parameterizedAttributeCallback; // @synthesize parameterizedAttributeCallback=_parameterizedAttributeCallback;
@property(nonatomic) _Bool systemWideServer; // @synthesize systemWideServer=_systemWideServer;
- (void)start;

@end

