/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCopying-Protocol.h"
#import "NSSecureCoding-Protocol.h"

@class NSString;

@interface SGSimpleNamedEmailAddress : NSObject <NSCopying, NSSecureCoding>
{
    NSString *_emailAddress;
    NSString *_name;
}

+ (id)serializeAll:(id)arg1;
+ (id)namedEmailAddressesWithFieldValues:(id)arg1;
+ (id)namedEmailAddressWithFieldValue:(id)arg1;
+ (_Bool)supportsSecureCoding;
@property(readonly, nonatomic) NSString *name; // @synthesize name=_name;
@property(readonly, nonatomic) NSString *emailAddress; // @synthesize emailAddress=_emailAddress;
- (void).cxx_destruct;
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqualToNamedEmailAddress:(id)arg1;
- (_Bool)isEqual:(id)arg1;
- (id)serialized;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithName:(id)arg1 emailAddress:(id)arg2;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

