/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIWKAutocorrectionContext.h"

// Not exported
@interface WKAutocorrectionContext : UIWKAutocorrectionContext
{
}

+ (id)autocorrectionContextWithData:(id)arg1 markedText:(id)arg2 selectedText:(id)arg3 afterText:(id)arg4 selectedRangeInMarkedText:(struct _NSRange)arg5;
- (void)dealloc;

@end

