/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIView.h"

#import "WKWebViewContentProvider-Protocol.h"

@class NSData, NSString, UIScrollView;

// Not exported
@interface WKPDFView : UIView <WKWebViewContentProvider>
{
    struct RetainPtr<UIPDFDocument> _pdfDocument;
    struct RetainPtr<NSString> _suggestedFilename;
    struct Vector<PDFPageInfo, 0, WTF::CrashOnOverflow> _pages;
    struct CGRect _documentFrame;
    struct CGSize _minimumSize;
    UIScrollView *_scrollView;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)_computePageAndDocumentFrames;
- (void)_revalidateViews;
- (void)scrollViewDidScroll:(id)arg1;
- (void)web_setScrollView:(id)arg1;
- (void)web_setMinimumSize:(struct CGSize)arg1;
- (void)web_setContentProviderData:(id)arg1 suggestedFilename:(id)arg2;
@property(readonly, nonatomic) NSString *suggestedFilename;
@property(readonly, nonatomic) NSData *documentData;
- (id)initWithFrame:(struct CGRect)arg1;

@end

