/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import <WebKit/WKObject-Protocol.h>

@class WKBrowsingContextHandle, WKDOMDocument, WKDOMRange, WKWebProcessPlugInFrame, WKWebProcessPlugInPageGroup, _WKRemoteObjectRegistry;

@interface WKWebProcessPlugInBrowserContextController : NSObject <WKObject>
{
    struct ObjectStorage<WebKit::WebPage> _page;
    struct WeakObjCPtr<id<WKWebProcessPlugInLoadDelegate>> _loadDelegate;
    struct WeakObjCPtr<id<WKWebProcessPlugInFormDelegatePrivate>> _formDelegate;
    struct RetainPtr<_WKRemoteObjectRegistry> _remoteObjectRegistry;
}

+ (id)lookUpBrowsingContextFromHandle:(id)arg1;
- (id).cxx_construct;
- (void).cxx_destruct;
@property(readonly) struct Object *_apiObject;
@property(readonly) WKWebProcessPlugInPageGroup *pageGroup;
@property(readonly) WKWebProcessPlugInFrame *mainFrame;
@property(readonly) WKDOMRange *selectedRange;
@property(readonly) WKDOMDocument *mainFrameDocument;
- (void)dealloc;
@property __weak id <WKWebProcessPlugInLoadDelegate> loadDelegate;
@property(nonatomic, setter=_setDefersLoading:) _Bool _defersLoading;
@property(setter=_setFormDelegate:) __weak id <WKWebProcessPlugInFormDelegatePrivate> _formDelegate;
@property(readonly, nonatomic) _WKRemoteObjectRegistry *_remoteObjectRegistry;
@property(readonly, nonatomic) WKBrowsingContextHandle *handle;
@property(readonly, nonatomic) struct OpaqueWKBundlePage *_bundlePageRef;

@end

