/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <MusicUI/MusicActionTableViewCell.h>

@interface MusicAddAllTableViewCell : MusicActionTableViewCell
{
}

- (void)setSectionLocation:(int)arg1 animated:(_Bool)arg2;
- (void)setDisplayAsDisabled:(_Bool)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

