/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <MusicUI/MusicTableViewController.h>

#import "MusicPickerOverlayDelegate-Protocol.h"
#import "UITextFieldDelegate-Protocol.h"

@class NSCache, UIAlertView, UIImage, UITextField;

@interface MusicPlaylistsViewController : MusicTableViewController <MusicPickerOverlayDelegate, UITextFieldDelegate>
{
    UIImage *_initialPlaceholderImage;
    UITextField *_newPlaylistAlertTextField;
    id _newPlaylistAlertTextFieldChangeObserver;
    UIAlertView *_newPlaylistAlertView;
    NSCache *_playlistMetadataCache;
}

@property(retain, nonatomic) NSCache *playlistMetadataCache; // @synthesize playlistMetadataCache=_playlistMetadataCache;
- (void).cxx_destruct;
- (id)_viewControllerForSelectedMediaEntity:(id)arg1 containerItemType:(long long)arg2;
- (void)_updateCloudPlaylist:(id)arg1;
- (id)_playlistTitle;
- (void)createGeniusPlaylistAction;
- (void)addPlaylistAction;
- (void)switchToShortcutIdentifier:(id)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (_Bool)_isSaveButtonEnabled;
- (void)_updateSaveButtonEnabledState;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)alertView:(id)arg1 didDismissWithButtonIndex:(long long)arg2;
- (void)pickerOverlayDidFinish:(id)arg1;
- (void)pickerOverlayRequestsFinish:(id)arg1;
- (_Bool)MPH_supportsCoverFlow;
- (_Bool)music_hasContent;
- (void)reloadData;
- (_Bool)music_handleUserActivityContext:(id)arg1 containerItem:(id)arg2;
- (_Bool)music_appendCurrentUserActivityContainerItems:(id)arg1 previousViewController:(id)arg2 nextViewController:(id)arg3;
- (id)initWithDataSource:(id)arg1;

@end

