/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <MusicUI/MusicStandardMediaTableViewCellContentView.h>

@interface MusicSongListTableViewCellContentView : MusicStandardMediaTableViewCellContentView
{
}

+ (id)_detailRegularTextAttributes;
+ (void)contentSizeCategoryDidChange;
+ (id)titleRegularTextAttributes;
+ (id)titleEmphasizedTextAttributes;
+ (id)subtitleRegularTextAttributes;
+ (id)detailEmphasizedTextAttributes;
+ (id)detailRegularTextAttributes;
+ (id)detailRegularGrayTextAttributes;
+ (struct CGSize)artworkSize;
- (id)subtitleDetailTextSeparatorString;
- (id)currentSubtitleAttributedText;
- (void)reloadContent;
- (void)setDisplayAsDisabled:(_Bool)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;

@end

