/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIViewController.h"

#import "MPTermsViewControllerDelegate-Protocol.h"

@class HSCloudClient, MPUContentSizeLayoutConstraint, NSLayoutConstraint, SKUICircleProgressIndicator, UIButton, UIImageView, UILabel, UITextView;

@interface MusicGeniusOptInViewController : UIViewController <MPTermsViewControllerDelegate>
{
    HSCloudClient *_cloudClient;
    _Bool _hasGeniusDownloadCompletionBlock;
    long long _acceptedTermsVersion;
    UIImageView *_geniusImageView;
    UILabel *_aboutGeniusLabel;
    UIButton *_geniusOptInButton;
    SKUICircleProgressIndicator *_indeterminateProgressIndicatorView;
    UITextView *_disclosureTextView;
    MPUContentSizeLayoutConstraint *_updatingAboutGeniusLabelBaselineContraint;
    NSLayoutConstraint *_updatingAboutGeniusLabelWidthContraint;
    MPUContentSizeLayoutConstraint *_updatingGeniusOptInButtonBaselineContraint;
    NSLayoutConstraint *_updatingDisclosureTextViewBottomContraint;
}

- (void).cxx_destruct;
- (void)_showTermsViewControllerForTerms:(id)arg1;
- (void)_showErrorAlert;
- (void)_updateGeniusState;
- (id)_completionBlock;
- (void)_ensureCompletionHandlerIsAttached;
- (void)_enableGenius;
- (id)_createSpacerView;
- (void)termsViewController:(id)arg1 didAcceptTerms:(_Bool)arg2;
- (void)_doneButtonPressed:(id)arg1;
- (void)_geniusOptInButtonAction:(id)arg1;
- (void)updateViewConstraints;
- (void)didRotateFromInterfaceOrientation:(long long)arg1;
- (void)viewDidLoad;
- (id)init;

@end

