/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface WLOResultTimer : NSObject
{
}

+ (double)EndTimerForKey:(id)arg1;
+ (id)StartTimerForKey:(id)arg1;
+ (double)_HandleTimerForKey:(id)arg1 isStart:(_Bool)arg2;

@end

