/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class AVAsset;

@interface MPStoreAsset : NSObject
{
    unsigned long long _storeAssetType;
    AVAsset *_asset;
}

+ (id)assetForContext:(id)arg1 allowCloudDialogue:(_Bool)arg2;
+ (void)setShouldAlwaysAirPlayFromCloud:(_Bool)arg1;
@property(retain, nonatomic) AVAsset *asset; // @synthesize asset=_asset;
@property(nonatomic) unsigned long long storeAssetType; // @synthesize storeAssetType=_storeAssetType;
- (void).cxx_destruct;

@end

