/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UINavigationController.h"

@class UIViewController;

@interface MCDNowPlayingNavigationController : UINavigationController
{
    UIViewController *_fakeViewController;
}

@property(readonly, nonatomic) UIViewController *previousViewController; // @synthesize previousViewController=_fakeViewController;
- (void).cxx_destruct;
- (_Bool)navigationBar:(id)arg1 shouldPopItem:(id)arg2;
- (id)initWithRootViewController:(id)arg1;

@end

