/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "CUIKSingleDayTimelineViewItem-Protocol.h"

@class EKCalendarDate, EKDayOccurrenceView, EKEvent, NSDate;

@interface EKDayViewContentItem : NSObject <CUIKSingleDayTimelineViewItem>
{
    _Bool _pinned;
    _Bool _toBottom;
    struct CGRect _unPinnedViewFrame;
    unsigned long long _eventIndex;
    EKDayOccurrenceView *_view;
    EKCalendarDate *_startDate;
    EKCalendarDate *_endDate;
    double _travelTime;
}

+ (double)barToBarHorizontalDistanceIncludingBarWidth;
@property(nonatomic) double travelTime; // @synthesize travelTime=_travelTime;
@property(copy, nonatomic) EKCalendarDate *endDate; // @synthesize endDate=_endDate;
@property(copy, nonatomic) EKCalendarDate *startDate; // @synthesize startDate=_startDate;
@property(retain, nonatomic) EKDayOccurrenceView *view; // @synthesize view=_view;
@property(readonly, nonatomic) unsigned long long eventIndex; // @synthesize eventIndex=_eventIndex;
- (void).cxx_destruct;
- (void)setVisibleHeight:(double)arg1;
@property(readonly) _Bool visibleHeightLocked;
@property struct CGRect unPinnedViewFrame;
- (void)setStagedFrame:(struct CGRect)arg1;
- (struct CGRect)stagedFrame;
@property(readonly, nonatomic) _Bool hideTravelTime;
@property(readonly, nonatomic) EKEvent *event;
@property(readonly, nonatomic) double viewMaxNaturalTextHeight;
@property(readonly, nonatomic) double enoughHeightForOneLine;
@property(readonly, nonatomic) NSDate *end;
@property(readonly, nonatomic) NSDate *start;
@property(readonly, nonatomic) NSDate *startWithTravelTime;
- (_Bool)isPinned;
- (void)setPinned:(_Bool)arg1 toBottom:(_Bool)arg2;
@property(readonly, copy, nonatomic) EKCalendarDate *startDateIncludingTravelTime;
- (id)description;
- (_Bool)isEqual:(id)arg1;
- (id)initWithEventIndex:(unsigned long long)arg1;

@end

