/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UITableViewController.h"

#import "EKEditItemViewControllerDelegate-Protocol.h"
#import "EKEditItemViewControllerProtocol-Protocol.h"
#import "MFMailComposeViewControllerDelegate-Protocol.h"
#import "MFMessageComposeViewControllerDelegate-Protocol.h"
#import "UIActionSheetDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class EKEvent, EKRequestAvailabilityOperation, EKUIEventInviteesView, NSArray, NSDate, NSDictionary, NSMutableArray, NSMutableDictionary, NSNumber, NSObject<OS_dispatch_queue>, NSOperationQueue;

// Not exported
@interface EKUIEventInviteesViewController : UITableViewController <EKEditItemViewControllerDelegate, UIActionSheetDelegate, UITableViewDataSource, UITableViewDelegate, MFMailComposeViewControllerDelegate, MFMessageComposeViewControllerDelegate, EKEditItemViewControllerProtocol>
{
    _Bool _supportsAvailabilityRequests;
    NSDictionary *_cachedABPeople;
    NSArray *_attendeesIgnoringMe;
    NSArray *_allParticipants;
    NSArray *_locationParticipants;
    NSArray *_sortedNonLocationRespondedParticipants;
    NSArray *_sortedNonLocationNotRespondedParticipants;
    NSMutableArray *_busyParticipants;
    NSMutableDictionary *_addressesToParticipants;
    NSMutableArray *_proposedFreeTimesAllAttendees;
    NSMutableArray *_proposedFreeTimesSomeAttendees;
    unsigned long long _proposedFreeTimeDurationInWeeks;
    NSMutableDictionary *_participantAddressToEventAvailabilityState;
    NSMutableDictionary *_participantAddressToFutureAvailabilitySpans;
    unsigned long long _numberOfAttendeesToConsiderForConflictResolution;
    NSObject<OS_dispatch_queue> *_eventLoadingQueue;
    EKRequestAvailabilityOperation *_eventAvailabilityOperation;
    EKRequestAvailabilityOperation *_futureAvailabilityOperation;
    NSOperationQueue *_availabilityRequestsQueue;
    _Bool _conflictDetected;
    _Bool _showConflictResolutionSections;
    _Bool _showParticipationStatus;
    _Bool _searchingForMoreFreeBlocks;
    NSNumber *_schedulingConflictCheckedIndex;
    NSNumber *_allAttendeesCheckedIndex;
    NSNumber *_someAttendeesCheckedIndex;
    EKEvent *_event;
    EKUIEventInviteesView *_inviteesView;
    _Bool _needsEventRefresh;
    _Bool _viewIsVisible;
    _Bool _onlyShowSingleAllAttendeesFreeTime;
    NSMutableArray *_allBlocks;
    _Bool _showAlternativeTimes;
    NSDate *_selectedStartDate;
    NSDate *_selectedEndDate;
    id _numberOfConflictsChangedBlock;
}

+ (id)_blankImage;
+ (id)_debugHeaderTitleForSection:(long long)arg1;
@property(copy, nonatomic) id numberOfConflictsChangedBlock; // @synthesize numberOfConflictsChangedBlock=_numberOfConflictsChangedBlock;
@property(retain, nonatomic) NSDate *selectedEndDate; // @synthesize selectedEndDate=_selectedEndDate;
@property(retain, nonatomic) NSDate *selectedStartDate; // @synthesize selectedStartDate=_selectedStartDate;
- (void).cxx_destruct;
- (id)attendeesIgnorningMe;
- (id)cachedABPeople;
- (id)_htmlBodyForMailMessageWithNames:(id)arg1;
- (void)sendEmail:(id)arg1;
- (id)_participantAddressForParticipant:(id)arg1;
- (void)_calculateNextFreeTimesForStartDate:(id)arg1 endDate:(id)arg2;
- (void)_makeAllAttendeeCells;
- (_Bool)_rowRepresentsLoadMoreSomeAttendeesCell:(long long)arg1;
- (_Bool)_rowRepresentsLoadMoreAllAttendeesCell:(long long)arg1;
- (_Bool)_rowRepresentsAddPersonCell:(long long)arg1;
- (_Bool)_isCellAtIndexPathDeleteable:(id)arg1;
- (void)_disclosureButtonTappedForRowWithIndexPath:(id)arg1;
- (long long)_indexForSection:(long long)arg1;
- (id)_attendeesOnlyOrganizerAndLocations;
- (id)_attendeesWithoutOrganizerAndLocations;
- (long long)_sectionForIndex:(long long)arg1;
- (void)_calculateProposedTimes;
- (void)_refreshFromEventIfNeeded;
- (void)_eventModified:(id)arg1;
@property(readonly, nonatomic) long long numberOfConflicts;
- (_Bool)editItemViewControllerShouldShowDetachAlert;
- (void)editItemViewController:(id)arg1 didCompleteWithAction:(int)arg2;
- (id)tableView:(id)arg1 titleForDeleteConfirmationButtonForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 estimatedHeightForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)mailComposeController:(id)arg1 didFinishWithResult:(int)arg2 error:(id)arg3;
- (void)messageComposeViewController:(id)arg1 didFinishWithResult:(int)arg2;
- (unsigned long long)supportedInterfaceOrientations;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)loadView;
- (void)dealloc;
- (id)initWithEvent:(id)arg1 showAlternativeTimes:(_Bool)arg2;

// Remaining properties
@property(nonatomic) __weak id <EKEditItemViewControllerDelegate> editDelegate;
@property(nonatomic) _Bool editItemShouldBeAskedForInjectableViewController;
@property(nonatomic) _Bool presentModally;

@end

