/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIView.h"

@class EKUIDividedGridViewController;

@interface EKUIDividedGridView : UIView
{
    EKUIDividedGridViewController *_viewController;
}

@property __weak EKUIDividedGridViewController *viewController; // @synthesize viewController=_viewController;
- (void).cxx_destruct;
- (struct CGSize)intrinsicContentSize;

@end

