/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIViewController.h"

#import "UIPickerViewDataSource-Protocol.h"
#import "UIPickerViewDelegate-Protocol.h"

@class UIPickerView;

@interface EKUICustomRecurrenceIntervalViewController : UIViewController <UIPickerViewDataSource, UIPickerViewDelegate>
{
    UIPickerView *_pickerView;
    int _frequency;
    long long _interval;
    id _changeBlock;
}

@property(copy) id changeBlock; // @synthesize changeBlock=_changeBlock;
@property(nonatomic) long long interval; // @synthesize interval=_interval;
@property(nonatomic) int frequency; // @synthesize frequency=_frequency;
- (void).cxx_destruct;
- (void)pickerView:(id)arg1 didSelectRow:(long long)arg2 inComponent:(long long)arg3;
- (id)pickerView:(id)arg1 titleForRow:(long long)arg2 forComponent:(long long)arg3;
- (long long)pickerView:(id)arg1 numberOfRowsInComponent:(long long)arg2;
- (long long)numberOfComponentsInPickerView:(id)arg1;
- (id)pickerView;
- (void)loadView;
- (id)initWithSelectedInterval:(long long)arg1 frequency:(int)arg2 changeBlock:(id)arg3;

@end

