/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UITableViewCell.h"

@class EKUIDividedGridViewController, UIView;

@interface EKUIDividedGridViewTableViewCell : UITableViewCell
{
    EKUIDividedGridViewController *_gridViewController;
    UIView *_bottomDivider;
}

@property(retain) UIView *bottomDivider; // @synthesize bottomDivider=_bottomDivider;
@property(retain) EKUIDividedGridViewController *gridViewController; // @synthesize gridViewController=_gridViewController;
- (void).cxx_destruct;
- (_Bool)wantsDrawBackground;
- (struct CGRect)_separatorFrame;
- (void)setDrawBottomDivider:(_Bool)arg1;
- (_Bool)drawBottomDivider;
- (_Bool)_isWiderThanMaximum;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 gridViewType:(long long)arg3 buttonTitles:(id)arg4;

@end

