/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCopying-Protocol.h"
#import "SSXPCCoding-Protocol.h"

@class NSArray;

@interface SSVDialogResponse : NSObject <NSCopying, SSXPCCoding>
{
    long long _selectedButtonIndex;
    NSArray *_textFieldValues;
}

@property(copy, nonatomic) NSArray *textFieldValues; // @synthesize textFieldValues=_textFieldValues;
@property(nonatomic) long long selectedButtonIndex; // @synthesize selectedButtonIndex=_selectedButtonIndex;
- (void).cxx_destruct;
- (id)copyXPCEncoding;
- (id)initWithXPCEncoding:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

