/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "SSXPCCoding-Protocol.h"

@class NSNumber, NSURL;

@interface SSVServerAuthenticateResponse : NSObject <SSXPCCoding>
{
    NSNumber *_authenticatedAccountIdentifier;
    long long _performedButtonIndex;
    NSURL *_redirectURL;
    long long _selectedButtonIndex;
}

@property(nonatomic) long long selectedButtonIndex; // @synthesize selectedButtonIndex=_selectedButtonIndex;
@property(copy, nonatomic) NSURL *redirectURL; // @synthesize redirectURL=_redirectURL;
@property(nonatomic) long long performedButtonIndex; // @synthesize performedButtonIndex=_performedButtonIndex;
@property(copy, nonatomic) NSNumber *authenticatedAccountIdentifier; // @synthesize authenticatedAccountIdentifier=_authenticatedAccountIdentifier;
- (void).cxx_destruct;
- (id)copyXPCEncoding;
- (id)initWithXPCEncoding:(id)arg1;

@end

