/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <CloudKit/CKOperationInfo.h>

@class CKCommentCursor, CKCommentQuery;

@interface CKFetchShareCommentsOperationInfo : CKOperationInfo
{
    CKCommentQuery *_query;
    CKCommentCursor *_cursor;
    unsigned long long _resultsLimit;
}

+ (_Bool)supportsSecureCoding;
@property(nonatomic) unsigned long long resultsLimit; // @synthesize resultsLimit=_resultsLimit;
@property(retain, nonatomic) CKCommentCursor *cursor; // @synthesize cursor=_cursor;
@property(retain, nonatomic) CKCommentQuery *query; // @synthesize query=_query;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end

