/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray, NSObject<OS_dispatch_queue>;

@interface CKSQLitePool : NSObject
{
    _Bool _drainScheduled;
    id _factory;
    NSMutableArray *_dbs;
    NSObject<OS_dispatch_queue> *_queue;
}

@property(nonatomic) _Bool drainScheduled; // @synthesize drainScheduled=_drainScheduled;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(retain, nonatomic) NSMutableArray *dbs; // @synthesize dbs=_dbs;
@property(readonly, copy, nonatomic) id factory; // @synthesize factory=_factory;
- (void).cxx_destruct;
- (void)_drain;
- (void)_scheduleDrain;
- (void)_closeDatabase:(id)arg1;
- (id)_openDatabaseWithError:(id *)arg1;
- (void)performWithDatabase:(id)arg1;
- (_Bool)performWithDatabase:(id)arg1 error:(void)arg2;
- (void)closeAll;
- (void)releaseDatabase:(id)arg1;
- (id)acquireDatabase;
- (id)_acquireDatabaseWithError:(id *)arg1;
- (id)initWithFactory:(id)arg1;

@end

