/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <CloudKit/CKOperationInfo.h>

@class CKShareID, NSString;

@interface CKUpdateUserPresenceOperationInfo : CKOperationInfo
{
    _Bool _isLurk;
    long long _status;
    unsigned long long _customStatusFlags;
    double _ttl;
    CKShareID *_shareID;
    NSString *_lastETag;
}

+ (_Bool)supportsSecureCoding;
@property(retain, nonatomic) NSString *lastETag; // @synthesize lastETag=_lastETag;
@property(retain, nonatomic) CKShareID *shareID; // @synthesize shareID=_shareID;
@property(nonatomic) _Bool isLurk; // @synthesize isLurk=_isLurk;
@property(nonatomic) double ttl; // @synthesize ttl=_ttl;
@property(nonatomic) unsigned long long customStatusFlags; // @synthesize customStatusFlags=_customStatusFlags;
@property(nonatomic) long long status; // @synthesize status=_status;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end

