/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <CloudPhotoLibrary/CPLEngineStorage.h>

#import "CPLAbstractObject-Protocol.h"

@class CPLPlatformObject;

@interface CPLEngineChangePipe : CPLEngineStorage <CPLAbstractObject>
{
}

@property(nonatomic, getter=isLocked) _Bool locked;
- (id)allChangeBatches;
- (id)popAllChangeBatchesWithError:(id *)arg1;
- (_Bool)compactChangeBatchesWithError:(id *)arg1;
- (_Bool)deleteAllChangeBatchesWithError:(id *)arg1;
- (_Bool)popNextBatchWithError:(id *)arg1;
- (id)nextBatch;
- (_Bool)popChangeBatch:(id *)arg1 error:(id *)arg2;
- (_Bool)appendChangeBatch:(id)arg1 error:(id *)arg2;
- (unsigned long long)countOfQueuedBatches;
- (id)initWithEngineStore:(id)arg1 name:(id)arg2;

// Remaining properties
@property(readonly, nonatomic) CPLPlatformObject *platformObject;

@end

