/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "CPLAbstractObject-Protocol.h"
#import "CPLEngineComponent-Protocol.h"

@class CPLEngineLibrary, CPLPlatformObject;

@interface CPLEngineTransport : NSObject <CPLAbstractObject, CPLEngineComponent>
{
    CPLPlatformObject *_platformObject;
    CPLEngineLibrary *_engineLibrary;
}

+ (id)platformImplementationProtocol;
@property(readonly, nonatomic) __weak CPLEngineLibrary *engineLibrary; // @synthesize engineLibrary=_engineLibrary;
@property(readonly, nonatomic) CPLPlatformObject *platformObject; // @synthesize platformObject=_platformObject;
- (void).cxx_destruct;
- (void)getStatusDictionaryWithCompletionHandler:(id)arg1;
- (void)getStatusWithCompletionHandler:(id)arg1;
- (id)componentName;
- (void)closeAndDeactivate:(_Bool)arg1 completionHandler:(id)arg2;
- (void)openWithCompletionHandler:(id)arg1;
- (id)bestErrorForUnderlyingError:(id)arg1;
- (id)resourceUploadTaskForResource:(id)arg1 ofRecord:(id)arg2 didStartHandler:(id)arg3 progressHandler:(void)arg4 completionHandler:(id)arg5;
- (_Bool)supportsDelayedUploads;
- (id)removeLibraryTaskWithCompletionHandler:(id)arg1;
- (id)resourcePublishTaskForResource:(id)arg1 completionHandler:(id)arg2;
- (id)resourceDownloadTaskForResource:(id)arg1 didStartHandler:(id)arg2 progressHandler:(void)arg3 completionHandler:(id)arg4;
- (id)downloadBatchTaskForSyncAnchor:(id)arg1 completionHandler:(id)arg2;
- (id)uploadBatchTaskForBatch:(id)arg1 completionHandler:(id)arg2;
- (id)setupTaskWithCompletionHandler:(id)arg1;
- (id)initWithEngineLibrary:(id)arg1;

@end

