/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <PhotoLibrary/PLPhotoBrowserController.h>

#import "UIGestureRecognizerDelegate-Protocol.h"

@interface PLWPhotoBrowserController : PLPhotoBrowserController <UIGestureRecognizerDelegate>
{
}

- (_Bool)wantsPhotoBrowserStyleStatusBar;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)loadView;
- (id)initWithAssetCollections:(id)arg1 atImageIndexPath:(id)arg2 datasource:(id)arg3 modalDoneButtonItem:(id)arg4;

@end

