/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

@protocol GSProtocol
- (void)getFileIdForDocumentId:(unsigned long long)arg1 onDevice:(int)arg2 reply:(id)arg3;
- (oneway void)setLogLevel:(unsigned int)arg1;
- (void)requestFreeSpace:(unsigned long long)arg1 forVolume:(id)arg2 reply:(id)arg3;
- (void)setAdditionNameSpaceInStorage:(long long)arg1 nameSpace:(id)arg2 additionName:(id)arg3 value:(id)arg4 completionHandler:(id)arg5;
- (void)setAdditionDisplayNameInStorage:(long long)arg1 nameSpace:(id)arg2 additionName:(id)arg3 value:(id)arg4 reply:(id)arg5;
- (void)mergeAdditionInfoValueInStorage:(long long)arg1 nameSpace:(id)arg2 additionName:(id)arg3 value:(id)arg4 reply:(id)arg5;
- (void)createAdditionInStorage:(long long)arg1 stagedFileDescriptor:(id)arg2 creationInfo:(id)arg3 completionHandler:(id)arg4;
- (void)removeAdditionsInStorage:(long long)arg1 removalSpec:(id)arg2 completionHandler:(id)arg3;
- (void)setAdditionOptionsInStorage:(long long)arg1 nameSpace:(id)arg2 additionName:(id)arg3 value:(unsigned long long)arg4 reply:(id)arg5;
- (void)listAdditionsOfStorage:(long long)arg1 nameSpace:(id)arg2 withOptions:(unsigned long long)arg3 withoutOptions:(unsigned long long)arg4 andEnumerationState:(id)arg5 completionHandler:(id)arg6;
- (void)getAdditionsInStorage:(long long)arg1 andNameSpace:(id)arg2 named:(id)arg3 completionHandler:(id)arg4;
- (void)getAdditionInStorage:(long long)arg1 andNameSpace:(id)arg2 named:(id)arg3 completionHandler:(id)arg4;
- (oneway void)permanentStorageClose:(unsigned long long)arg1;
- (void)permanentStorageOpenForHandle:(id)arg1 withRemoteID:(unsigned long long)arg2 andDocumentID:(id)arg3 reply:(id)arg4;
- (oneway void)stagingPrefixRelinquish:(id)arg1;
- (void)stagingPrefixForDevice:(int)arg1 volumeUUID:(id)arg2 reply:(id)arg3;
- (void)isPermanentStorageSupportedForHandle:(id)arg1 reply:(id)arg2;
@end

