/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSArray;

@interface BKSHIDEventRouterManagerBase : NSObject
{
    NSArray *_eventRouters;
}

@property(retain, nonatomic) NSArray *eventRouters; // @synthesize eventRouters=_eventRouters;
- (id)description;
- (long long)routerDestinationForDescriptor:(id)arg1;
- (id)init;

@end

