/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSData.h"

@class ML3DatabaseConnection, ML3MusicLibrary;

@interface HomeSharingPlaylistImporter : NSData
{
    NSData *_playlistData;
    ML3MusicLibrary *_library;
    ML3DatabaseConnection *_connection;
    unsigned long long _basePlaylistContainerId;
}

- (void).cxx_destruct;
- (_Bool)importPlaylistData;
- (_Bool)executeUpdateSQL:(id)arg1;
- (id)initWithData:(id)arg1 basePlaylistContainerId:(unsigned long long)arg2 library:(id)arg3 connection:(id)arg4;

@end

