/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class HSConnection, NSString;

@interface HSCloudLibrary : NSObject
{
    NSString *_name;
    NSString *_uniqueIdentifier;
    HSConnection *_connection;
}

@property(readonly, nonatomic) HSConnection *connection; // @synthesize connection=_connection;
@property(readonly, copy, nonatomic) NSString *uniqueIdentifier; // @synthesize uniqueIdentifier=_uniqueIdentifier;
@property(readonly, copy, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (id)initWithConnectionConfiguration:(id)arg1;

@end

