/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class BSDispatchSource;

@interface BSProcessDeathWatcher : NSObject
{
    BSDispatchSource *_source;
    id _deathHandler;
}

- (void)invalidate;
- (void)dealloc;
- (id)initWithPID:(int)arg1 queue:(id)arg2 deathHandler:(id)arg3;

@end

