/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIViewController.h"

#import "SBSUICarDisplayNowPlayingInterface-Protocol.h"

@interface SBSUICarDisplayNowPlayingViewController : UIViewController <SBSUICarDisplayNowPlayingInterface>
{
}

+ (id)_exportedInterface;
+ (id)_remoteViewControllerInterface;
- (void)switchToState:(id)arg1;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

