/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "BRCLifeCycle-Protocol.h"
#import "BRCTransferQueueDelegate-Protocol.h"

@class BRCLocalContainer, BRCOperationMultiplexer, BRCTransferQueue, NSObject<OS_dispatch_queue>;

@interface BRCVersionUploader : NSObject <BRCTransferQueueDelegate, BRCLifeCycle>
{
    NSObject<OS_dispatch_queue> *_queue;
    BRCTransferQueue *_transferQueue;
    BRCLocalContainer *_container;
    BRCOperationMultiplexer *_uploadMultiplexer;
}

@property(readonly, nonatomic) BRCOperationMultiplexer *uploadMultiplexer; // @synthesize uploadMultiplexer=_uploadMultiplexer;
- (void).cxx_destruct;
- (void)transferQueueDidRequestOperations:(id)arg1;
- (void)_scheduleUploads;
- (_Bool)_scheduleUploadForItem:(id)arg1;
- (void)cancelUploadForItemID:(id)arg1;
- (_Bool)isUploadingItemID:(id)arg1;
- (void)signalNeedsUploads;
- (void)_didFailUploadingContentWithItemID:(id)arg1 error:(id)arg2;
- (void)_didUploadContentWithItemID:(id)arg1 record:(id)arg2;
- (id)verboseDescription;
- (void)resume;
- (void)suspend;
- (void)close;
- (id)description;
- (id)initWithLocalContainer:(id)arg1;

@end

