/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "PQLResultSetInitializer-Protocol.h"

@interface NSObject (PQLResultSetInitializer) <PQLResultSetInitializer>
- (id)initFromPQLResultSet:(id)arg1 error:(id *)arg2;
@end

