/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

@protocol AVVideoLayer
@property(readonly, nonatomic) struct CGRect videoRect;
@property(readonly, nonatomic, getter=isReadyForDisplay) _Bool readyForDisplay;
@property(nonatomic) long long videoLayerGravity;
- (void)setPlayerController:(id)arg1;
@end

