/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <GameCenterUI/GKHostedViewController.h>

@interface GKHostedMatchmakerViewController : GKHostedViewController
{
}

- (void)didGetRemoteViewController;
- (id)_presentingViewController;
- (void)presentRemoteViewControllerIfNeeded;
- (id)hostSideViewControllerClassName;
- (id)serviceSideViewControllerClassName;
- (id)remoteMatchmakerViewController;
- (id)matchmakerViewController;

@end

