/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface MKIconManager : NSObject
{
}

+ (id)imageForMapItem:(id)arg1 size:(unsigned long long)arg2 forScale:(double)arg3;
+ (id)imageForMapItem:(id)arg1 forScale:(double)arg2;
+ (id)identifiersForMapItem:(id)arg1 forSize:(unsigned long long)arg2;

@end

