/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIView.h"

@class NSArray, NSString, UIButton, UILabel;

// Not exported
@interface MKPlaceSectionHeaderView : UIView
{
    _Bool _showSeeMoreButton;
    NSString *_sectionHeaderText;
    UILabel *_sectionHeaderLabel;
    UIButton *_seeMoreButton;
    NSArray *_seeMoreButtonConstraints;
    NSArray *_noSeeMoreButtonConstraints;
    SEL _action;
    id _target;
}

@property(nonatomic) __weak id target; // @synthesize target=_target;
@property(nonatomic) SEL action; // @synthesize action=_action;
@property(retain, nonatomic) NSArray *noSeeMoreButtonConstraints; // @synthesize noSeeMoreButtonConstraints=_noSeeMoreButtonConstraints;
@property(retain, nonatomic) NSArray *seeMoreButtonConstraints; // @synthesize seeMoreButtonConstraints=_seeMoreButtonConstraints;
@property(retain, nonatomic) UIButton *seeMoreButton; // @synthesize seeMoreButton=_seeMoreButton;
@property(retain, nonatomic) UILabel *sectionHeaderLabel; // @synthesize sectionHeaderLabel=_sectionHeaderLabel;
@property(copy, nonatomic) NSString *sectionHeaderText; // @synthesize sectionHeaderText=_sectionHeaderText;
@property(nonatomic) _Bool showSeeMoreButton; // @synthesize showSeeMoreButton=_showSeeMoreButton;
- (void).cxx_destruct;
- (void)setTarget:(id)arg1 action:(SEL)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

