/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UITableViewCell.h"

@class NSAttributedString, UILabel;

// Not exported
@interface MKPlaceReviewsViewCheckInWriteCell : UITableViewCell
{
    UILabel *_checkInLabel;
    UILabel *_writeReviewLabel;
    id <MKPlaceReviewsViewCheckInWriteCellDelegate> _delegate;
}

+ (id)reuseIdentifier;
@property(nonatomic) __weak id <MKPlaceReviewsViewCheckInWriteCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)cellTapped:(id)arg1;
@property(retain, nonatomic) NSAttributedString *writeReviewTitle;
@property(retain, nonatomic) NSAttributedString *checkInTitle;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

