/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIView.h"

@class UISegmentedControl, _UIBackdropView;

@interface MKSegmentedControlTabBarView : UIView
{
    _UIBackdropView *_blurView;
    UIView *_hairline;
    id _didChangeSelectedSegmentIndex;
    long long _backdropStyle;
    UISegmentedControl *_segmentedControl;
}

@property(nonatomic) long long backdropStyle; // @synthesize backdropStyle=_backdropStyle;
@property(copy, nonatomic) id didChangeSelectedSegmentIndex; // @synthesize didChangeSelectedSegmentIndex=_didChangeSelectedSegmentIndex;
- (void).cxx_destruct;
- (void)_segmentSelectionDidChange;
@property(readonly, nonatomic) UISegmentedControl *segmentedControl; // @synthesize segmentedControl=_segmentedControl;
- (void)setContentFromViewController:(id)arg1;
- (void)didMoveToWindow;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

