/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIViewController.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSArray, NSDictionary, NSMapTable, UITableView, UIView, _MKStackingView;

@interface MKStackingViewController : UIViewController <UITableViewDataSource, UITableViewDelegate>
{
    _MKStackingView *_stackingView;
    UIView *_contentView;
    _Bool _isScrollingProgrammaticallyToViewController;
    unsigned long long _inTableViewCallbacks;
    UITableView *_table;
    _Bool _hasScrolledToTop;
    NSDictionary *_previousNavigationBarBackgroundsByStyle;
    NSMapTable *_knownHeightsForRowsByViewControllers;
    id <MKStackingViewControllerDelegate> _stackingDelegate;
    UIView *_headerView;
    UIView *_selectorView;
    NSArray *_viewControllers;
    UIViewController *_selectedViewController;
}

@property(nonatomic) __weak UIViewController *selectedViewController; // @synthesize selectedViewController=_selectedViewController;
@property(copy, nonatomic) NSArray *viewControllers; // @synthesize viewControllers=_viewControllers;
@property(retain, nonatomic) UIView *selectorView; // @synthesize selectorView=_selectorView;
@property(retain, nonatomic) UIView *headerView; // @synthesize headerView=_headerView;
@property(nonatomic) __weak id <MKStackingViewControllerDelegate> stackingDelegate; // @synthesize stackingDelegate=_stackingDelegate;
- (void).cxx_destruct;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)_rowIndexForIndexPath:(id)arg1;
- (_Bool)_showsTitleForViewController:(id)arg1;
- (_Bool)_showsTitleForSectionAtIndex:(long long)arg1;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)_preferredSizeDidChangeForViewControllerAtIndex:(unsigned long long)arg1;
- (void)_setTopInset:(double)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)_scrollToViewControllerAtIndex:(unsigned long long)arg1 animated:(_Bool)arg2;
- (void)_enumerateVisibleCellsUsingBlock:(id)arg1;
- (double)_heightForViewOfViewController:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)_updateSelectedViewControllerAfterPositionChange;
- (void)_updateSelectorView;
- (void)setSelectorViewNeedsUpdate;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)performUserSelectionForViewControllerAtIndex:(unsigned long long)arg1;
- (void)_setSelectedViewController:(id)arg1 animated:(_Bool)arg2;
- (void)setSelectedViewController:(id)arg1 animated:(_Bool)arg2;
- (_Bool)_isInTableViewCallbacks;
- (void)_performAsTableViewCallback:(id)arg1;
- (void)_stopObservingPropertiesOfViewController:(id)arg1;
- (void)_startObservingPropertiesOfViewController:(id)arg1;
- (double)_fittingHeightForView:(id)arg1;
- (double)_topLayoutGuideLength;
- (double)_selectorHeight;
- (double)_headerHeight;
- (void)_repositionTopViews;
- (void)_getSelectorViewFrame:(out struct CGRect *)arg1 headerViewFrame:(out struct CGRect *)arg2 headerViewBackgroundTransfrom:(out struct CATransform3D *)arg3 forContentBounds:(struct CGRect)arg4;
- (void)viewDidLayoutSubviews;
- (void)viewWillLayoutSubviews;
- (void)_addFloatingSubviewIfPossibleAndNeeded:(id)arg1;
- (struct CGSize)_contentSize;
- (void)viewDidLoad;
- (void)loadView;
- (void)_setNeedsLayout;
- (void)dealloc;

@end

