/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface SBSLockScreenPluginService : NSObject
{
}

- (void)disableLockScreenBundle:(id)arg1 withContext:(id)arg2;
- (void)enableLockScreenBundle:(id)arg1 withContext:(id)arg2;
- (id)_serializedDataForContext:(id)arg1;

@end

