/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <OfficeImport/OAXClient.h>

// Not exported
@interface EXOfficeArtClient : OAXClient
{
    _Bool mAutoChartFillIsHollow;
    _Bool mAutoChartStrokeIsHollow;
}

@property _Bool autoChartStrokeIsHollow; // @synthesize autoChartStrokeIsHollow=mAutoChartStrokeIsHollow;
@property _Bool autoChartFillIsHollow; // @synthesize autoChartFillIsHollow=mAutoChartFillIsHollow;
- (_Bool)chartAutoStrokeIsHollow;
- (_Bool)chartAutoFillIsHollow;
- (void)readClientDataFromNode:(struct _xmlNode *)arg1 toDrawable:(id)arg2 state:(id)arg3;

@end

