/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIViewController.h"

#import "MPAVRoutingControllerDelegate-Protocol.h"
#import "MPUChronologicalProgressViewDelegate-Protocol.h"
#import "MPUMediaControlsTitlesViewDelegate-Protocol.h"
#import "MPUNowPlayingDelegate-Protocol.h"
#import "MPURemoteViewControllerPresentation-Protocol.h"
#import "MPUTransportControlsViewDelegate-Protocol.h"
#import "RUTrackActionsDelegate-Protocol.h"
#import "UIModalItemDelegate-Protocol.h"
#import "UIPopoverControllerDelegate-Protocol.h"

@class MPAVRoutingController, MPUNowPlayingController, MPUSystemMediaControlsView, NSArray, NSDictionary, NSString, NSTimer, RUTrackActionsModalItem, RUTrackActionsViewController, UIImageView, UIPopoverController, UIView;

@interface MPUSystemMediaControlsViewController : UIViewController <MPUNowPlayingDelegate, MPUTransportControlsViewDelegate, MPURemoteViewControllerPresentation, MPUChronologicalProgressViewDelegate, MPUMediaControlsTitlesViewDelegate, MPAVRoutingControllerDelegate, RUTrackActionsDelegate, UIModalItemDelegate, UIPopoverControllerDelegate>
{
    MPUNowPlayingController *_nowPlayingController;
    MPAVRoutingController *_routingController;
    MPUSystemMediaControlsView *_mediaControlsView;
    UIImageView *_artworkImageView;
    _Bool _nowPlayingInfoIsOverridingSupportedCommands;
    unsigned int _runningLongPressCommand;
    NSArray *_currentlySupportedCommands;
    NSDictionary *_nowPlayingInfoForPresentedTrackActions;
    UIPopoverController *_trackActionsPopoverController;
    RUTrackActionsModalItem *_trackActionsModalItem;
    RUTrackActionsViewController *_trackActionsViewController;
    NSTimer *_skipInformationRevealTimer;
    NSTimer *_scrubberCommitTimer;
    double _scrubbedTimeDestination;
    double _lastDurationFromUpdate;
    NSString *_audioCategoryForDisabledHUD;
    _Bool _lockscreenDisabledForScreenTurnOff;
    _Bool _wantsToLaunchNowPlayingApp;
    _Bool _persistentUpdatesEnabled;
    long long _style;
    id <MPUSystemMediaControlsDelegate> _delegate;
}

@property(nonatomic) _Bool persistentUpdatesEnabled; // @synthesize persistentUpdatesEnabled=_persistentUpdatesEnabled;
@property(nonatomic) __weak id <MPUSystemMediaControlsDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) long long style; // @synthesize style=_style;
- (void).cxx_destruct;
- (id)_commandOptionsForRadioItemUsingNowPlayingInfo:(id)arg1;
- (void)_cancelRunningLongPressCommand;
- (void)_launchCurrentNowPlayingApp;
- (void)_updateSupportedCommands;
- (void)_revealSkipInformation;
- (void)_invalidateSkipInformationRevealTimer;
- (void)_scheduleSkipInformationRevealTimer;
- (void)_stopScrubberCommitTimer;
- (void)_commitCurrentScrubberValue;
- (void)_beginScrubberCommitTimer;
- (void)_tearDownNotifications;
- (void)_setupNotifications;
- (void)_applyNowPlayingInformation:(id)arg1 toTrackActioningController:(id)arg2;
- (void)_buyButtonActionForSender:(id)arg1 command:(unsigned int)arg2;
- (void)_buyAlbumButtonAction:(id)arg1;
- (void)_buyTrackButtonAction:(id)arg1;
- (void)_likeBanButtonTapped:(id)arg1;
- (void)_systemAppDidSkipTrackNotification:(id)arg1;
- (void)_supportedCommandsDidChangeNotification:(id)arg1;
- (void)_backlightLevelChangedNotification:(id)arg1;
- (void)popoverControllerDidDismissPopover:(id)arg1;
- (void)modalItem:(id)arg1 didDismissWithButtonIndex:(long long)arg2;
- (id)trackActioningObject:(id)arg1 localizedTitleForAction:(long long)arg2;
- (void)trackActioningObject:(id)arg1 didSelectAction:(long long)arg2 atIndex:(long long)arg3;
- (void)routingControllerAvailableRoutesDidChange:(id)arg1;
- (void)mediaControlsTitlesViewWasTapped:(id)arg1;
- (void)progressViewDidEndScrubbing:(id)arg1;
- (void)progressViewDidBeginScrubbing:(id)arg1;
- (void)remoteViewControllerDidFinish;
- (void)transportControlsView:(id)arg1 tapOnAccessoryButtonType:(long long)arg2;
- (void)transportControlsView:(id)arg1 longPressEndOnControlType:(long long)arg2;
- (void)transportControlsView:(id)arg1 longPressBeginOnControlType:(long long)arg2;
- (void)transportControlsView:(id)arg1 tapOnControlType:(long long)arg2;
- (void)nowPlayingController:(id)arg1 nowPlayingApplicationDidChange:(id)arg2;
- (void)nowPlayingController:(id)arg1 elapsedTimeDidChange:(double)arg2;
- (void)nowPlayingController:(id)arg1 playbackStateDidChange:(_Bool)arg2;
- (void)nowPlayingController:(id)arg1 nowPlayingInfoDidChange:(id)arg2;
@property(readonly, nonatomic) UIView *artworkView;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)loadView;
- (void)dealloc;
- (id)initWithStyle:(long long)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

