/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "CTCellularPlanClientDelegate-Protocol.h"

@class NSMutableArray, NSString, NSXPCConnection;

@interface CTCellularPlanManager : NSObject <CTCellularPlanClientDelegate>
{
    NSMutableArray *_subscriptionCompletions;
    struct dispatch_queue_s *_queue;
    NSString *_lastSessionId;
    NSXPCConnection *_connection;
}

+ (id)sharedManager;
- (void)dealloc;
- (void)subscriptionDetailsRequestDidFail:(id)arg1;
- (void)subscriptionDetailsDidUpdate:(id)arg1;
- (void)setUserInPurchaseFlow:(_Bool)arg1;
- (void)didPurchasePlanWithIccid:(id)arg1 downloadProfile:(_Bool)arg2;
- (void)setActivePlan:(id)arg1 completion:(id)arg2;
- (void)startPurchaseWithPlanId:(id)arg1 options:(id)arg2 completion:(id)arg3;
- (void)startPurchaseWithPlanId:(id)arg1 completion:(id)arg2;
- (void)subscriptionDetailsWithCompletion:(id)arg1;
- (void)plansForRenewalWithCompletion:(id)arg1;
- (void)plansWithCompletion:(id)arg1;
- (void)_plansForRenewal:(_Bool)arg1 completion:(id)arg2;
- (void)isNewDataPlanCapable:(id)arg1;
- (id)init;
- (void)_connect_sync;
- (void)_ensureConnected_sync;

@end

