/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <HealthKitUI/HKEmergencyCardMultilineTextTableItem.h>

@interface HKEmergencyCardMedicationInfoTableItem : HKEmergencyCardMultilineTextTableItem
{
}

- (void)_updateMultilineStringValueWithValue:(id)arg1;
- (id)_multilineStringValue;
- (id)_placeholderText;
- (id)title;
- (_Bool)hasPresentableData;

@end

