/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UITableViewCell.h"

@class UIImageView, UILabel, UISwitch;

@interface HKSwitchTableViewCell : UITableViewCell
{
    UILabel *_displayLabel;
    UIImageView *_iconImageView;
    UISwitch *_switch;
    id <HKSwitchTableViewCellDelegate> _delegate;
    struct UIEdgeInsets _marginInsets;
}

@property(nonatomic) struct UIEdgeInsets marginInsets; // @synthesize marginInsets=_marginInsets;
@property(nonatomic) __weak id <HKSwitchTableViewCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)switchValueChanged:(id)arg1;
@property(nonatomic, getter=isOn) _Bool on;
- (void)setIconImage:(id)arg1;
- (void)setDisplayText:(id)arg1;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)_setupUI;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

