/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <RadioUI/RURadioAVItem.h>

@interface RURadioAudioClipAVItem : RURadioAVItem
{
}

- (id)audioClip;
- (unsigned long long)type;
- (_Bool)supportsSkip;
- (void)loadAssetAndPlayerItem;
- (id)initWithAudioClip:(id)arg1;
- (id)artworkCatalogForPlaybackTime:(double)arg1;

@end

