/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface CAMAVMetadataHelper : NSObject
{
}

+ (_Bool)cameraMode:(long long *)arg1 fromMetadataItem:(id)arg2;
+ (_Bool)cameraMode:(long long *)arg1 fromMetadataItems:(id)arg2;
+ (_Bool)cameraMode:(long long *)arg1 fromAssetTrack:(id)arg2;
+ (_Bool)cameraMode:(long long *)arg1 fromAsset:(id)arg2;
+ (id)metadataItemForCameraMode:(long long)arg1;

@end

