/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <CameraKit/CAMBadgeView.h>

@interface CAMBadgeTextView : CAMBadgeView
{
}

- (double)_textVerticalInset;
- (double)_textHorizontalKerningOffset;
- (double)_textHorizontalInset;
- (id)_textAttributes;
- (id)_text;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (struct CGSize)_textSize;
- (id)_maskImage;

@end

