/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "BSBasicServerClient.h"

@class NSString;

@interface FBSystemServiceServerClient : BSBasicServerClient
{
    _Bool _UIApp;
    NSString *_bundlePath;
}

@property(retain, nonatomic) NSString *bundlePath; // @synthesize bundlePath=_bundlePath;
@property(nonatomic, getter=isUIApp) _Bool UIApp; // @synthesize UIApp=_UIApp;
@property(readonly, retain, nonatomic) NSString *bundleID;
@property(readonly, nonatomic) int pid;
- (id)description;
- (void)dealloc;

@end

