/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <FrontBoard/FBWorkspaceScene.h>

@class BKSProcessAssertion, FBApplicationWatchdog;

@interface FBUIApplicationWorkspaceScene : FBWorkspaceScene
{
    FBApplicationWatchdog *_watchdog;
    BKSProcessAssertion *_launchBoostahAssertion;
    unsigned long long _resumeProcessAssertionCount;
    BKSProcessAssertion *_resumeProcessAssertion;
    unsigned long long _suspendingProcessAssertionCount;
    BKSProcessAssertion *_suspendingProcessAssertion;
    int _suspendType;
    _Bool _createResponseReceived;
    _Bool _lastSuspendWasSEOUnderLock;
    _Bool _transitioningToForeground;
}

@property(readonly, nonatomic, getter=_workspaceQueue_isTransitioningToForeground) _Bool transitioningToForeground; // @synthesize transitioningToForeground=_transitioningToForeground;
- (void)_workspaceQueue_dropSuspendingProcessAssertion:(_Bool)arg1;
- (void)_workspaceQueue_dropSuspendingProcessAssertion;
- (void)_workspaceQueue_takeSuspendingProcessAssertion;
- (void)_workspaceQueue_dropResumeProcessAssertion:(_Bool)arg1;
- (void)_workspaceQueue_dropResumeProcessAssertion;
- (void)_workspaceQueue_takeResumeProcessAssertionWithThrottledCPU:(_Bool)arg1;
- (id)_workspaceQueue_createForegroundAssertionWithName:(id)arg1 throttledCPU:(_Bool)arg2;
- (unsigned long long)_workspaceQueue_determineSceneActionFromSettings:(id)arg1 toSettings:(id)arg2;
- (_Bool)_workspaceQueue_wantsDeactivateSEOForSettings:(id)arg1;
- (void)_workspaceQueue_cancelWatchdogTimer;
- (void)_workspaceQueue_startWatchdogTimerOfType:(int)arg1 withDuration:(double)arg2;
- (int)_workspaceQueue_pid;
- (id)_workspaceQueue_process;
- (id)_workspaceQueue_clientSettingsFromTransitionContext:(id)arg1;
- (void)_dispatchBlockAfterProcessLaunch:(id)arg1;
- (void)_workspaceQueue_deactivateResponseReceived:(id)arg1;
- (void)_workspaceQueue_deactivateWithSettings:(id)arg1 transitionContext:(id)arg2 eventBlock:(id)arg3;
- (void)_workspaceQueue_activateResponseReceived:(id)arg1;
- (void)_workspaceQueue_activateWithSettings:(id)arg1 transitionContext:(id)arg2 eventBlock:(id)arg3;
- (void)host:(id)arg1 didInvalidateWithTransitionContext:(id)arg2 completion:(id)arg3;
- (void)host:(id)arg1 didUpdateSettings:(id)arg2 withDiff:(id)arg3 transitionContext:(id)arg4 completion:(id)arg5;
- (void)_workspaceQueue_takeAssertionsForDeactivation:(_Bool)arg1;
- (void)_workspaceQueue_invalidate;
- (id)parentWorkspace;
- (void)dealloc;
- (id)initWithParentWorkspace:(id)arg1 host:(id)arg2 initialClientSettings:(id)arg3;

@end

