/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIView.h"

#import "UIPopoverControllerDelegate-Protocol.h"

@class WKContentView;

// Not exported
@interface WKAirPlayRoutePicker : UIView <UIPopoverControllerDelegate>
{
    struct RetainPtr<MPAVRoutingController> _routingController;
    struct RetainPtr<MPAudioVideoRoutingPopoverController> _popoverController;
    struct RetainPtr<MPAudioVideoRoutingActionSheet> _actionSheet;
    WKContentView *_view;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)show:(_Bool)arg1 fromRect:(struct CGRect)arg2;
- (void)showAirPlayPickerIPhone:(unsigned long long)arg1;
- (void)showAirPlayPickerIPad:(unsigned long long)arg1 fromRect:(struct CGRect)arg2;
- (void)_dismissAirPlayRoutePickerIPad;
- (void)_windowDidRotate:(id)arg1;
- (void)_windowWillRotate:(id)arg1;
- (void)_presentAirPlayPopoverAnimated:(_Bool)arg1 fromRect:(struct CGRect)arg2;
- (void)popoverControllerDidDismissPopover:(id)arg1;
- (void)dealloc;
- (id)initWithView:(id)arg1;

@end

