/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import <WebKit/WKObject-Protocol.h>

@class NSString, NSURL;

@interface WKBackForwardListItem : NSObject <WKObject>
{
    struct ObjectStorage<WebKit::WebBackForwardListItem> _item;
}

- (id).cxx_construct;
@property(readonly) struct Object *_apiObject;
@property(readonly) NSURL *initialURL;
@property(readonly) NSString *title;
@property(readonly) NSURL *URL;
- (void)dealloc;
@property(readonly) struct WebBackForwardListItem *_item;

@end

