/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIView.h"

#import "UIScrollViewDelegate-Protocol.h"

@class NSArray, NSData, NSString, NSURL, UIScrollView, WKBackForwardList, WKBrowsingContextHandle, WKWebViewConfiguration;

@interface WKWebView : UIView <UIScrollViewDelegate>
{
    struct RetainPtr<WKWebViewConfiguration> _configuration;
    struct RefPtr<WebKit::WebPageProxy> _page;
    struct unique_ptr<WebKit::NavigationState, std::__1::default_delete<WebKit::NavigationState>> _navigationState;
    struct unique_ptr<WebKit::UIDelegate, std::__1::default_delete<WebKit::UIDelegate>> _uiDelegate;
    struct RetainPtr<_WKRemoteObjectRegistry> _remoteObjectRegistry;
    unsigned long long _observedRenderingProgressEvents;
    struct WeakObjCPtr<id<_WKFormDelegate>> _formDelegate;
    struct RetainPtr<WKScrollView> _scrollView;
    struct RetainPtr<WKContentView> _contentView;
    _Bool _hasStaticMinimumLayoutSize;
    struct CGSize _minimumLayoutSizeOverride;
    struct CGSize _minimumLayoutSizeOverrideForMinimalUI;
    struct CGRect _inputViewBounds;
    struct UIEdgeInsets _obscuredInsets;
    _Bool _isChangingObscuredInsetsInteractively;
    struct UIEdgeInsets _extendedBackgroundExclusionInsets;
    UIView *_mainExtendedBackgroundView;
    UIView *_extendedBackgroundLayerTopInset;
    UIView *_extendedBackgroundLayerBottomInset;
    _Bool _needsResetViewStateAfterCommitLoadForMainFrame;
    _Bool _isAnimatingResize;
    struct CATransform3D _resizeAnimationTransformAdjustments;
    struct RetainPtr<UIView> _resizeAnimationView;
    double _lastAdjustmentForScroller;
    struct unique_ptr<WebKit::ViewGestureController, std::__1::default_delete<WebKit::ViewGestureController>> _gestureController;
    _Bool _allowsBackForwardNavigationGestures;
    struct RetainPtr<UIView<WKWebViewContentProvider>> _customContentView;
}

- (id).cxx_construct;
- (void).cxx_destruct;
@property(nonatomic) _Bool allowsBackForwardNavigationGestures;
- (void)_keyboardWillHide:(id)arg1;
- (void)_keyboardWillShow:(id)arg1;
- (void)_keyboardDidChangeFrame:(id)arg1;
- (void)_keyboardWillChangeFrame:(id)arg1;
- (void)_keyboardChangedWithInfo:(id)arg1 adjustScrollView:(_Bool)arg2;
- (void)_updateVisibleContentRects;
- (struct CGRect)_contentRectForUserInteraction;
- (void)_frameOrBoundsChanged;
- (void)scrollViewDidEndZooming:(id)arg1 withView:(id)arg2 atScale:(double)arg3;
- (void)scrollViewDidZoom:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewDidScrollToTop:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)_didFinishScrolling;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewWillBeginZooming:(id)arg1 withView:(id)arg2;
- (id)viewForZoomingInScrollView:(id)arg1;
- (_Bool)usesStandardContentView;
- (void)didMoveToWindow;
- (_Bool)_zoomToRect:(struct FloatRect)arg1 withOrigin:(struct FloatPoint)arg2 fitEntireRect:(_Bool)arg3 minimumScale:(double)arg4 maximumScale:(double)arg5 minimumScrollDistance:(float)arg6;
- (void)_zoomToFocusRect:(struct FloatRect)arg1 selectionRect:(struct FloatRect)arg2 fontSize:(float)arg3 minimumScale:(double)arg4 maximumScale:(double)arg5 allowScaling:(_Bool)arg6 forceScroll:(_Bool)arg7;
- (void)_zoomOutWithOrigin:(struct FloatPoint)arg1;
- (_Bool)_scrollToRect:(struct FloatRect)arg1 origin:(struct FloatPoint)arg2 minimumScrollDistance:(float)arg3;
- (void)_scrollToContentOffset:(struct FloatPoint)arg1;
- (void)_zoomToRect:(struct FloatRect)arg1 atScale:(double)arg2 origin:(struct FloatPoint)arg3;
- (void)_zoomToPoint:(struct FloatPoint)arg1 atScale:(double)arg2;
- (struct ViewSnapshot)_takeViewSnapshot;
- (void)_dynamicViewportUpdateChangedTargetToScale:(double)arg1 position:(struct CGPoint)arg2;
- (void)_didCommitLayerTree:(const struct RemoteLayerTreeTransaction *)arg1;
- (void)_didCommitLoadForMainFrame;
- (void)_updateScrollViewBackground;
- (void)_didFinishLoadingDataForCustomContentProviderWithSuggestedFilename:(const struct String *)arg1 data:(id)arg2;
- (void)_setHasCustomContentView:(_Bool)arg1 loadedMIMEType:(const struct String *)arg2;
- (id)browsingContextController;
@property(readonly, nonatomic) UIScrollView *scrollView;
- (void)setBounds:(struct CGRect)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (void)stopLoading;
- (id)reloadFromOrigin;
- (id)reload;
- (id)goForward;
- (id)goBack;
@property(readonly, nonatomic) _Bool canGoForward;
@property(readonly, nonatomic) _Bool canGoBack;
@property(readonly, nonatomic) _Bool hasOnlySecureContent;
@property(readonly, nonatomic) double estimatedProgress;
@property(readonly, nonatomic, getter=isLoading) _Bool loading;
@property(readonly, nonatomic) NSURL *URL;
@property(readonly, nonatomic) NSString *title;
- (id)goToBackForwardListItem:(id)arg1;
- (id)loadRequest:(id)arg1;
@property(nonatomic) __weak id <WKUIDelegate> UIDelegate;
@property(nonatomic) __weak id <WKNavigationDelegate> navigationDelegate;
@property(readonly, nonatomic) WKBackForwardList *backForwardList;
@property(readonly, nonatomic) WKWebViewConfiguration *configuration;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 configuration:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;
@property(readonly, nonatomic) NSURL *activeURL;
@property(readonly, nonatomic) NSString *_suggestedFilenameForDisplayedPDF;
@property(readonly, nonatomic) NSData *_dataForDisplayedPDF;
@property(readonly, nonatomic, getter=_isDisplayingPDF) _Bool _displayingPDF;
- (id)_viewForFindUI;
- (void)_snapshotRect:(struct CGRect)arg1 intoImageOfWidth:(double)arg2 completionHandler:(id)arg3;
- (void)_hideInspectorIndication;
- (void)_showInspectorIndication;
- (void)_endAnimatedResize;
- (void)_beginAnimatedResizeWithUpdates:(id)arg1;
- (void)_endInteractiveObscuredInsetsChange;
- (void)_beginInteractiveObscuredInsetsChange;
@property(nonatomic, setter=_setExtendedBackgroundExclusionInsets:) struct UIEdgeInsets _extendedBackgroundExclusionInsets;
@property(nonatomic, setter=_setBackgroundExtendsBeyondPage:) _Bool _backgroundExtendsBeyondPage;
@property(nonatomic, setter=_setObscuredInsets:) struct UIEdgeInsets _obscuredInsets;
@property(nonatomic, setter=_setMinimumLayoutSizeOverrideForMinimalUI:) struct CGSize _minimumLayoutSizeOverrideForMinimalUI;
@property(nonatomic, setter=_setMinimumLayoutSizeOverride:) struct CGSize _minimumLayoutSizeOverride;
@property(nonatomic, setter=_setFormDelegate:) __weak id <_WKFormDelegate> _formDelegate;
- (void)_hideFindUI;
- (void)_findString:(id)arg1 options:(unsigned long long)arg2 maxCount:(unsigned long long)arg3;
- (void)_countStringMatches:(id)arg1 options:(unsigned long long)arg2 maxCount:(unsigned long long)arg3;
@property(nonatomic, setter=_setFindDelegate:) __weak id <_WKFindDelegate> _findDelegate;
@property(nonatomic, setter=_setPageZoomFactor:) double _pageZoomFactor;
@property(nonatomic, setter=_setTextZoomFactor:) double _textZoomFactor;
@property(readonly, nonatomic) _Bool _supportsTextZoom;
@property(readonly) unsigned long long _pageCount;
@property(nonatomic, setter=_setGapBetweenPages:) double _gapBetweenPages;
@property(nonatomic, setter=_setPageLength:) double _pageLength;
@property(nonatomic, setter=_setPaginationBehavesLikeColumns:) _Bool _paginationBehavesLikeColumns;
@property(nonatomic, setter=_setPaginationMode:) long long _paginationMode;
- (void)_runJavaScriptInMainFrame:(id)arg1;
@property(nonatomic, setter=_setObservedRenderingProgressEvents:) unsigned long long _observedRenderingProgressEvents;
@property(nonatomic, setter=_setAddsVisitedLinks:) _Bool _addsVisitedLinks;
@property(nonatomic, setter=_setAllowsRemoteInspection:) _Bool _allowsRemoteInspection;
@property(nonatomic, setter=_setPrivateBrowsingEnabled:) _Bool _privateBrowsingEnabled;
- (void)_close;
- (void)_restoreFromSessionState:(id)arg1;
@property(readonly, nonatomic) NSData *_sessionState;
@property(readonly, nonatomic) int _webProcessIdentifier;
@property(copy, setter=_setCustomUserAgent:) NSString *_customUserAgent;
@property(copy, setter=_setApplicationNameForUserAgent:) NSString *_applicationNameForUserAgent;
@property(readonly, nonatomic) NSURL *_committedURL;
@property(readonly, nonatomic) NSArray *_certificateChain;
- (id)_reload;
- (void)_loadAlternateHTMLString:(id)arg1 baseURL:(id)arg2 forUnreachableURL:(id)arg3;
@property(readonly, nonatomic) NSURL *_unreachableURL;
@property(nonatomic, setter=_setHistoryDelegate:) __weak id <WKHistoryDelegatePrivate> _historyDelegate;
@property(readonly, nonatomic) WKBrowsingContextHandle *_handle;
@property(readonly, nonatomic) id _remoteObjectRegistry;

@end

