/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSArray, NSString;

@interface PRSSearchResponse : NSObject
{
    long long _status;
    NSString *_errorCodeString;
    double _backOff;
    double _maxAge;
    NSArray *_completionResultSets;
}

@property(readonly, nonatomic) NSArray *completionResultSets; // @synthesize completionResultSets=_completionResultSets;
@property(readonly, nonatomic) double maxAge; // @synthesize maxAge=_maxAge;
@property(readonly, nonatomic) double backOff; // @synthesize backOff=_backOff;
@property(readonly, nonatomic) NSString *errorCodeString; // @synthesize errorCodeString=_errorCodeString;
@property(readonly, nonatomic) long long status; // @synthesize status=_status;
- (void).cxx_destruct;
- (id)description;
- (id)initWithFactory:(id)arg1 resourceProvider:(id)arg2 array:(id)arg3;

@end

