/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <CFNetwork/__NSCFBackgroundSessionTask.h>

#import "NSStreamDelegate-Protocol.h"

@class NSFileHandle, NSInputStream, NSObject<OS_dispatch_io>, NSObject<OS_dispatch_queue>;

// Not exported
@interface __NSCFBackgroundDataTask : __NSCFBackgroundSessionTask <NSStreamDelegate>
{
    NSInputStream *_requestBodyStream;
    NSInputStream *_initialStream;
    NSObject<OS_dispatch_queue> *_writeQueue;
    NSObject<OS_dispatch_io> *_pipeIO;
    unsigned long long _bytesRead;
    _Bool _streamBased;
    NSFileHandle *_readHandle;
}

@property(readonly, getter=isStreamBased) _Bool streamBased; // @synthesize streamBased=_streamBased;
@property(readonly) NSFileHandle *readHandle; // @synthesize readHandle=_readHandle;
- (void)stream:(id)arg1 handleEvent:(unsigned long long)arg2;
- (void)finishStream:(_Bool)arg1;
- (void)readFromStream;
- (void)_onqueue_didReceiveData:(id)arg1 withCompletion:(id)arg2;
- (void)_onqueue_didReceiveResponse:(id)arg1 withCompletion:(id)arg2;
- (void)_onqueue_didReceiveResponse:(id)arg1 redirectRequest:(id)arg2 withCompletion:(id)arg3;
- (void)dealloc;
- (_Bool)isKindOfClass:(Class)arg1;
- (void)_onqueue_needNewBodyStream:(_Bool)arg1 withCompletion:(id)arg2;
- (void)captureStream:(id)arg1;
- (void)_onqueue_willSendRequestForEstablishedConnection:(id)arg1 withCompletion:(id)arg2;
- (void)_onqueue_openStream;
- (id)initWithSession:(id)arg1 remoteSession:(id)arg2 request:(id)arg3 ident:(unsigned long long)arg4;

@end

