/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#pragma mark Named Structures

struct BaseAwaitingTube;

struct BaseTubeManager;

struct CFURLProtocolClient {
    long long version;
    void *client;
    void *retain;
    void *release;
    void *copyDescription;
    void *wasRedirected;
    void *cacheResponseIsValid;
    void *didReceiveResponse;
    void *didLoadData;
    void *didFinishLoading;
    void *didFail;
    void *didReceiveAuthenticationChallenge;
};

struct CFURLProtocolImplementation {
    long long _field1;
    void *_field2;
    void *_field3;
    void *_field4;
    void *_field5;
    void *_field6;
    void *_field7;
    void *_field8;
    void *_field9;
};

struct CFURLProtocolInstanceCallbacks {
    long long _field1;
    void *_field2;
    void *_field3;
    void *_field4;
    void *_field5;
    void *_field6;
    void *_field7;
    void *_field8;
    void *_field9;
    void *_field10;
    void *_field11;
    void *_field12;
    void *_field13;
    void *_field14;
};

struct ConfigFlags {
    unsigned int :1;
    unsigned int :1;
    unsigned int :1;
    unsigned int :1;
    unsigned int :1;
    unsigned int :1;
    unsigned int :1;
};

struct CoreLockable;

struct CoreSchedulingSet {
    void **_field1;
    struct __CFAllocator *_field2;
    int _field3;
    void **_field4;
    struct _opaque_pthread_t *_field5;
    int _field6;
    union {
        struct __CFSet *_field1;
        id _field2;
        id _field3;
    } _field7;
    struct __CFRunLoop *_field8;
    struct __CFString *_field9;
    int _field10;
};

struct HTTPBodyData;

struct HTTPConnectionCacheKey {
    void **_field1;
    struct __CFAllocator *_field2;
    int _field3;
    unsigned long long _field4;
    struct __CFString *_field5;
    int _field6;
    int _field7;
    struct __CFDictionary *_field8;
    unsigned long long _field9;
    struct __CFDictionary *_field10;
    struct NetworkProxy *_field11;
    struct __CFString *_field12;
    int _field13;
    int _field14;
};

struct HTTPConnectionCacheLimits {
    int _field1;
    int _field2;
    int _field3;
    int _field4;
    int _field5;
    int _field6;
    int _field7;
    int _field8;
    int _field9;
    int _field10;
};

struct HTTPHeaderDict;

struct HTTPMethodMixedValue {
    void **_field1;
    struct __CFString *_field2;
};

struct HTTPParser;

struct HTTPRequestMessage {
    void **_field1;
    void **_field2;
    void **_field3;
    unsigned char _field4;
    struct HTTPVersionMixedValue _field5;
    struct HTTPBodyData *_field6;
    int _field7;
    long long _field8;
    struct _CFHTTPAuthentication *_field9;
    struct _CFHTTPAuthentication *_field10;
    struct HTTPParser *_field11;
    struct HTTPHeaderDict *_field12;
    struct HTTPHeaderDict *_field13;
    void **_field14;
    struct __CFAllocator *_field15;
    struct HTTPMethodMixedValue _field16;
    char *_field17;
    struct __CFURL *_field18;
    char *_field19;
};

struct HTTPVersionMixedValue {
    void **_field1;
    struct __CFString *_field2;
};

struct InterfaceRequiredForLoader;

struct InternalInit {
    id _field1;
    id _field2;
    id _field3;
    id _field4;
    _Bool _field5;
    long long _field6;
};

struct InternalProtocolImplementation {
    long long _field1;
    void *_field2;
    void *_field3;
    void *_field4;
    void *_field5;
    void *_field6;
    void *_field7;
    void *_field8;
    void *_field9;
};

struct MetaConnectionCacheClient {
    void **_field1;
};

struct MetaConnectionOptions {
    int _field1;
    unsigned long long _field2;
    unsigned char _field3;
    unsigned char _field4;
    unsigned char _field5;
};

struct NSCFURLProtocolClient {
    void **_field1;
    void **_field2;
    id _field3;
    id _field4;
};

struct NetworkProxy;

struct PerformanceTiming;

struct RedirectionRecorder;

struct RetainableTypedDict<const CoreSchedulingSet *, TubeManager *>;

struct SessionConnectionLoadable {
    void **_field1;
    long long _field2;
    long long _field3;
    long long _field4;
    long long _field5;
    void **_field6;
    void **_field7;
    id _field8;
};

struct SocketStreamObject;

struct Tube {
    void **_field1;
    struct __CFAllocator *_field2;
    int _field3;
    void **_field4;
    void **_field5;
    struct HTTPConnectionCacheKey *_field6;
    struct BaseTubeManager *_field7;
    struct CoreSchedulingSet *_field8;
    struct BaseAwaitingTube *_field9;
    struct SocketStreamObject *_field10;
    int _field11;
    _Bool _field12;
    struct {
        _Bool _field1;
        unsigned long long _field2;
    } _field13;
    int _field14;
    _Bool _field15;
    _Bool _field16;
    struct __CFArray *_field17;
    struct __SecTrust *_field18;
    struct NetworkProxy *_field19;
    id _field20;
    void _field21;
    id _field22;
    void _field23;
    struct __CFReadStream *_field24;
    struct __CFWriteStream *_field25;
};

struct URLConnectionLoader {
    void **_field1;
    struct __CFAllocator *_field2;
    void **_field3;
    unsigned char _field4;
    unsigned char _field5;
    struct InterfaceRequiredForLoader *_field6;
    struct CoreSchedulingSet *_field7;
    void **_field8;
    void **_field9;
    struct PerformanceTiming *_field10;
    id _field11;
    long long _field12;
    struct RedirectionRecorder *_field13;
    unsigned char _field14;
    unsigned char _field15;
    unsigned char _field16;
    id _field17;
    unsigned char _field18;
    double _field19;
    struct URLProtocol *_field20;
    id _field21;
    unsigned char _field22;
    struct CoreSchedulingSet *_field23;
    double _field24;
    double _field25;
    unsigned long long _field26;
    struct ConfigFlags _field27;
    unsigned char _field28;
    unsigned char _field29;
    unsigned char _field30;
    unsigned char _field31;
};

struct URLProtocol {
    void **_field1;
    void **_field2;
    struct CoreSchedulingSet *_field3;
    double _field4;
    unsigned char _field5;
    unsigned char _field6;
    unsigned char _field7;
    unsigned char _field8;
    unsigned char _field9;
    unsigned char _field10;
    unsigned char _field11;
    unsigned char _field12;
    long long _field13;
    long long _field14;
    struct CFURLProtocolClient *_field15;
    long long _field16;
    unsigned char _field17;
    int _field18;
    long long _field19;
    id _field20;
    struct _CFURLRequest *_field21;
    struct _CFURLRequest *_field22;
    struct URLProtocolClient *_field23;
    struct _CFCachedURLResponse *_field24;
};

struct URLProtocolClient {
    void **_field1;
};

struct UploadProgressInfo {
    long long _field1;
    long long _field2;
    long long _field3;
};

struct XCookieStorage {
    void **_field1;
    struct __CFAllocator *_field2;
    int _field3;
};

struct XCredentialStorage {
    void **_field1;
    struct __CFAllocator *_field2;
    int _field3;
};

struct XTubeManager {
    void **_field1;
    struct __CFAllocator *_field2;
    int _field3;
    struct RetainableTypedDict<const CoreSchedulingSet *, TubeManager *> *_field4;
    struct _opaque_pthread_mutex_t _field5;
    struct HTTPConnectionCacheLimits _field6;
};

struct XURLCache {
    void **_field1;
    struct __CFAllocator *_field2;
    int _field3;
};

struct _CFCachedURLResponse {
    struct __CFRuntimeBase _field1;
    struct __CFCachedURLResponse *_field2;
};

struct _CFHTTPAuthentication;

struct _CFURLCache {
    struct __CFRuntimeBase _field1;
    struct __CFURLCache *_field2;
};

struct _CFURLRequest;

struct __CFAllocator;

struct __CFArray;

struct __CFDictionary;

struct __CFRuntimeBase {
    unsigned long long _field1;
    unsigned char _field2[4];
    unsigned int _field3;
};

struct __CFSet;

struct __CFString;

struct __CFURLCache {
    void **_field1;
    int *_field2;
    id _field3;
    id _field4;
    void _field5;
    long long _field6;
    long long _field7;
    long long _field8;
    long long _field9;
    long long _field10;
    long long _field11;
    long long _field12;
    long long _field13;
    unsigned long long _field14;
    struct __CFString *_field15;
    struct __CFString *_field16;
    struct __CFString *_field17;
    char *_field18;
    _Bool _field19;
    _Bool _field20;
    struct sqlite3 *_field21;
    struct sqlite3 *_field22;
    struct _opaque_pthread_mutex_t _field23;
    struct _opaque_pthread_mutex_t _field24;
    struct CoreLockable *_field25;
    struct CoreLockable *_field26;
    struct CoreLockable *_field27;
    struct sqlite3_stmt *_field28;
    struct sqlite3_stmt *_field29;
    struct sqlite3_stmt *_field30;
    struct sqlite3_stmt *_field31;
    struct sqlite3_stmt *_field32;
    struct sqlite3_stmt *_field33;
    struct sqlite3_stmt *_field34;
    struct sqlite3_stmt *_field35;
    struct sqlite3_stmt *_field36;
    struct sqlite3_stmt *_field37;
    struct sqlite3_stmt *_field38;
    struct sqlite3_stmt *_field39;
    struct sqlite3_stmt *_field40;
    struct sqlite3_stmt *_field41;
    struct unordered_map<int, __CFURLCacheNode *, __CFURLCache__::HashFunc, std::__1::equal_to<int>, std::__1::allocator<std::__1::pair<const int, __CFURLCacheNode *>>> _field42;
    struct deque<__CFURLCacheNode *, std::__1::allocator<__CFURLCacheNode *>> _field43;
    struct __CFRunLoopSource *_field44;
    struct _opaque_pthread_t *_field45;
    struct _opaque_pthread_mutex_t _field46;
    struct _opaque_pthread_mutex_t _field47;
    struct _opaque_pthread_mutex_t _field48;
    struct _opaque_pthread_mutex_t _field49;
    struct _opaque_pthread_mutex_t _field50;
    struct __CFArray *_field51;
    struct __CFArray *_field52;
    _Bool _field53;
    _Bool _field54;
    id _field55;
    id _field56;
    _Bool _field57;
    id _field58;
    struct _CFURLCache *_field59;
    _Bool _field60;
    _Bool _field61;
    int _field62;
    long long _field63;
    long long _field64;
    _Bool _field65;
    struct __asl_object_s *_field66;
    unsigned short _field67;
    long long _field68;
    _Bool _field69;
    _Bool _field70;
    _Bool _field71;
    _Bool _field72;
    long long _field73;
    _Bool _field74;
    _Bool _field75;
    long long _field76;
    id _field77;
    struct __CFSet *_field78;
    struct __CFArray *_field79;
    long long _field80;
    id _field81;
    struct _opaque_pthread_mutex_t _field82;
    struct _opaque_pthread_mutex_t _field83;
    struct __CFDictionary *_field84;
    _Bool _field85;
};

struct __CFURLCacheNode;

struct __hash_node<std::__1::__hash_value_type<int, __CFURLCacheNode *>, void *>;

struct _opaque_pthread_mutex_t {
    long long _field1;
    char _field2[56];
};

struct _opaque_pthread_t;

struct deque<__CFURLCacheNode *, std::__1::allocator<__CFURLCacheNode *>> {
    struct __split_buffer<__CFURLCacheNode **, std::__1::allocator<__CFURLCacheNode **>> {
        struct __CFURLCacheNode ***_field1;
        struct __CFURLCacheNode ***_field2;
        struct __CFURLCacheNode ***_field3;
        struct __compressed_pair<__CFURLCacheNode ***, std::__1::allocator<__CFURLCacheNode **>> {
            struct __CFURLCacheNode ***_field1;
        } _field4;
    } _field1;
    unsigned long long _field2;
    struct __compressed_pair<unsigned long, std::__1::allocator<__CFURLCacheNode *>> {
        unsigned long long _field1;
    } _field3;
};

struct internal_state;

struct sqlite3;

struct sqlite3_stmt;

struct stat {
    int st_dev;
    unsigned short st_mode;
    unsigned short st_nlink;
    unsigned long long st_ino;
    unsigned int st_uid;
    unsigned int st_gid;
    int st_rdev;
    struct timespec st_atimespec;
    struct timespec st_mtimespec;
    struct timespec st_ctimespec;
    struct timespec st_birthtimespec;
    long long st_size;
    long long st_blocks;
    int st_blksize;
    unsigned int st_flags;
    unsigned int st_gen;
    int st_lspare;
    long long st_qspare[2];
};

struct timespec {
    long long tv_sec;
    long long tv_nsec;
};

struct unique_ptr<std::__1::__hash_node<std::__1::__hash_value_type<int, __CFURLCacheNode *>, void *>*[], std::__1::__bucket_list_deallocator<std::__1::allocator<std::__1::__hash_node<std::__1::__hash_value_type<int, __CFURLCacheNode *>, void *>*>>> {
    struct __compressed_pair<std::__1::__hash_node<std::__1::__hash_value_type<int, __CFURLCacheNode *>, void *>**, std::__1::__bucket_list_deallocator<std::__1::allocator<std::__1::__hash_node<std::__1::__hash_value_type<int, __CFURLCacheNode *>, void *>*>>> {
        struct __hash_node<std::__1::__hash_value_type<int, __CFURLCacheNode *>, void *> **_field1;
        struct __bucket_list_deallocator<std::__1::allocator<std::__1::__hash_node<std::__1::__hash_value_type<int, __CFURLCacheNode *>, void *>*>> {
            struct __compressed_pair<unsigned long, std::__1::allocator<std::__1::__hash_node<std::__1::__hash_value_type<int, __CFURLCacheNode *>, void *>*>> {
                unsigned long long _field1;
            } _field1;
        } _field2;
    } _field1;
};

struct unordered_map<int, __CFURLCacheNode *, __CFURLCache__::HashFunc, std::__1::equal_to<int>, std::__1::allocator<std::__1::pair<const int, __CFURLCacheNode *>>> {
    struct __hash_table<std::__1::__hash_value_type<int, __CFURLCacheNode *>, std::__1::__unordered_map_hasher<int, std::__1::__hash_value_type<int, __CFURLCacheNode *>, __CFURLCache__::HashFunc, true>, std::__1::__unordered_map_equal<int, std::__1::__hash_value_type<int, __CFURLCacheNode *>, std::__1::equal_to<int>, true>, std::__1::allocator<std::__1::__hash_value_type<int, __CFURLCacheNode *>>> {
        struct unique_ptr<std::__1::__hash_node<std::__1::__hash_value_type<int, __CFURLCacheNode *>, void *>*[], std::__1::__bucket_list_deallocator<std::__1::allocator<std::__1::__hash_node<std::__1::__hash_value_type<int, __CFURLCacheNode *>, void *>*>>> _field1;
        struct __compressed_pair<std::__1::__hash_node_base<std::__1::__hash_node<std::__1::__hash_value_type<int, __CFURLCacheNode *>, void *>*>, std::__1::allocator<std::__1::__hash_node<std::__1::__hash_value_type<int, __CFURLCacheNode *>, void *>>> {
            struct __hash_node_base<std::__1::__hash_node<std::__1::__hash_value_type<int, __CFURLCacheNode *>, void *>*> {
                struct __hash_node<std::__1::__hash_value_type<int, __CFURLCacheNode *>, void *> *_field1;
            } _field1;
        } _field2;
        struct __compressed_pair<unsigned long, std::__1::__unordered_map_hasher<int, std::__1::__hash_value_type<int, __CFURLCacheNode *>, __CFURLCache__::HashFunc, true>> {
            unsigned long long _field1;
        } _field3;
        struct __compressed_pair<float, std::__1::__unordered_map_equal<int, std::__1::__hash_value_type<int, __CFURLCacheNode *>, std::__1::equal_to<int>, true>> {
            float _field1;
        } _field4;
    } _field1;
};

struct z_stream_s {
    char *next_in;
    unsigned int avail_in;
    unsigned long long total_in;
    char *next_out;
    unsigned int avail_out;
    unsigned long long total_out;
    char *msg;
    struct internal_state *state;
    void *zalloc;
    void *zfree;
    void *opaque;
    int data_type;
    unsigned long long adler;
    unsigned long long reserved;
};

#pragma mark Typedef'd Structures

typedef struct {
    long long _field1;
    int _field2;
} CDStruct_87dc826d;

