/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol NSURLSessionSubclass <NSObject>
- (void)_onqueue_getTasksWithCompletionHandler:(id)arg1;
- (void)_onqueue_resetStorageWithCompletionHandler:(id)arg1;
- (void)_onqueue_completeInvalidation:(_Bool)arg1;
- (void)_onqueue_flushWithCompletionHandler:(id)arg1;
- (id)_streamTaskForHost:(id)arg1 port:(long long)arg2 tls:(_Bool)arg3 completionHandler:(id)arg4;
- (id)_AVAssetDownloadTaskForURL:(id)arg1 destinationURL:(id)arg2 options:(id)arg3;
- (id)downloadTaskForRequest:(id)arg1 downloadFilePath:(id)arg2 resumeData:(id)arg3 completion:(id)arg4;
- (id)uploadTaskForRequest:(id)arg1 uploadFile:(id)arg2 bodyData:(id)arg3 completion:(id)arg4;
- (id)dataTaskForRequest:(id)arg1 completion:(id)arg2;
@end

