/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSObject<OS_dispatch_queue>, NSString;

@interface DADownloadContext : NSObject
{
    NSString *_attachmentUUID;
    NSString *_accountID;
    NSObject<OS_dispatch_queue> *_queue;
    id _progressBlock;
    id _completionBlock;
}

@property(readonly, copy, nonatomic) id completionBlock; // @synthesize completionBlock=_completionBlock;
@property(readonly, copy, nonatomic) id progressBlock; // @synthesize progressBlock=_progressBlock;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(readonly, nonatomic) NSString *accountID; // @synthesize accountID=_accountID;
@property(readonly, nonatomic) NSString *attachmentUUID; // @synthesize attachmentUUID=_attachmentUUID;
- (void).cxx_destruct;
- (void)finishedWithError:(id)arg1;
- (void)updateProgressDownloadedByteCount:(long long)arg1 totalByteCount:(long long)arg2;
- (id)initWithAttachmentUUID:(id)arg1 accountID:(id)arg2 queue:(id)arg3 downloadProgressBlock:(id)arg4 completionBlock:(void)arg5;

@end

