/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface DAECalendarAvailabilityContext : NSObject
{
    id _resultsBlock;
    id _completionBlock;
}

- (void).cxx_destruct;
- (void)finishedWithError:(id)arg1;
- (void)resultsReturned:(id)arg1;
- (id)initWithResultsBlock:(id)arg1 completionBlock:(void)arg2;

@end

