/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <HealthDaemon/HDSampleEntity.h>

@interface HDCategorySampleEntity : HDSampleEntity
{
}

+ (id)_tableValuesFromDataObject:(id)arg1;
+ (id)_propertySettersForDataObject;
+ (Class)_associatedDataObjectClass;
+ (id)_columnsSQL;
+ (id)_databaseTable;
+ (void)load;

@end

