/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol HDSQLiteEntity <NSObject>
+ (void)applyPropertySetters:(id)arg1 toObject:(id)arg2 withProperties:(id)arg3 values:(id *)arg4;
+ (id)associationPropertyForEntityClass:(Class)arg1;
+ (id)databasePropertyToSetClientProperty:(id)arg1;
+ (id)databasePropertyToGetClientProperty:(id)arg1;
+ (id)copyDatabaseDictionaryToSetClientDictionary:(id)arg1;
+ (id)disambiguatedSQLForProperty:(id)arg1;
+ (id)foreignDatabaseTablesToDelete;
+ (id)foreignKeyColumnForTable:(id)arg1;
+ (id)foreignDatabaseTableForProperty:(id)arg1;
+ (id)foreignDatabaseColumnForProperty:(id)arg1;
+ (id)joinClauseForProperty:(id)arg1;
+ (id)disambiguatedDatabaseTable;
+ (id)databaseTable;
+ (id)databaseName;
+ (id)databaseValueForProperty:(id)arg1 clientValue:(id)arg2;
- (void)getValuesForProperties:(id)arg1 withDatabase:(id)arg2 applier:(id)arg3;
- (_Bool)deleteFromDatabase:(id)arg1;
- (id)valueForExternalProperty:(id)arg1;
- (void)setExternalValuesWithDictionary:(id)arg1;
- (_Bool)setValuesWithDictionary:(id)arg1 database:(id)arg2;
- (_Bool)setValue:(id)arg1 forProperty:(id)arg2 database:(id)arg3;
- (void)getValues:(id *)arg1 forProperties:(id *)arg2 count:(unsigned long long)arg3 database:(id)arg4;
- (id)valueForProperty:(id)arg1 database:(id)arg2;
@end

