/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface AXHAListenerHelper : NSObject
{
    void *_listenerAddress;
}

- (void)dealloc;
- (id)initWithListenerAddress:(void *)arg1;

@end

