/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UITableViewCell.h"

@class NSArray, NSString, UIButton, UIImage, UILabel;

@interface PUAdjustmentsModePickerCell : UITableViewCell
{
    UIButton *_accessoryButton;
    UILabel *_displayValueLabel;
    NSArray *_accessoryButtonConstraints;
    NSArray *_displayValueLabelConstraints;
    _Bool _isSubMode;
    NSString *_localizedModeName;
    UIImage *_modeIcon;
    NSString *_currentDisplayValue;
    long long _buttonType;
    id _buttonAction;
}

+ (void)configureModePickerCellLabel:(id)arg1;
@property(copy, nonatomic) id buttonAction; // @synthesize buttonAction=_buttonAction;
@property(nonatomic) long long buttonType; // @synthesize buttonType=_buttonType;
@property(nonatomic) _Bool isSubMode; // @synthesize isSubMode=_isSubMode;
@property(copy, nonatomic) NSString *currentDisplayValue; // @synthesize currentDisplayValue=_currentDisplayValue;
@property(retain, nonatomic) UIImage *modeIcon; // @synthesize modeIcon=_modeIcon;
@property(copy, nonatomic) NSString *localizedModeName; // @synthesize localizedModeName=_localizedModeName;
- (void).cxx_destruct;
- (void)_handleAccessoryButton:(id)arg1;
- (void)_updateDisplayValueLabel;
- (void)_updateButton;
- (void)prepareForReuse;
- (void)updateConstraints;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

