/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UICollectionViewCell.h"

#import "PUPhotoEditLayoutStaticAdaptable-Protocol.h"

@class NSArray, NSString, PUAdjustmentsMode, PUPhotoEditLevelSlider, UILabel;

@interface PUAdjustmentsModeSliderCell : UICollectionViewCell <PUPhotoEditLayoutStaticAdaptable>
{
    UILabel *_titleLabel;
    NSArray *_levelSliderConstraints;
    NSArray *_titleLabelConstraints;
    long long _layoutOrientation;
    PUAdjustmentsMode *_adjustmentsMode;
    NSString *_title;
    PUPhotoEditLevelSlider *_levelSlider;
    double _sliderShortSideLength;
    long long _titleLabelPosition;
}

+ (double)sliderTopMarginVerticalForTitleLabelPosition:(long long)arg1;
@property(nonatomic) long long titleLabelPosition; // @synthesize titleLabelPosition=_titleLabelPosition;
@property(nonatomic) double sliderShortSideLength; // @synthesize sliderShortSideLength=_sliderShortSideLength;
@property(retain, nonatomic) PUPhotoEditLevelSlider *levelSlider; // @synthesize levelSlider=_levelSlider;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) PUAdjustmentsMode *adjustmentsMode; // @synthesize adjustmentsMode=_adjustmentsMode;
@property(readonly, nonatomic) long long layoutOrientation; // @synthesize layoutOrientation=_layoutOrientation;
- (void).cxx_destruct;
- (void)_updateTitleLabel;
- (void)setupWithLayoutOrientation:(long long)arg1;
- (void)updateConstraints;
- (id)initWithFrame:(struct CGRect)arg1;

@end

