/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSArray;

@interface PUEditPluginManager : NSObject
{
    long long _mediaType;
    NSArray *__plugins;
}

+ (id)sharedManagerForMediaType:(long long)arg1;
@property(copy, nonatomic, setter=_setPlugins:) NSArray *_plugins; // @synthesize _plugins=__plugins;
@property(readonly) long long mediaType; // @synthesize mediaType=_mediaType;
- (void).cxx_destruct;
- (id)userDefaultsIdentifier;
- (id)pluginActivities;
- (void)rediscoverAvailablePlugins;
- (_Bool)hasPlugins;
- (id)_initWithMediaType:(long long)arg1;

@end

