/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "PUEditPluginHostViewControllerDataSource-Protocol.h"
#import "PUEditPluginHostViewControllerDelegate-Protocol.h"
#import "UIActivityGroupViewControllerDelegate-Protocol.h"
#import "UINavigationControllerDelegate-Protocol.h"

@class PHAsset, PUEditPlugin, PUEditPluginManager, UINavigationController, UIViewController;

@interface PUEditPluginSession : NSObject <PUEditPluginHostViewControllerDataSource, PUEditPluginHostViewControllerDelegate, UINavigationControllerDelegate, UIActivityGroupViewControllerDelegate>
{
    PUEditPluginManager *_pluginManager;
    UINavigationController *_pluginNavigationController;
    PUEditPlugin *_currentPlugin;
    _Bool _isAvailable;
    id <PUEditPluginSessionDataSource> _dataSource;
    id <PUEditPluginSessionDelegate> _delegate;
    PHAsset *_asset;
    long long _adjustmentType;
    UIViewController *__hostViewController;
}

@property(retain, nonatomic, setter=_setHostViewController:) UIViewController *_hostViewController; // @synthesize _hostViewController=__hostViewController;
- (void)_setAdjustmentType:(long long)arg1;
@property(nonatomic) long long adjustmentType; // @synthesize adjustmentType=_adjustmentType;
- (void)_setAsset:(id)arg1;
@property(retain, nonatomic) PHAsset *asset; // @synthesize asset=_asset;
@property(nonatomic) _Bool isAvailable; // @synthesize isAvailable=_isAvailable;
@property(nonatomic) __weak id <PUEditPluginSessionDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak id <PUEditPluginSessionDataSource> dataSource; // @synthesize dataSource=_dataSource;
- (void).cxx_destruct;
- (id)navigationController:(id)arg1 animationControllerForOperation:(long long)arg2 fromViewController:(id)arg3 toViewController:(id)arg4;
- (void)editPluginHostViewController:(id)arg1 didFinishWithSuccess:(_Bool)arg2;
- (void)editPluginHostViewController:(id)arg1 commitContentEditingOutput:(id)arg2 withCompletionHandler:(id)arg3;
- (void)editPluginHostViewController:(id)arg1 loadItemProviderWithHandler:(id)arg2;
- (void)activityGroupViewController:(id)arg1 didSelectActivity:(id)arg2;
- (void)dismissSession;
- (void)beginSessionWithAsset:(id)arg1 fromViewController:(id)arg2 sourceElement:(id)arg3;
- (void)_setIsAvailable:(_Bool)arg1;
- (void)_updateAvailability;
- (void)_pluginManagerPluginsDidChange:(id)arg1;
- (void)loadItemProviderWithSupportedAdjustmentData:(id)arg1 loadHandler:(id)arg2;
@property(readonly, nonatomic) long long mediaType;
- (void)dealloc;
- (id)init;

@end

