/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIView.h"

@class UIImageView, UILabel;

@interface PUFeedTextCellContentView : UIView
{
    UILabel *label;
    UILabel *detailLabel;
    UIImageView *iconImageView;
}

@property(retain, nonatomic) UIImageView *iconImageView; // @synthesize iconImageView;
@property(retain, nonatomic) UILabel *detailLabel; // @synthesize detailLabel;
@property(retain, nonatomic) UILabel *label; // @synthesize label;
- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;

@end

