/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <PhotosUI/PUViewControllerSpec.h>

@interface PUPhotoEditViewControllerSpec : PUViewControllerSpec
{
}

@property(readonly, nonatomic) _Bool shouldDisplayExtensionButtonInToolbar;
@property(readonly, nonatomic) _Bool shouldDisplaySecondaryToolButtonsInToolbar;
@property(readonly, nonatomic) double toolbarLongSideMargin;
@property(readonly, nonatomic) struct UIEdgeInsets previewViewInsetsLandscape;
@property(readonly, nonatomic) struct UIEdgeInsets previewViewInsetsPortrait;

@end

