/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

@protocol PUPhotosSharingTransitionDelegate
- (void)photosSharingTransition:(id)arg1 willAnimatePresent:(_Bool)arg2;
- (id)photosSharingTransition:(id)arg1 viewForTransitionWithAssetCollectionsDataSource:(id)arg2;
- (void)photosSharingTransition:(id)arg1 setVisibility:(_Bool)arg2 forKeyAssetIndexPath:(id)arg3 inAssetCollectionsDataSource:(id)arg4;
- (struct CGPoint)photosSharingTransition:(id)arg1 contentOffsetForKeyAssetIndexPath:(id)arg2 inAssetCollectionsDataSource:(id)arg3;
- (id)photosSharingTransition:(id)arg1 layoutForKeyAssetIndexPath:(id)arg2 inAssetCollectionsDataSource:(id)arg3;
@end

