/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface PUPhotosSharingViewControllerSpec : NSObject
{
}

- (_Bool)embedsActivityViewForBounds:(struct CGRect)arg1 horizontalSizeClass:(long long)arg2 verticalSizeClass:(long long)arg3;
- (struct UIEdgeInsets)collectionViewLayoutContentInsetForBounds:(struct CGRect)arg1;
@property(readonly, nonatomic) unsigned long long selectionBadgeCorner;
@property(readonly, nonatomic) struct UIOffset selectionBadgeOffset;
@property(readonly, nonatomic) struct CGSize selectionBadgeSize;
@property(readonly, nonatomic) double interItemSpacing;
- (_Bool)maximizeImageHeightForBounds:(struct CGRect)arg1;
- (int)zoomingImageFormatForBounds:(struct CGRect)arg1;
- (int)qualityImageFormatForBounds:(struct CGRect)arg1;
- (int)fastImageFormatForBounds:(struct CGRect)arg1;

@end

