/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMapTable, NSMutableSet, NSOrderedSet, NSSet;

@interface PUPhotoSelectionManager : NSObject
{
    NSMapTable *_selectionEntriesByAssetCollection;
    NSMutableSet *_uniqueAssetSelection;
    long long _selectionChangeCount;
    long long _options;
    id <PUPhotoSelectionManagerDelegate> _delegate;
    id <PUPhotoSelectionManagerDataSource> _datasource;
}

@property(nonatomic) __weak id <PUPhotoSelectionManagerDataSource> datasource; // @synthesize datasource=_datasource;
@property(nonatomic) __weak id <PUPhotoSelectionManagerDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) long long options; // @synthesize options=_options;
- (void).cxx_destruct;
- (_Bool)_shouldUniqueAssets;
- (void)_endSelectionChange;
- (void)_beginSelectionChange;
- (void)invalidateAllAssetIndexes;
- (void)handleChange:(id)arg1;
- (id)localizedSelectionString;
@property(readonly, nonatomic) NSOrderedSet *orderedSelectedAssets;
@property(readonly, nonatomic) NSSet *selectedAssets;
- (id)selectedAssetsWithAssetCollectionOrdering:(id)arg1;
- (void)enumerateSelectedAssetsWithAssetCollectionOrdering:(id)arg1 block:(id)arg2;
- (id)selectedAssetIndexesWithAssetCollectionOrdering:(id)arg1;
- (_Bool)areAllAssetsSelectedInAssetCollections:(id)arg1;
- (_Bool)areAllAssetsSelectedInAssetCollection:(id)arg1;
- (_Bool)isAnyAssetSelectedInAssetCollections:(id)arg1;
- (_Bool)isAnyAssetSelectedInAssetCollection:(id)arg1;
- (_Bool)isAssetAtIndexSelected:(unsigned long long)arg1 inAssetCollection:(id)arg2;
- (void)deselectAllAssets;
- (void)deselectAllAssetsInAssetCollections:(id)arg1;
- (void)deselectAssetsAtIndexes:(id)arg1 inAssetCollection:(id)arg2;
- (void)deselectAssetAtIndex:(unsigned long long)arg1 inAssetCollection:(id)arg2;
- (void)selectAllAssetsInAssetCollections:(id)arg1;
- (void)selectAssetsAtIndexes:(id)arg1 inAssetCollection:(id)arg2;
- (void)selectAssetAtIndex:(unsigned long long)arg1 inAssetCollection:(id)arg2;
- (id)_selectionEntryForAssetCollection:(id)arg1 createIfNeeded:(_Bool)arg2;
- (id)initWithOptions:(long long)arg1;
- (id)init;

@end

