/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UICollectionViewFlowLayout.h"

@interface PUSlidersCollectionViewLayout : UICollectionViewFlowLayout
{
    double _rowHeight;
}

@property(nonatomic) double rowHeight; // @synthesize rowHeight=_rowHeight;
- (void)prepareLayout;

@end

