/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UITabBarController.h"

#import "PLAssetContainerListChangeObserver-Protocol.h"
#import "PLAssetContainerObserver-Protocol.h"
#import "PLDismissableViewController-Protocol.h"
#import "PLInvitationRecordsObserver-Protocol.h"
#import "PLRootLibraryNavigationController-Protocol.h"
#import "UINavigationControllerDelegate-Protocol.h"

@class NSDictionary, NSMutableIndexSet, PUMomentsZoomLevelManager, PUSessionInfo, PUTabbedLibraryViewControllerSpec, UINavigationController;

@interface PUTabbedLibraryViewController : UITabBarController <PLAssetContainerListChangeObserver, PLAssetContainerObserver, PLInvitationRecordsObserver, PLDismissableViewController, PLRootLibraryNavigationController, UINavigationControllerDelegate>
{
    PUTabbedLibraryViewControllerSpec *_spec;
    PUSessionInfo *_sessionInfo;
    int _pendingSelectedContentMode;
    _Bool _sharedTabBadgeIsDirty;
    NSDictionary *_filteredAlbumListsByContentMode;
    PUMomentsZoomLevelManager *_zoomLevelManager;
    NSMutableIndexSet *_everDisplayedContentModes;
}

+ (void)initialize;
@property(retain, nonatomic) PUSessionInfo *sessionInfo; // @synthesize sessionInfo=_sessionInfo;
- (void).cxx_destruct;
- (void)prepareForDefaultImageSnapshot;
- (_Bool)prepareForDismissingForced:(_Bool)arg1;
- (id)navigationController:(id)arg1 animationControllerForOperation:(long long)arg2 fromViewController:(id)arg3 toViewController:(id)arg4;
- (id)navigationController:(id)arg1 interactionControllerForAnimationController:(id)arg2;
- (Class)_navigationControllerLayoutTransitioningClass:(id)arg1;
- (_Bool)_navigationControllerShouldUseBuiltinInteractionController:(id)arg1;
- (_Bool)_navigationControllerShouldCrossFadeBottomBars:(id)arg1;
- (void)navigationController:(id)arg1 didShowViewController:(id)arg2 animated:(_Bool)arg3;
- (void)navigationController:(id)arg1 willShowViewController:(id)arg2 animated:(_Bool)arg3;
- (id)_nextCloudFeedNavigatingObject;
- (_Bool)cloudFeedInvitationForAlbumIsAvailableForNavigation:(id)arg1;
- (_Bool)cloudFeedCommentIsAvailableForNavigation:(id)arg1;
- (_Bool)cloudFeedAssetIsAvailableForNavigation:(id)arg1;
- (_Bool)commentIsAvailableForNavigation:(id)arg1 inAsset:(id)arg2;
- (_Bool)assetIsAvailableForNavigation:(id)arg1 inAlbum:(struct NSObject *)arg2;
- (struct NSObject *)_availableAlbumToNavigateToAsset:(id)arg1 preferredAlbum:(struct NSObject *)arg2;
- (_Bool)cloudFeedIsAvailableForNavigation;
- (_Bool)albumIsAvailableForNavigation:(struct NSObject *)arg1;
- (_Bool)contentModeIsAvailableForNavigation:(int)arg1;
- (_Bool)_navigateToRootOfCurrentTabAnimated:(_Bool)arg1;
- (void)navigateToRevealCloudFeedInvitationForAlbum:(id)arg1 completion:(id)arg2;
- (void)navigateToCloudFeedComment:(id)arg1 completion:(id)arg2;
- (void)navigateToRevealCloudFeedComment:(id)arg1 completion:(id)arg2;
- (void)navigateToCloudFeedAsset:(id)arg1 completion:(id)arg2;
- (void)navigateToRevealCloudFeedAsset:(id)arg1 completion:(id)arg2;
- (void)navigateToCloudFeedWithCompletion:(id)arg1;
- (void)navigateToAsset:(id)arg1 animated:(_Bool)arg2;
- (void)navigateToContentMode:(int)arg1 animated:(_Bool)arg2 completion:(id)arg3;
- (void)navigateToComment:(id)arg1 forAsset:(id)arg2 animated:(_Bool)arg3;
- (void)navigateToRevealAsset:(id)arg1 inAlbum:(struct NSObject *)arg2 animated:(_Bool)arg3;
- (void)navigateToAsset:(id)arg1 inAlbum:(struct NSObject *)arg2 animated:(_Bool)arg3;
- (void)_navigateToAsset:(id)arg1 andPerformAction:(int)arg2 inAlbum:(struct NSObject *)arg3 animated:(_Bool)arg4;
- (void)navigateToRevealAlbum:(struct NSObject *)arg1 initiallyHidden:(_Bool)arg2 animated:(_Bool)arg3;
- (void)navigateToAlbum:(struct NSObject *)arg1 animated:(_Bool)arg2 completion:(id)arg3;
- (void)_navigateToAlbum:(struct NSObject *)arg1 andPerformAction:(int)arg2 initiallyHidden:(_Bool)arg3 animated:(_Bool)arg4 completion:(id)arg5;
- (_Bool)_navigateToDefaultLocationInNavigationController:(id)arg1 animated:(_Bool)arg2;
- (void)navigateToInitialLocationInNavigationController:(id)arg1;
- (void)_enumerateViewControllersWithBlock:(id)arg1;
- (void)_didFinishPostingNotifications:(id)arg1;
- (void)invitationRecordsDidChange:(id)arg1;
- (void)assetContainerDidChange:(id)arg1;
- (void)assetContainerListDidChange:(id)arg1;
- (void)_libraryDidChange:(id)arg1;
- (void)_applicationWillEnterForeground:(id)arg1;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)_updateSharedStreamsTabBadge;
- (void)updateDisplayedTabsAnimated:(_Bool)arg1;
- (_Bool)_isNavigationControllerBadged:(id)arg1;
- (id)_navigationControllerForContentMode:(int)arg1;
- (id)newRootViewControllerForContentMode:(int)arg1;
- (id)_newNavigationControllerWithRootController:(id)arg1;
- (id)_existingNavigationControllerForContentMode:(int)arg1;
- (void)setSelectedViewController:(id)arg1;
@property(nonatomic) int selectedContentMode;
- (_Bool)shouldShowTabForContentMode:(int)arg1;
@property(readonly, nonatomic) UINavigationController *selectedNavigationController;
- (int)_contentModeForNavigationController:(id)arg1;
- (int)_contentModeForAlbum:(struct NSObject *)arg1;
- (struct NSObject *)_albumListForContentMode:(int)arg1;
- (_Bool)pu_shouldSelectViewController:(id)arg1;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)dealloc;
- (id)initWithSpec:(id)arg1;

@end

