/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIPasteboard.h"

@interface UIPasteboard (PhotosUI)
- (_Bool)pu_containsAssets;
- (id)pu_assets;
- (void)pu_setAssets:(id)arg1;
- (void)pu_setAsset:(id)arg1;
- (id)pu_newPasteboardRepresentationForAsset:(id)arg1;
@end

