/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableDictionary, NSObject<OS_dispatch_queue>, NSOperationQueue;

@interface MSVImageResizeUtility : NSObject
{
    NSObject<OS_dispatch_queue> *_imageResizingAccessQueue;
    NSOperationQueue *_imageResizingOperationQueue;
    NSMutableDictionary *_imageResizingOperations;
}

@property(retain, nonatomic) NSMutableDictionary *imageResizingOperations; // @synthesize imageResizingOperations=_imageResizingOperations;
@property(retain, nonatomic) NSOperationQueue *imageResizingOperationQueue; // @synthesize imageResizingOperationQueue=_imageResizingOperationQueue;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *imageResizingAccessQueue; // @synthesize imageResizingAccessQueue=_imageResizingAccessQueue;
- (void).cxx_destruct;
@property(nonatomic) long long maxConcurrentOperationCount;
- (void)cancelResizeImage:(id)arg1;
- (id)resizeImageAtSourceURL:(id)arg1 destinationSize:(struct CGSize)arg2 destinationURL:(id)arg3 completionHandler:(id)arg4;
- (id)init;

@end

