/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <ITMLKit/IKViewElement.h>

@class IKAudioElement, NSArray, UIColor;

@interface IKBackgroundElement : IKViewElement
{
}

@property(readonly, retain, nonatomic) UIColor *backgroundColor;
@property(readonly, nonatomic) double transitionInterval;
@property(readonly, retain, nonatomic) IKAudioElement *audio;
@property(readonly, retain, nonatomic) NSArray *images;

@end

