/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <ITMLKit/IKDOMCharacterData.h>

#import "IKJSDOMText-Protocol.h"

@interface IKDOMText : IKDOMCharacterData <IKJSDOMText>
{
}

- (void)setTextContent:(id)arg1;
- (id)textContent;
- (id)nodeValue;
- (long long)nodeType;
- (id)nodeName;

@end

