/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <ITMLKit/IKViewElement.h>

@class IKBackgroundElement, IKDocumentBannerElement, IKGridElement;

@interface IKGalleryTemplate : IKViewElement
{
}

@property(readonly, retain, nonatomic) IKGridElement *grid;
@property(readonly, retain, nonatomic) IKDocumentBannerElement *documentBanner;
@property(readonly, retain, nonatomic) IKBackgroundElement *background;

@end

