/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "JSExport-Protocol.h"

@class NSString;

@protocol IKJSITunesStore <JSExport>
@property(retain, nonatomic) id cookie;
@property(retain, nonatomic) NSString *cookieURL;
@property(retain, nonatomic) NSString *storefront;
@property(readonly, nonatomic) NSString *networkConnectionType;
@property(readonly, nonatomic) NSString *userAgent;
@property(readonly, nonatomic) NSString *DSID;
- (void)evaluateScripts:(id)arg1:(id)arg2;
- (void)loadStoreContent:(id)arg1:(id)arg2;
- (void)clearCookies;
- (void)recordEvent:(id)arg1:(id)arg2;
- (id)makeStoreXMLHttpRequest;
- (id)getBag;
@end

