/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "JSExport-Protocol.h"

@class IKDOMElement, IKDOMImplementation, NSString;

@protocol IKJSDOMDocument <JSExport>
@property(retain, nonatomic) NSString *documentURI;
@property(nonatomic) _Bool strictErrorChecking;
@property(retain, nonatomic) NSString *xmlVersion;
@property(nonatomic) _Bool xmlStandalone;
@property(readonly, retain, nonatomic) NSString *xmlEncoding;
@property(readonly, retain, nonatomic) NSString *inputEncoding;
@property(readonly, retain, nonatomic) IKDOMElement *documentElement;
@property(readonly, nonatomic) __weak IKDOMImplementation *implementation;
- (void)replace:(id)arg1;
- (void)setNeedsUpdate;
- (id)adoptNode:(id)arg1;
- (id)getElementById:(id)arg1;
- (id)getElementsByTagName:(id)arg1;
- (id)createComment:(id)arg1;
- (id)createTextNode:(id)arg1;
- (id)createDocumentFragment;
- (id)createElement:(id)arg1;
@end

