/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "JSExport-Protocol.h"

@protocol IKJSDOMNodeList <JSExport>
@property(readonly, nonatomic) long long length;
- (id)item:(long long)arg1;
@end

