/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <ITMLKit/IKViewElement.h>

@class NSArray;

@interface IKMediaElement : IKViewElement
{
}

@property(readonly, nonatomic) IKViewElement *relatedContent;
@property(readonly, retain, nonatomic) NSArray *assets;
@property(readonly, nonatomic) unsigned long long scrubBehavior;

@end

