/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCacheDelegate-Protocol.h"

@interface IKRestrictionsUtilities : NSObject <NSCacheDelegate>
{
}

+ (id)orderedRankingsInDomain:(id)arg1 countryCode:(id)arg2;
+ (id)ratingForRestrictionRanking:(id)arg1 inDomain:(id)arg2 countryCode:(id)arg3;
+ (id)_purgableRatingsDictionary;
- (void)cache:(id)arg1 willEvictObject:(id)arg2;

@end

