/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <HealthKit/HKQuery.h>

#import "HKCorrelationQueryClient-Protocol.h"

@class NSArray, NSPredicate, NSSet, _HKFilter;

@interface HKCorrelationQuery : HKQuery <HKCorrelationQueryClient>
{
    NSSet *_types;
    NSPredicate *_samplePredicate;
    _HKFilter *_dataFilter;
    id _completionHandler;
}

+ (void)_configureServerInterface:(id)arg1;
+ (void)_configureClientInterface:(id)arg1;
+ (id)_serverInterfaceProtocol;
+ (id)_clientInterfaceProtocol;
- (void).cxx_destruct;
- (id)_predicateFilterClasses;
- (void)_deliverError:(id)arg1;
- (void)_validate;
- (void)_requestServerProxyWithUUID:(id)arg1 connection:(id)arg2 handler:(id)arg3;
- (void)_prepareToActivateWithServerProxy:(id)arg1 isReactivation:(_Bool)arg2;
- (void)deliverCorrelations:(id)arg1 forQuery:(id)arg2;
@property(readonly) NSPredicate *samplePredicate;
@property(readonly) NSArray *types;
- (id)initWithTypes:(id)arg1 predicate:(id)arg2 samplePredicate:(id)arg3 completion:(id)arg4;

@end

