/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol HKQueryServer <NSObject>
- (void)deactivateServer;
- (void)activateServerWithCompletion:(id)arg1;
- (void)setQueryDataType:(id)arg1 filter:(id)arg2 shouldListenForUpdates:(_Bool)arg3;
@end

