/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <HealthKit/HKObject.h>

@class HKSampleType, NSDate;

@interface HKSample : HKObject
{
    HKSampleType *_sampleType;
    NSDate *_startDate;
    NSDate *_endDate;
}

+ (_Bool)supportsSecureCoding;
+ (id)_newSampleWithType:(id)arg1 startDate:(id)arg2 endDate:(id)arg3 metadata:(id)arg4 config:(id)arg5;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)description;
- (void)_setEndDate:(id)arg1;
@property(readonly) NSDate *endDate;
- (void)_setStartDate:(id)arg1;
@property(readonly) NSDate *startDate;
@property(readonly) HKSampleType *sampleType;
- (void)_setSampleType:(id)arg1;
- (void)validate;

@end

