/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <HealthKit/HKQuery.h>

#import "HKStatisticsQueryClient-Protocol.h"

@interface HKStatisticsQuery : HKQuery <HKStatisticsQueryClient>
{
    unsigned long long _options;
    id _completionHandler;
}

+ (void)_configureClientInterface:(id)arg1;
+ (id)_serverInterfaceProtocol;
+ (id)_clientInterfaceProtocol;
@property(copy, nonatomic) id completionHandler; // @synthesize completionHandler=_completionHandler;
@property(nonatomic) unsigned long long options; // @synthesize options=_options;
- (void).cxx_destruct;
- (void)deliverStatistics:(id)arg1 forQuery:(id)arg2;
- (void)_deliverError:(id)arg1;
- (void)_validate;
- (void)_cleanupAfterDeactivation;
- (void)_prepareToActivateWithServerProxy:(id)arg1 isReactivation:(_Bool)arg2;
- (void)_requestServerProxyWithUUID:(id)arg1 connection:(id)arg2 handler:(id)arg3;
- (id)initWithQuantityType:(id)arg1 quantitySamplePredicate:(id)arg2 options:(unsigned long long)arg3 completionHandler:(id)arg4;

@end

