/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <CoreFoundation/NSSharedKeySet.h>

// Not exported
@interface NSStringROMKeySet_Embedded : NSSharedKeySet
{
}

- (unsigned long long)indexForCString:(const char *)arg1 length:(unsigned long long)arg2 key:(const struct __CFString **)arg3;
- (_Bool)isEmpty;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithKeys:(id *)arg1 count:(unsigned long long)arg2;
- (void)finalize;
- (void)dealloc;
- (id)init;

@end

