/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

@protocol CHLoggerProtocol
- (void)logDebug:(id)arg1;
- (void)logInfo:(id)arg1;
- (void)logNotice:(id)arg1;
- (void)logWarn:(id)arg1;
- (void)logError:(id)arg1;
@end

