/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <CoreData/NSPersistentStoreResult.h>

@class NSArray;

// Not exported
@interface NSUnknownRequestTypeResult : NSPersistentStoreResult
{
    NSArray *_subresults;
}

@property(readonly) NSArray *subresults; // @synthesize subresults=_subresults;
- (void)dealloc;
- (id)initWithSubresults:(id)arg1;

@end

