/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "AAUIFamilySetupDelegate-Protocol.h"
#import "SKComposeReviewDelegate-Protocol.h"
#import "UIPopoverControllerDelegate-Protocol.h"

@class NSArray, NSMutableArray, SKUIClientContext, SKUIOverlayContainerViewController, UINavigationController, UIViewController;

@interface SKUIModalDocumentController : NSObject <AAUIFamilySetupDelegate, SKComposeReviewDelegate, UIPopoverControllerDelegate>
{
    SKUIClientContext *_clientContext;
    NSMutableArray *_composeReviewViewControllers;
    id <SKUIModalSourceViewProvider> _modalSourceViewProvider;
    UINavigationController *_overlayNavigationController;
    SKUIOverlayContainerViewController *_overlayViewController;
    id <UINavigationControllerDelegate> _navigationControllerDelegate;
    NSMutableArray *_popoverControllers;
    UIViewController *_rootViewController;
    NSMutableArray *_stackItems;
}

@property(retain, nonatomic) UIViewController *rootViewController; // @synthesize rootViewController=_rootViewController;
@property(nonatomic) __weak id <UINavigationControllerDelegate> navigationControllerDelegate; // @synthesize navigationControllerDelegate=_navigationControllerDelegate;
@property(nonatomic) __weak id <SKUIModalSourceViewProvider> modalSourceViewProvider; // @synthesize modalSourceViewProvider=_modalSourceViewProvider;
@property(retain, nonatomic) SKUIClientContext *clientContext; // @synthesize clientContext=_clientContext;
- (void).cxx_destruct;
- (void)_unloadDocumentForViewController:(id)arg1;
- (id)_showOverlayContainerViewController;
- (void)_pushWriteAReviewDocument:(id)arg1 viewController:(id)arg2;
- (void)_pushSheetStackItem:(id)arg1;
- (void)_pushSheetDocument:(id)arg1 viewController:(id)arg2;
- (void)_pushRedeemDocument:(id)arg1 options:(id)arg2;
- (void)_pushPopoverStackItem:(id)arg1;
- (void)_pushOverlayStackItem:(id)arg1;
- (void)_pushGiftDocument:(id)arg1 options:(id)arg2;
- (void)_pushFamilySetupDocument:(id)arg1 options:(id)arg2;
- (void)_pushDialogDocument:(id)arg1 options:(id)arg2;
- (void)_pushCharityDocument:(id)arg1 options:(id)arg2;
- (void)_presentOverlayViewControllersFromNavigationController:(id)arg1;
- (id)_presenterViewController;
- (void)_popPopoverStackItem:(id)arg1 animated:(_Bool)arg2;
- (void)_popOverlayStackItem:(id)arg1 animated:(_Bool)arg2;
- (void)_popDocument:(_Bool)arg1;
- (id)_overlayStackItems;
- (void)_dismissOverlayControllerWithStackItem:(id)arg1 animated:(_Bool)arg2;
- (void)_overlayControllerBackstopAction:(id)arg1;
- (void)popoverControllerDidDismissPopover:(id)arg1;
- (void)reviewComposeViewControllerDidFinish:(id)arg1;
- (void)familySetupViewController:(id)arg1 didCompleteWithSuccess:(_Bool)arg2;
- (void)setOverlayNavigationController:(id)arg1 withTransitionCoordinator:(id)arg2;
- (void)pushDocument:(id)arg1 options:(id)arg2;
- (void)popToDocument:(id)arg1;
- (void)popDocument;
- (void)popAllDocuments;
- (void)presentOverlayViewControllersFromNavigationController:(id)arg1;
@property(readonly, nonatomic) NSArray *documents;
- (void)dealloc;
- (id)init;

@end

