/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSCache, NSNumber, NSOperationQueue, SKUIClientContext, SSFamilyCircle;

@interface SKUIFamilyCircleController : NSObject
{
    SSFamilyCircle *_familyCircle;
    NSNumber *_lastAccountID;
    NSCache *_imageCache;
    NSOperationQueue *_opQueue;
    _Bool _sharedPurchasesEnabled;
    SKUIClientContext *_clientContext;
}

+ (id)sharedController;
@property(retain, nonatomic) SKUIClientContext *clientContext; // @synthesize clientContext=_clientContext;
@property(readonly, nonatomic) SSFamilyCircle *familyCircle; // @synthesize familyCircle=_familyCircle;
- (void).cxx_destruct;
- (void)_setProfilePicture:(id)arg1 forMember:(id)arg2;
- (void)_setFamilyCircleResponse:(id)arg1 error:(id)arg2;
- (void)_accountStoreDidChange:(id)arg1;
- (id)profilePictureForFamilyMember:(id)arg1;
- (void)reloadData;
- (void)dealloc;
- (id)init;

@end

