/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UITabBarController.h"

#import "SKUIMoreNavigationControllerDelegate-Protocol.h"

@class SKUIFloatingOverlayView, SKUITabBarBackgroundView, UIViewController;

@interface SKUITabBarController : UITabBarController <SKUIMoreNavigationControllerDelegate>
{
    SKUIFloatingOverlayView *_floatingOverlayView;
    UIViewController *_floatingOverlayViewController;
    SKUITabBarBackgroundView *_tabBarBackgroundView;
}

+ (Class)_moreNavigationControllerClass;
@property(readonly, nonatomic) UIViewController *floatingOverlayViewController; // @synthesize floatingOverlayViewController=_floatingOverlayViewController;
- (void).cxx_destruct;
- (void)_layoutFloatingOverlayView;
- (void)moreNavigationController:(id)arg1 didSelectItemAtIndex:(long long)arg2;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)viewDidLayoutSubviews;
- (void)setTransientViewController:(id)arg1 animated:(_Bool)arg2;
- (id)moreNavigationController;
- (void)cancelTransientViewController:(id)arg1;
- (void)setTabBarBackdropStyle:(long long)arg1;
- (void)setFloatingOverlayViewController:(id)arg1 animated:(_Bool)arg2;
- (id)init;

@end

