/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <StoreKitUI/SKUIStorePageSection.h>

@class SKUIColorScheme, SKUIEditorialComponent, SKUIEditorialLayout;

@interface SKUIEditorialPageSection : SKUIStorePageSection
{
    SKUIColorScheme *_colorScheme;
    SKUIEditorialLayout *_editorialLayout;
    _Bool _isExpanded;
}

- (void).cxx_destruct;
- (id)_editorialLayout;
- (void)willTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)willAppearInContext:(id)arg1;
@property(retain, nonatomic) SKUIEditorialComponent *pageComponent; // @dynamic pageComponent;
- (long long)numberOfCells;
- (void)collectionViewDidSelectItemAtIndexPath:(id)arg1;
- (struct CGSize)cellSizeForIndexPath:(id)arg1;
- (id)cellForIndexPath:(id)arg1;
- (id)initWithPageComponent:(id)arg1;

@end

