/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class IKAppDocument, NSDictionary, NSString, UIViewController;

@interface SKUIDocumentStackItem : NSObject
{
    IKAppDocument *_document;
    NSDictionary *_presentationOptions;
    _Bool _usesNavigationControllerForModalPresentation;
    UIViewController *_viewController;
}

@property(retain, nonatomic) UIViewController *viewController; // @synthesize viewController=_viewController;
@property(nonatomic) _Bool usesNavigationControllerForModalPresentation; // @synthesize usesNavigationControllerForModalPresentation=_usesNavigationControllerForModalPresentation;
@property(readonly, nonatomic) NSDictionary *presentationOptions; // @synthesize presentationOptions=_presentationOptions;
@property(readonly, nonatomic) IKAppDocument *document; // @synthesize document=_document;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *sourceElementIdentifier;
@property(readonly, nonatomic) NSString *presentationType;
@property(readonly, nonatomic, getter=isAnimated) _Bool animated;
- (id)initWithDocument:(id)arg1 presentationOptions:(id)arg2;

@end

