/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "PKAddPassesViewControllerDelegate-Protocol.h"

@class NSOperationQueue, SKUIClientContext;

@interface SKUIPassbookLoader : NSObject <PKAddPassesViewControllerDelegate>
{
    SKUIClientContext *_clientContext;
    id <SKUIPassbookLoaderDelegate> _delegate;
    long long _loadCount;
    NSOperationQueue *_operationQueue;
}

@property(retain, nonatomic) NSOperationQueue *operationQueue; // @synthesize operationQueue=_operationQueue;
@property(nonatomic) __weak id <SKUIPassbookLoaderDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_sendDidFinishIfFinished;
- (void)_loadPassWithURL:(id)arg1;
- (void)_didLoadWithPass:(id)arg1 error:(id)arg2;
- (void)addPassesViewControllerDidFinish:(id)arg1;
- (void)loadPassWithURL:(id)arg1;
- (id)initWithClientContext:(id)arg1;

@end

