/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "SKUILibraryInterface-Protocol.h"

@interface SKUIMediaLibraryInterface : NSObject <SKUILibraryInterface>
{
}

- (unsigned long long)_AVTypesForMediaItem:(id)arg1;
- (id)stateForLibraryItem:(id)arg1;
- (_Bool)performActionForLibraryItem:(id)arg1;
- (void)enumerateStatesForLibraryItems:(id)arg1 usingBlock:(id)arg2;

@end

