/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIView.h"

@class SKUITrendingSearchPage, SKUITrendingSearchPageView, UIScrollView;

@interface SKUIIPhoneTrendingSearchPageView : UIView
{
    SKUITrendingSearchPageView *_view;
    UIScrollView *_scrollView;
}

@property(readonly, nonatomic) SKUITrendingSearchPageView *trendingSearchPageView; // @synthesize trendingSearchPageView=_view;
- (void).cxx_destruct;
- (void)layoutSubviews;
@property(nonatomic) __weak id <SKUITrendingSearchPageViewDelegate> delegate;
@property(retain, nonatomic) SKUITrendingSearchPage *page;
- (id)initWithFrame:(struct CGRect)arg1;

@end

