/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

@protocol CADCalendarInterface
- (void)CADDatabaseDeleteCalendar:(CDStruct_f683c4ba)arg1 forEntityType:(int)arg2 error:(id)arg3;
- (void)CADCalendar:(CDStruct_f683c4ba)arg1 hasReminders:(id)arg2;
- (void)CADCalendar:(CDStruct_f683c4ba)arg1 hasEvents:(id)arg2;
- (void)CADDatabaseGetCalendarsWithFaultedProperties:(id)arg1 reply:(id)arg2;
@end

