/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

@protocol CADSourceInterface
- (void)CADSourceRefresh:(CDStruct_f683c4ba)arg1 isUserRequested:(_Bool)arg2 reply:(id)arg3;
- (void)CADSourceGetConstraints:(CDStruct_f683c4ba)arg1 reply:(id)arg2;
- (void)CADDatabaseGetSources:(id)arg1;
@end

