/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "EKIdentityProtocol-Protocol.h"

@class NSString, NSURL;

// Not exported
@interface EKCalendarEventInvitationNotificationAttendee : NSObject <EKIdentityProtocol>
{
    _Bool _statusChanged;
    _Bool _commentChanged;
    int _participantStatus;
    NSString *_name;
    NSString *_emailAddress;
    NSURL *_url;
    NSString *_comment;
}

@property(readonly, nonatomic) NSString *comment; // @synthesize comment=_comment;
@property(readonly, nonatomic) int participantStatus; // @synthesize participantStatus=_participantStatus;
@property(readonly, nonatomic) _Bool commentChanged; // @synthesize commentChanged=_commentChanged;
@property(readonly, nonatomic) _Bool statusChanged; // @synthesize statusChanged=_statusChanged;
@property(readonly, nonatomic) NSURL *url; // @synthesize url=_url;
@property(readonly, nonatomic) NSString *emailAddress; // @synthesize emailAddress=_emailAddress;
@property(readonly, nonatomic) NSString *name; // @synthesize name=_name;
- (void)dealloc;
- (id)initWithAttendee:(id)arg1;

@end

