/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@class NSDate;

@protocol EKTravelAdvice <NSObject>
@property(readonly, nonatomic) double travelStateScore;
@property(readonly, nonatomic) unsigned long long travelState;
@property(readonly, nonatomic) unsigned long long accidentState;
@property(readonly, nonatomic) unsigned long long trafficLevel;
@property(readonly, nonatomic) NSDate *predictedDepartureTime;
@end

