/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@class EKTravelAgendaItem;

@protocol EKTravelRoutePredictor <NSObject>
@property(nonatomic) EKTravelAgendaItem *agendaItem;
- (void)updateLocation:(id)arg1 handler:(id)arg2;
- (id)initWithSource:(id)arg1 destination:(id)arg2 arrivalDate:(id)arg3 travelMethod:(int)arg4;
@end

