/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "ADBannerViewInternalDelegate-Protocol.h"

@class NSArray, NSMutableArray;

@interface _ADPolicyEngineEvent : NSObject <ADBannerViewInternalDelegate>
{
    id _bannersLoadedHandler;
    NSMutableArray *_banners;
    NSMutableArray *_bannersWaitingOnLoad;
}

@property(retain, nonatomic) NSMutableArray *bannersWaitingOnLoad; // @synthesize bannersWaitingOnLoad=_bannersWaitingOnLoad;
@property(retain, nonatomic) NSMutableArray *banners; // @synthesize banners=_banners;
@property(copy, nonatomic) id bannersLoadedHandler; // @synthesize bannersLoadedHandler=_bannersLoadedHandler;
- (void)bannerView:(id)arg1 didFailToReceiveAdWithError:(id)arg2;
- (void)bannerViewDidLoadAd:(id)arg1;
- (void)_considerCallingLoadedHandler;
- (void)waitForLoadsForBanners:(id)arg1 completionHandler:(id)arg2;
- (id)loadedBannerWithIdentifier:(id)arg1;
@property(readonly, nonatomic) NSArray *bannerIdentifiers;
- (void)addBannerForCreativeType:(int)arg1;
- (id)init;
- (void)dealloc;

@end

