/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "MPMoviePlayerController.h"

@interface MPMoviePlayerController (iAdPreroll)
+ (void)preparePrerollAds;
- (void)set_iAd_prerollController:(id)arg1;
- (id)_iAd_prerollController;
- (void)cancelPreroll;
- (void)playPrerollAdWithCompletionHandler:(id)arg1;
@end

