/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <UIAccessibility/__UIPrintPanelTableViewControllerAccessibility_super.h>

@interface UIPrintPanelTableViewControllerAccessibility : __UIPrintPanelTableViewControllerAccessibility_super
{
}

+ (void)_accessibilityPerformValidations:(id)arg1;
+ (Class)safeCategoryTargetClass;
+ (id)safeCategoryTargetClassName;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;

@end

