/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <UIAccessibility/__UITouchesEventAccessibility_super.h>

@interface UITouchesEventAccessibility : __UITouchesEventAccessibility_super
{
}

+ (Class)safeCategoryTargetClass;
+ (id)safeCategoryTargetClassName;
- (_Bool)_accessibilityHitTestsAnyElement;
- (void)_setAccessibilityHitTestsAnyElement:(_Bool)arg1;
- (void)_setAccessibilityHitTestStartsAtElement:(id)arg1;
- (id)_accessibilityHitTestStartsAtElement;

@end

