/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <ManagedConfiguration/MCPayload.h>

@class NSString;

@interface MCManagedAppPayload : MCPayload
{
    NSString *_managedAppID;
}

+ (id)localizedPluralForm;
+ (id)localizedSingularForm;
+ (id)typeStrings;
@property(retain, nonatomic) NSString *managedAppID; // @synthesize managedAppID=_managedAppID;
- (void).cxx_destruct;
- (id)title;
- (id)initWithManagedAppID:(id)arg1 profile:(id)arg2;

@end

