/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface MCTunnelParser : NSObject
{
}

+ (id)responseWithError:(id)arg1;
+ (id)responseWithStatus:(id)arg1;
- (void)processRequest:(id)arg1 assertion:(id)arg2 completionBlock:(id)arg3;
- (id)_commandDisconnect:(id)arg1;

@end

