/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "_UIRemoteViewController.h"

#import "NCBannerAccessoryHostInterface-Protocol.h"

@interface NCBannerAccessoryHostViewController : _UIRemoteViewController <NCBannerAccessoryHostInterface>
{
    id <NCBannerAccessoryHostViewControllerDelegate> _delegate;
}

+ (id)serviceViewControllerInterface;
+ (id)exportedInterface;
+ (void)requestBannerAccessoryViewControllerWithName:(id)arg1 bundleIdentifier:(id)arg2 context:(id)arg3 completion:(id)arg4;
@property(nonatomic) id <NCBannerAccessoryHostViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)_becomeSticky;
- (void)_dismiss;

@end

