/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "BLAlertViewControllerDelegate-Protocol.h"
#import "UIAlertViewDelegate-Protocol.h"

@class BLAlertAction, BLAlertViewController, NSArray;

@interface BLAlert : NSObject <BLAlertViewControllerDelegate, UIAlertViewDelegate>
{
    BLAlertAction *_cancelAction;
    NSArray *_actions;
    id _conditionBlock;
    id _context;
    id _executionBlock;
    _Bool _showing;
    int _options;
    BLAlertViewController *_alertView;
    BLAlert *_strongSelf;
}

+ (id)popPendingAlert;
+ (void)pushPendingAlert:(id)arg1;
+ (id)pendingAlerts;
+ (void)performWithTitle:(id)arg1 message:(id)arg2 action:(id)arg3;
@property(retain) BLAlert *strongSelf; // @synthesize strongSelf=_strongSelf;
@property(retain) id context; // @synthesize context=_context;
@property(copy) id conditionBlock; // @synthesize conditionBlock=_conditionBlock;
- (void).cxx_destruct;
- (void)alertViewController:(id)arg1 didPressButtonAtIndex:(long long)arg2;
- (_Bool)isShowing;
- (void)setMessage:(id)arg1;
- (void)setTitle:(id)arg1;
- (void)hideWithDelay:(double)arg1 completionBlock:(id)arg2;
- (void)hideWithDelay:(double)arg1;
- (void)cancelDelayedHide;
- (void)hideWithCompletionBlock:(id)arg1;
- (void)hide:(_Bool)arg1;
- (void)hide;
- (void)showWithExecutionBlock:(id)arg1;
- (void)show;
- (void)showPendingAlertIfNeeded;
- (_Bool)wantSingular;
- (void)dealloc;
- (id)initWithTitle:(id)arg1 message:(id)arg2 cancelAction:(id)arg3 otherActions:(id)arg4;
- (id)initWithTitle:(id)arg1 message:(id)arg2 options:(int)arg3 cancelAction:(id)arg4 otherActions:(id)arg5;

@end

