/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol AAUIContactsSearchDelegate <NSObject>
- (void)contactsSearchController:(id)arg1 didFinishSearchWithSuccess:(_Bool)arg2;
- (void)contactsSearchController:(id)arg1 didFindSortedResult:(id)arg2;
@end

