/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSIndexSet, NSString;

@interface _PLKnownAdjustment : NSObject
{
    NSString *_identifier;
    NSIndexSet *_supportedVersions;
    long long _supportLevel;
    id _settingsExtractionBlock;
}

@property(copy, nonatomic) id settingsExtractionBlock; // @synthesize settingsExtractionBlock=_settingsExtractionBlock;
@property(nonatomic) long long supportLevel; // @synthesize supportLevel=_supportLevel;
@property(copy, nonatomic) NSIndexSet *supportedVersions; // @synthesize supportedVersions=_supportedVersions;
@property(copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (id)description;

@end

