/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class CPLResourceTransferTask;

@interface PendingResourceTask : NSObject
{
    CPLResourceTransferTask *_transferTask;
    id _progressBlock;
    id _completionHandler;
}

- (void)dealloc;
- (void)cancelTaskWithIdentifier:(id)arg1;
- (void)reportCompletionForTaskWithIdentifier:(id)arg1 withError:(id)arg2;
- (void)reportProgress:(float)arg1 forTaskWithIdentifier:(id)arg2;
- (id)initWithTransferTask:(id)arg1 progressBlock:(id)arg2 completionHandler:(void)arg3;

@end

