/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "CPLLibraryManagerDelegate-Protocol.h"
#import "CPLResourceProgressDelegate-Protocol.h"
#import "PLForegroundObserver-Protocol.h"

@class CPLLibraryManager, NSMutableArray, NSMutableDictionary, NSObject<OS_dispatch_queue>, NSObject<OS_xpc_object>, PLPhotoLibrary;

@interface PLCLoudPhotoLibraryManager : NSObject <CPLResourceProgressDelegate, CPLLibraryManagerDelegate, PLForegroundObserver>
{
    NSMutableArray *_uploadBatchArray;
    unsigned long long _lastKnownChangeHubEventIndex;
    int _notifyToken;
    NSObject<OS_dispatch_queue> *_isolationQueue;
    NSObject<OS_xpc_object> *_hubConnection;
    unsigned char _nodeUUID[16];
    NSMutableArray *_cameraAsset;
    _Bool _processingChange;
    unsigned long long _mode;
    _Bool _pushOnIdle;
    _Bool _pullOnIdle;
    _Bool _modeChangePending;
    _Bool _closeLibrary;
    _Bool _initialUpload;
    unsigned long long _uploadCounterCheck;
    unsigned long long _downloadCounterCheck;
    NSMutableArray *_downloadedDeleteUuid;
    NSMutableDictionary *_taskIdentifierToPendingResourceTask;
    PLPhotoLibrary *_photoLibrary;
    CPLLibraryManager *_cplLibrary;
    _Bool _stopping;
    _Bool _stopped;
    _Bool _needToResume;
    _Bool _needSoftReset;
    _Bool _pausing;
    unsigned long long _defaultResourceDownloadType;
}

+ (id)descriptionForResourceType:(unsigned long long)arg1;
- (void)foregroundMonitor:(id)arg1 changedStateToForeground:(_Bool)arg2 context:(id)arg3;
- (void)libraryManager:(id)arg1 uploadDidFinishForResourceTransferTask:(id)arg2 withError:(id)arg3;
- (void)libraryManager:(id)arg1 uploadDidStartForResourceTransferTask:(id)arg2;
- (void)libraryManager:(id)arg1 backgroundDownloadDidFinishForResource:(id)arg2;
- (void)_recoverFromPauseUnderDiskPressureIfNeeded;
- (void)_updateAsset:(id)arg1 withImageFileURL:(id)arg2;
- (void)_updateThumbnailDataForAsset:(id)arg1 withImageFileURL:(id)arg2;
- (short)_placeHolderKindFromCPLResourceType:(unsigned long long)arg1;
- (void)_updateWithCPLResource:(id)arg1;
- (void)takeStatisticsSnapshotSinceDate:(id)arg1 completionHandler:(id)arg2;
- (id)_copyTemporaryAssetToFinalPhotoLocationWithResourceIdentity:(id)arg1 withExtension:(id)arg2 withName:(id)arg3;
- (void)_linkFileFrom:(id)arg1 to:(id)arg2;
- (void)libraryManager:(id)arg1 downloadDidFinishForResourceTransferTask:(id)arg2 withError:(id)arg3;
- (void)libraryManager:(id)arg1 downloadDidStartForResourceTransferTask:(id)arg2;
- (void)libraryManager:(id)arg1 downloadDidProgress:(float)arg2 forResourceTransferTask:(id)arg3;
- (void)libraryManagerHasChangesToPull:(id)arg1;
- (void)libraryManagerDidStartSynchronization:(id)arg1;
- (void)libraryManagerStatusDidChange:(id)arg1;
- (void)deleteCPLPlist;
- (void)saveCPLPlistVersion:(id)arg1 forVersionKey:(id)arg2;
- (id)readCPLPlist;
- (void)processDownloadBatchWithSession:(id)arg1;
- (void)_handleRelationRecords:(id)arg1 inLibrary:(id)arg2;
- (void)_handleDeleteRecords:(id)arg1 inLibrary:(id)arg2;
- (void)_handleAssetRecords:(id)arg1 andMasterRecords:(id)arg2 inLibrary:(id)arg3;
- (void)_handleAlbumRecords:(id)arg1 inLibrary:(id)arg2;
- (void)downloadFromCloud;
- (_Bool)needResetSyncErrorType:(id)arg1;
- (id)lastKnownCloudVersionFromDisk;
- (void)_cleanUploadedResources:(id)arg1;
- (void)_processUploadBatchWithStartupFailureCount:(unsigned long long)arg1;
- (void)processUploadBatch;
- (void)prepareEventForUploadProcess:(id)arg1;
- (unsigned long long)diskSpaceLevel;
- (id)createBatchesForChanges:(id)arg1 withContainerChangeForAsset:(_Bool)arg2;
- (_Bool)asset:(id)arg1 isInOrderList:(id)arg2;
- (_Bool)asset:(id)arg1 isIn:(id)arg2;
- (void)sortData:(id)arg1 withMode:(int)arg2 forAssets:(id *)arg3 adjustedAssets:(id *)arg4 andAlbums:(id *)arg5 andOrders:(id *)arg6 inManagedObjectContext:(id)arg7;
- (_Bool)shouldProcessDuringInitialUpload:(id)arg1;
- (id)filterCloudDeleteForKey:(const char *)arg1 fromEvent:(id)arg2;
- (void)uploadToCloudForEvents:(id)arg1;
- (void)uploadFullPhotoLibraryToCloud;
- (void)sendAssets:(id)arg1 toBatchManager:(id)arg2;
- (void)sendAlbums:(id)arg1 toBatchManager:(id)arg2;
- (_Bool)createPathIfNeeded:(id)arg1;
- (void)fetchNewEventsFromChangeHub;
- (void)addLogMark:(id)arg1;
- (void)doSoftResetSync;
- (void)_doResetSync:(_Bool)arg1;
- (void)deleteResourcesIfSafe:(id)arg1 completionHandler:(id)arg2;
- (void)downloadAsset:(id)arg1 resourceType:(unsigned long long)arg2 highPriority:(_Bool)arg3 taskDidBeginHandler:(id)arg4 progressBlock:(void)arg5 completionHandler:(id)arg6;
- (void)fetchPublicURLForAsset:(id)arg1 resourceType:(unsigned long long)arg2 completionHandler:(id)arg3;
- (_Bool)isResourceTransferTaskAliveWithTaskWithIdentifier:(id)arg1;
- (void)cancelResourceTransferTaskWithIdentifier:(id)arg1;
- (void)sync;
- (void)setupHubConnection;
- (void)unregisterToChangeHubNotification;
- (unsigned int)registerToChangeHubNotification;
- (void)_processNextTransaction;
- (void)transitionToState:(unsigned long long)arg1;
- (_Bool)_canExternallyTransitionToNewLibraryModeIgnoringPause:(_Bool)arg1;
- (void)_runOnIsolationQueueAfterDelayInSeconds:(unsigned long long)arg1 withBlock:(id)arg2;
- (void)_runBlockOnIsolationQueue:(id)arg1;
- (void)resume;
- (void)stopAll;
- (void)stop;
- (void)pause;
- (void)unpause;
- (void)resetFlags;
- (void)_releasePowerAssertion;
- (void)_createPowerAssertion;
- (void)dealloc;
- (void)_deactivateCPLLibrary;
- (void)_cleanupCPLLibrary;
- (void)_resetCPLLibrary;
- (void)closeCPLLibrary;
- (void)deactivateCPLLibrary;
- (void)openCPLLibrary;
- (void)deleteExpiredTrashBinObjects;
- (id)init;
- (void)updateLastKnownIndexFromChangeHub;
- (id)_debugNameForMode:(unsigned long long)arg1;

@end

