/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "UIPopoverControllerDelegate-Protocol.h"

@class UIAlertController, UIPopoverController, UIViewController, _UIAlertControllerShimPresenterWindow;

// Not exported
@interface _UIAlertControllerShimPresenter : NSObject <UIPopoverControllerDelegate>
{
    UIPopoverController *_popoverController;
    UIViewController *_presentedViewController;
    _UIAlertControllerShimPresenterWindow *_window;
    UIAlertController *_alertController;
}

+ (id)_topmostAlertWindow;
+ (void)_removePresenter:(id)arg1;
+ (void)_addPresenter:(id)arg1;
+ (id)_currentFullScreenAlertPresenters;
+ (void)_cancelPendingTouchesIfAppropriate;
+ (_Bool)_shouldPresentActionSheetsFullscreen;
@property UIAlertController *alertController; // @synthesize alertController=_alertController;
@property(readonly) _UIAlertControllerShimPresenterWindow *window; // @synthesize window=_window;
- (void)dealloc;
- (id)init;
- (id)_popoverController;
@property id <UIPopoverControllerDelegate> popoverDelegate;
- (void)_dismissAlertControllerAnimated:(_Bool)arg1 completion:(id)arg2;
- (void)_presentAlertControllerFromRect:(struct CGRect)arg1 inView:(id)arg2 animated:(_Bool)arg3 completion:(id)arg4;
- (void)_presentAlertControllerFromBarButtonItem:(id)arg1 animated:(_Bool)arg2 completion:(id)arg3;
- (void)_presentAlertControllerAnimated:(_Bool)arg1 completion:(id)arg2;

@end

