/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <UIKit/UIPresentationController.h>

#import "UIAdaptivePresentationControllerDelegate-Protocol.h"

@class UIView, _UIKeyboardLayoutAlignmentView;

// Not exported
@interface _UIAlertControllerPresentationController : UIPresentationController <UIAdaptivePresentationControllerDelegate>
{
    UIView *_dimmingView;
    _UIKeyboardLayoutAlignmentView *keyboardLayoutAlignmentView;
    UIView *keyboardLayoutAlignmentAvailableSpaceView;
    _Bool addedConstraints;
}

@property(readonly) UIView *_dimmingView; // @synthesize _dimmingView;
- (id)_presentedAlertController;
- (id)presentationController:(id)arg1 viewControllerForAdaptivePresentationStyle:(long long)arg2;
- (long long)adaptivePresentationStyleForPresentationController:(id)arg1;
- (void)setDelegate:(id)arg1;
- (double)constantForAligningAlertControllerToAvailableSpace;
- (long long)attributeToAlignAlertControllerViewBy;
- (void)_addConstraints;
- (void)_occludePresentingWindow:(_Bool)arg1;
- (void)dismissalTransitionDidEnd:(_Bool)arg1;
- (void)dismissalTransitionWillBegin;
- (void)presentationTransitionDidEnd:(_Bool)arg1;
- (void)presentationTransitionWillBegin;
- (_Bool)shouldRemovePresentersView;
- (_Bool)shouldPresentInFullscreen;
- (struct CGRect)frameOfPresentedViewInContainerView;
- (id)presentedView;
- (void)containerViewDidLayoutSubviews;
- (void)containerViewWillLayoutSubviews;
- (long long)adaptivePresentationStyle;
- (void)dealloc;
- (id)initWithPresentingViewController:(id)arg1 presentedViewController:(id)arg2;

@end

