/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <UIKit/UIWindow.h>

@class UIAlertController;

// Not exported
@interface _UIAlertControllerShimPresenterWindow : UIWindow
{
    UIAlertController *_alertController;
}

@property(retain, nonatomic) UIAlertController *alertController;
- (id)_presentationViewController;
- (id)init;

@end

