/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "UIViewControllerAnimatedTransitioning-Protocol.h"

@class NSMutableDictionary, UIPercentDrivenInteractiveTransition, UIView, UIViewController, _UIViewControllerOneToOneTransitionContext;

// Not exported
@interface _UIAnimationCoordinator : NSObject <UIViewControllerAnimatedTransitioning>
{
    NSMutableDictionary *_stash;
    _UIViewControllerOneToOneTransitionContext *_transitionContext;
    UIPercentDrivenInteractiveTransition *_interactiveTransition;
    double _duration;
    id _preperation;
    id _animator;
    id _completion;
    UIView *_containerView;
    UIViewController *_viewController;
    struct CGRect _startFrame;
    struct CGRect _endFrame;
}

@property(nonatomic) struct CGRect endFrame; // @synthesize endFrame=_endFrame;
@property(nonatomic) struct CGRect startFrame; // @synthesize startFrame=_startFrame;
@property(retain, nonatomic) UIViewController *viewController; // @synthesize viewController=_viewController;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(copy, nonatomic) id completion; // @synthesize completion=_completion;
@property(copy, nonatomic) id animator; // @synthesize animator=_animator;
@property(copy, nonatomic) id preperation; // @synthesize preperation=_preperation;
@property(nonatomic) double duration; // @synthesize duration=_duration;
- (void)animationEnded:(_Bool)arg1;
- (void)animateTransition:(id)arg1;
- (double)transitionDuration:(id)arg1;
- (void)finishInteractiveAnimation;
- (void)cancelInteractiveAnimation;
- (void)updateInteractiveProgress:(double)arg1;
- (void)animateInteractively;
- (void)animate;
- (void)_updateTransitionContext;
@property(readonly, retain, nonatomic) NSMutableDictionary *stash;
@property(readonly, retain, nonatomic) _UIViewControllerOneToOneTransitionContext *transitionContext;
- (void)dealloc;

@end

