/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <UIKit/UIPresentationController.h>

@interface _UICurrentContextPresentationController : UIPresentationController
{
}

- (CDStruct_d58201db)__sizeClassPair;
- (struct CGRect)frameOfPresentedViewInContainerView;
- (_Bool)shouldRemovePresentersView;
- (_Bool)_shouldRespectDefinesPresentationContext;
- (_Bool)shouldPresentInFullscreen;

@end

