/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol _UIDocumentPickerViewController <NSObject>
- (void)_prepareWithExtensionInfo:(id)arg1 completionHandler:(id)arg2;
- (void)_showDefaultPicker;
- (void)_setAuxiliaryOptions:(id)arg1;
- (void)_setUploadURL:(id)arg1 withSandboxExtension:(id)arg2;
- (void)_setPickerMode:(unsigned long long)arg1;
- (void)_setPickableTypes:(id)arg1;
@end

