/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSSecureCoding-Protocol.h"

@class NSString, UIImage;

// Not exported
@interface _UIDocumentPickerAuxiliaryOption : NSObject <NSSecureCoding>
{
    NSString *_title;
    UIImage *_image;
    NSString *_identifier;
    id _handler;
    unsigned long long _order;
}

+ (_Bool)supportsSecureCoding;
@property(nonatomic) unsigned long long order; // @synthesize order=_order;
@property(copy, nonatomic) id handler; // @synthesize handler=_handler;
@property(copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)dealloc;
- (id)init;

@end

