/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <UIKit/UIView.h>

// Not exported
@interface _UIDebugColorBoundsView : UIView
{
}

+ (id)_nextColor;
- (void)doesNotRecognizeSelector:(SEL)arg1;
- (void)_removeColorViewBoundsOverlay;
- (id)_colorViewBoundsOverlayCreateIfNecessary:(_Bool)arg1;
- (id)initWithView:(id)arg1;

@end

