/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <UIKit/_UICurrentContextPresentationController.h>

// Not exported
@interface _UIFullscreenPresentationController : _UICurrentContextPresentationController
{
}

- (void)_setPresentedViewController:(id)arg1;
- (_Bool)_shouldChangeStatusBarViewController;
- (struct CGRect)frameOfPresentedViewInContainerView;
- (_Bool)_shouldRespectDefinesPresentationContext;
- (_Bool)shouldRemovePresentersView;
- (_Bool)shouldPresentInFullscreen;

@end

