/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "CALayer.h"

@class _UILabelContentLayer;

// Not exported
@interface _UILabelLayer : CALayer
{
    _UILabelContentLayer *_contentLayer;
    _Bool _contentInsetsValid;
    struct UIEdgeInsets _contentInsets;
}

- (void)setMasksToBounds:(_Bool)arg1;
- (void)_updateContentLayer;
- (void)invalidateContentInsets;
- (void)setNeedsDisplayInRect:(struct CGRect)arg1;
- (void)setBounds:(struct CGRect)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (void)layoutSublayers;
- (void)updateContentLayerSize;
- (void)updateContentInsets;
- (void)dealloc;

@end

