/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "_UIScrollNotification-Protocol.h"

@class UIScrollView;

// Not exported
@interface _UISearchControllerDidScrollDelegate : NSObject <_UIScrollNotification>
{
    UIScrollView *_scrollView;
    id <_UIScrollNotification> _controller;
}

@property(nonatomic) id <_UIScrollNotification> controller; // @synthesize controller=_controller;
- (void)_updateBackdropMaskViewsInScrollView:(id)arg1;
- (void)_didScroll;
@property(nonatomic) UIScrollView *scrollView;
- (void)dealloc;

@end

