/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <UIKit/_UIVisualEffectSubview.h>

// Not exported
@interface _UIVisualEffectFilterView : _UIVisualEffectSubview
{
}

- (void)_setLayerConfig:(id)arg1;
- (id)_initWithFrame:(struct CGRect)arg1 config:(id)arg2;
- (id)_initWithFrame:(struct CGRect)arg1 settings:(id)arg2 type:(long long)arg3;

@end

