/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSLayoutConstraint.h"

@class _NSLayoutConstraintConstant;

@interface NSLayoutConstraint (UIInterfaceBuilderSupport)
@property(getter=_encodedConstant, setter=_setEncodedConstant:) _NSLayoutConstraintConstant *encodedConstant;
@end

