/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol NSMetadataQueryDelegate <NSObject>

@optional
- (id)metadataQuery:(id)arg1 replacementValueForAttribute:(id)arg2 value:(id)arg3;
- (id)metadataQuery:(id)arg1 replacementObjectForResultObject:(id)arg2;
@end

