/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <UIKit/UIApplication.h>

// Not exported
@interface UIIBApplication : UIApplication
{
    long long _statusBarOrientation;
}

+ (_Bool)rendersLocally;
- (long long)statusBarOrientation;
- (void)setStatusBarOrientation:(long long)arg1 animationParameters:(id)arg2;
- (id)init;

@end

