/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <UIKit/UIViewController.h>

#import "UITextInputDelegate-Protocol.h"
#import "_UITextDocumentInterfaceDelegate-Protocol.h"

@class NSObject<UITextDocumentProxy>, UIInputView, UIKeyboard;

@interface UIInputViewController : UIViewController <_UITextDocumentInterfaceDelegate, UITextInputDelegate>
{
    NSObject<UITextDocumentProxy> *_textDocumentProxy;
}

+ (_Bool)_requiresProxyInterface;
@property(readonly, nonatomic) NSObject<UITextDocumentProxy> *textDocumentProxy; // @synthesize textDocumentProxy=_textDocumentProxy;
- (void)_didResetDocumentState;
- (void)_willResetDocumentState;
- (void)textDidChange:(id)arg1;
- (void)textWillChange:(id)arg1;
- (void)selectionDidChange:(id)arg1;
- (void)selectionWillChange:(id)arg1;
- (void)requestSupplementaryLexiconWithCompletion:(id)arg1;
- (void)returnToPreviousInputMode;
- (void)advanceToNextInputMode;
- (void)dismissKeyboard;
- (void)setView:(id)arg1;
@property(retain, nonatomic) UIInputView *inputView;
- (id)_textDocumentInterface;
- (id)_proxyInterface;
- (id)_compatibilityController;
@property(readonly, nonatomic) UIKeyboard *_keyboard;
- (void)_setExtensionContext:(id)arg1;
- (id)extensionContext;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (void)loadView;
- (void)_setTextDocumentProxy:(id)arg1;
- (void)dealloc;
- (void)_setupInputController;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

