/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <UIKit/UICollectionView.h>

@class NSIndexPath;

// Not exported
@interface UIKBCandidateCollectionView : UICollectionView
{
}

- (void)configureAsCandidatesBar;
- (_Bool)_selectAndScrollToItemAtIndexPath:(id)arg1 animated:(_Bool)arg2 scrollPosition:(unsigned long long)arg3;
@property(readonly, nonatomic) NSIndexPath *selectedItemIndexPath;

@end

