/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <UIKit/UIStoryboardSegue.h>

// Not exported
@interface UIStoryboardShowSegue : UIStoryboardSegue
{
    SEL _action;
}

@property(nonatomic) SEL action; // @synthesize action=_action;
- (void)perform;

@end

