/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <UIKit/UIStoryboardSegueTemplate.h>

@class NSString;

// Not exported
@interface UIStoryboardShowSegueTemplate : UIStoryboardSegueTemplate
{
    NSString *_action;
}

@property(copy, nonatomic) NSString *action; // @synthesize action=_action;
- (id)segueWithDestinationViewController:(id)arg1;
- (id)defaultSegueClassName;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)dealloc;

@end

