/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class NSString, UILabel, UITableView, UITapGestureRecognizer;

// Not exported
@interface UITableViewIndexOverlayIndicatorView : UIView
{
    UILabel *_label;
    UITapGestureRecognizer *_tapGestureRecognizer;
    UITableView *_table;
}

@property(copy, nonatomic) NSString *currentText;
- (void)layoutSubviews;
- (void)_willChangeToIdiom:(long long)arg1 onScreen:(id)arg2;
- (void)dealloc;
- (void)_invalidateTable;
- (void)_tapGestureChanged:(id)arg1;
- (id)initWithTable:(id)arg1;

@end

