/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface GKBubbleShape : NSObject
{
    struct GKVertexCurve *_vertexCurves;
    unsigned long long _vertexCount;
    double _vertexVariance;
    double _controlpointVariance;
    double _endpointVariance;
}

+ (id)standardBubbleShape;
+ (id)standardBezierPathForSize:(struct CGSize)arg1;
@property(nonatomic) double endpointVariance; // @synthesize endpointVariance=_endpointVariance;
@property(nonatomic) double controlpointVariance; // @synthesize controlpointVariance=_controlpointVariance;
@property(nonatomic) double vertexVariance; // @synthesize vertexVariance=_vertexVariance;
@property(nonatomic) unsigned long long vertexCount; // @synthesize vertexCount=_vertexCount;
@property(nonatomic) struct GKVertexCurve *vertexCurves; // @synthesize vertexCurves=_vertexCurves;
- (void)generateVertexCurves;
- (id)pathForSize:(struct CGSize)arg1;
- (void)dealloc;
- (id)initWithVertexCount:(unsigned long long)arg1 vertexVariance:(double)arg2 endpointVariance:(double)arg3 controlpointVariance:(double)arg4;

@end

