/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <GameCenterPrivateUI/GKBubbleControl.h>

@class GKBubbleStackedContentView, NSArray;

@interface GKBubbleWithStackedContent : GKBubbleControl
{
    double _maximumDimension;
    GKBubbleStackedContentView *_contentView;
    NSArray *_dimensionConstraints;
}

+ (double)maximumDimensionBasedOnDeviceAdjustForTallness:(_Bool)arg1;
+ (void)initialize;
@property(retain, nonatomic) NSArray *dimensionConstraints; // @synthesize dimensionConstraints=_dimensionConstraints;
@property(retain, nonatomic) GKBubbleStackedContentView *contentView; // @synthesize contentView=_contentView;
@property(nonatomic) double paddingSizeMultiplier;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (struct CGSize)intrinsicContentSize;
- (void)invalidateIntrinsicContentSize;
- (void)setCenter:(struct CGPoint)arg1;
- (void)dealloc;
- (void)didMoveToWindow;
- (void)updateConstraints;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) double maximumDimension;

@end

