/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UICollectionReusableView.h"

@class GKHairlineView;

@interface GKColumnDividerView : UICollectionReusableView
{
    GKHairlineView *_hairlineView;
}

@property(retain, nonatomic) GKHairlineView *hairlineView; // @synthesize hairlineView=_hairlineView;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

