/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UICollectionReusableView.h"

#import "GKStateMachineDelegate-Protocol.h"

@class GKPlaceholderContentStateMachine, GKPlaceholderView, NSString, UIActivityIndicatorView;

@interface GKCollectionViewPlaceholderView : UICollectionReusableView <GKStateMachineDelegate>
{
    GKPlaceholderView *_placeholderView;
    NSString *_loadingState;
    NSString *_noContentTitle;
    NSString *_noContentMessage;
    NSString *_errorTitle;
    NSString *_errorMessage;
    UIActivityIndicatorView *_loadingIndicatorView;
    GKPlaceholderContentStateMachine *_loadingMachine;
}

@property(retain, nonatomic) GKPlaceholderContentStateMachine *loadingMachine; // @synthesize loadingMachine=_loadingMachine;
@property(retain, nonatomic) UIActivityIndicatorView *loadingIndicatorView; // @synthesize loadingIndicatorView=_loadingIndicatorView;
@property(retain, nonatomic) NSString *errorMessage; // @synthesize errorMessage=_errorMessage;
@property(retain, nonatomic) NSString *errorTitle; // @synthesize errorTitle=_errorTitle;
@property(retain, nonatomic) NSString *noContentMessage; // @synthesize noContentMessage=_noContentMessage;
@property(retain, nonatomic) NSString *noContentTitle; // @synthesize noContentTitle=_noContentTitle;
@property(retain, nonatomic) NSString *loadingState; // @synthesize loadingState=_loadingState;
@property(retain, nonatomic) GKPlaceholderView *placeholderView; // @synthesize placeholderView=_placeholderView;
- (void)didExitErrorState;
- (void)didEnterErrorState;
- (void)didExitNoContentState;
- (void)didEnterNoContentState;
- (void)didExitLoadingState;
- (void)didEnterLoadingState;
- (void)delayedShowLoadingIndicator;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

