/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIImageView.h"

@class UIImage;

@interface GKFixedSizeImageView : UIImageView
{
    UIImage *_actualImage;
}

@property(retain, nonatomic) UIImage *actualImage; // @synthesize actualImage=_actualImage;
- (void)invalidateIntrinsicContentSize;
- (void)setImage:(id)arg1;
- (id)image;
- (void)dealloc;

@end

