/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "UIViewControllerAnimatorTransitioning-Protocol.h"

@class _GKBubbleFlowTransitionInfo;

@interface GKTabBarTransitionAnimator : NSObject <UIViewControllerAnimatorTransitioning>
{
    _GKBubbleFlowTransitionInfo *_transitionInfo;
}

@property(retain, nonatomic) _GKBubbleFlowTransitionInfo *transitionInfo; // @synthesize transitionInfo=_transitionInfo;
- (void)animationEnded:(_Bool)arg1;
- (void)_animateTransitionInTwoParts:(id)arg1;
- (void)_animateTransition:(id)arg1;
- (void)animateTransition:(id)arg1;
- (void)dealloc;
- (double)transitionDuration:(id)arg1;

@end

