/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <GameCenterPrivateUI/GKValueWithCaptionBubbleControl.h>

@class GKLabel, NSAttributedString, NSString;

@interface GKTextBubbleControl : GKValueWithCaptionBubbleControl
{
}

@property(retain, nonatomic) GKLabel *textLabel;
@property(retain, nonatomic) NSAttributedString *attributedText;
@property(retain, nonatomic) NSString *text;
- (void)setAttributedCaptionText:(id)arg1;
- (void)setCaptionLabel:(id)arg1;
- (void)setCaptionText:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

