/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <AddressBookUI/ABContactHeaderView.h>

#import "ABContactPhotoViewDelegate-Protocol.h"
#import "ABPropertyGroupItemDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSArray, UITableView;

@interface ABContactHeaderEditView : ABContactHeaderView <UITableViewDelegate, UITableViewDataSource, ABPropertyGroupItemDelegate, ABContactPhotoViewDelegate>
{
    UITableView *_editingTable;
    NSArray *_editingGroups;
    id <ABPropertyCellDelegate> _namePropertyDelegate;
    id <ABContactHeaderViewDelegate> _headerDelegate;
}

+ (id)contactHeaderViewWithContact:(id)arg1 editingGroups:(id)arg2;
@property(nonatomic) id <ABContactHeaderViewDelegate> headerDelegate; // @synthesize headerDelegate=_headerDelegate;
@property(nonatomic) id <ABPropertyCellDelegate> namePropertyDelegate; // @synthesize namePropertyDelegate=_namePropertyDelegate;
@property(retain, nonatomic) NSArray *editingGroups; // @synthesize editingGroups=_editingGroups;
- (id)_phoneticNameForValue:(id)arg1 isFamilyName:(_Bool)arg2;
- (void)didUpdatePhoto;
- (void)propertyItem:(id)arg1 willChangeValue:(id)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (_Bool)tableView:(id)arg1 shouldIndentWhileEditingRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (void)setBackgroundColor:(id)arg1;
- (id)selectEditingGroupAtIndex:(unsigned long long)arg1;
- (_Bool)photoIsModified;
- (_Bool)hasPhoto;
- (void)reloadData;
- (void)updateConstraints;
- (void)updateFontSizes;
- (void)setEditingGroups:(id)arg1 withUpdate:(_Bool)arg2;
- (void)dealloc;
- (id)initWithContact:(id)arg1 editingGroups:(id)arg2 frame:(struct CGRect)arg3;

@end

