/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UITableViewController.h"

#import "ABPresenterDelegate-Protocol.h"

@class ABCardPropertyGroup, CNMutableContact, NSMutableArray;

@interface ABPostalAddressEditorViewController : UITableViewController <ABPresenterDelegate>
{
    NSMutableArray *_propertyItems;
    CNMutableContact *_contact;
    ABCardPropertyGroup *_propertyGroup;
}

+ (id)cellIdentifierForClass:(Class)arg1;
+ (id)cellIdentifierForEditingProperty:(id)arg1;
@property(readonly) _Bool isPresentingModalViewController;
- (void)sender:(id)arg1 dismissViewController:(id)arg2;
- (void)sender:(id)arg1 presentViewController:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)registerContactCellClass:(Class)arg1;
- (void)_startEditingFirstCell;
- (void)done:(id)arg1;
- (void)cancel:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)title;
- (void)_rebuildPropertyGroupItems;
- (void)dealloc;
- (id)initWithContact:(id)arg1;

@end

