/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <AddressBookUI/ABLabeledCell.h>

@class UILabel;

@interface ABPropertyPlaceholderCell : ABLabeledCell
{
    UILabel *_label;
}

@property(retain, nonatomic) UILabel *label; // @synthesize label=_label;
- (double)minCellHeight;
- (void)setCardGroupItem:(id)arg1;
- (_Bool)shouldPerformDefaultAction;
- (id)labelView;
- (void)dealloc;

@end

