/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "ABContactActionDelegate-Protocol.h"

@protocol ABPropertyActionDelegate <ABContactActionDelegate>
- (id)action:(id)arg1 cellForPropertyItem:(id)arg2 sender:(id)arg3;
@end

